import type { Cond } from '../engine/types';
import type { Order } from './agenda';

// POWERS OF THE MOMENT
// Orders that exist only because of the situation: the season, the state of the
// country, the electoral calendar, a rising rival, something just done. The
// engine offers a handful at a time, each for a few months. When the moment
// passes, so does the option.

const all = (...c: Cond[]): Cond => ({ all: c });
const v = (path: string, op: '<' | '<=' | '>' | '>=' | '==', n: number): Cond => ({ v: [path, op, n] });
const moment = { group: 'moment', situational: true } as const;

export const SITUATIONAL: Order[] = [
  {
    ...moment, id: 'blame', name: 'Blame the previous administration', pc: 0, naira: 0, cooldown: 5, window: 14,
    when: { turn: [1, 14] },
    blurb: 'A press conference on the state in which you found things. It is true, it works, and it stops working after about a year.',
    result: 'The Minister of Information presents "The Rot We Met", with slides. The country nods. It will nod a little less each time.',
    fx: [['approval', 2], ['bloc.street', 2], ['bloc.press', -2], ['counter.blamed', 1]],
    news: ['FG PUBLISHES "THE ROT WE MET"', 'GOVERNMENT SAY NA THE LAST PEOPLE CAUSE AM'],
    archive: 'Blamed the previous administration.',
  },
  // ---------------------------------------------------------------- the first hundred days
  {
    ...moment, id: 'assets', name: 'Publish your own assets on day one', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [1, 6] }, v('exposure.count', '==', 0)),
    blurb: 'Before anyone asks. It will never be this cheap again, and it binds you for the rest of the term.',
    result: 'The declaration is published in full. Three newspapers print it. The cabinet reads it with visible unease.',
    fx: [['nation.integrity', 4], ['bloc.press', 6], ['approval', 2], ['bloc.villa', -4]],
    flags: { 'assets.published': true },
    news: ['PRESIDENT PUBLISHES ASSET DECLARATION', 'PRESIDENT SHOW US EVERYTHING E GET'],
    archive: 'Published your asset declaration in your first months.', sig: 2,
  },
  {
    ...moment, id: 'convoy', name: 'Austerity at the top', pc: 0, naira: 0, cooldown: 0, window: 6,
    when: { turn: [1, 10] },
    levels: [
      { label: 'Your convoy and travel', word: 'the convoy', scale: 0.6 },
      { label: 'And half the air fleet', word: 'the convoy and half the air fleet', scale: 1 },
      { label: 'And halve political pay', word: 'the convoy, the air fleet and political pay', scale: 1.6, pc: 10 },
    ],
    blurb: 'The savings are small. The symbolism is not, and everyone beneath you will be expected to follow. The further it goes, the more of them object.',
    result: 'The cuts go through: {AMT}. Ministers are told the same applies to them. The Assembly is "invited to follow", and forms a committee to consider the invitation.',
    fx: [['approval', 3], ['bloc.street', 4], ['bloc.villa', -5], ['nation.fiscalSpace', 0.1], ['bloc.party', -4]],
    news: ['PRESIDENT ORDERS AUSTERITY AT THE TOP', 'PRESIDENT DON CUT HIM OWN BELLE FIRST'],
    archive: 'Ordered austerity at the top: {AMT}.', sig: 2,
  },
  {
    ...moment, id: 'merge', name: 'Merge the ministries: 48 down to 24', pc: 14, naira: 0, cooldown: 0, window: 6,
    when: { turn: [1, 10] },
    blurb: 'Only possible while your mandate is fresh. Every ministry abolished is a minister, a permanent secretary and four hundred directors.',
    result: 'Twenty-four ministries are abolished by order. The civil service unions threaten, the party sulks, and the wage bill falls for the first time in a generation.',
    fx: [['nation.capacity', 5], ['bonus.fiscal', 0.025], ['bloc.party', -8], ['bloc.establishment', -5], ['bloc.press', 4]],
    news: ['PRESIDENT HALVES NUMBER OF MINISTRIES', '24 MINISTRIES DON CLOSE. BIG MEN DON LOSE OFFICE'],
    archive: 'Merged forty-eight ministries into twenty-four.', sig: 3,
  },

  // ---------------------------------------------------------------- hardship and prices
  {
    ...moment, id: 'price_control', name: 'Impose price controls on staple foods', pc: 4, naira: 0, cooldown: 30,
    when: v('nation.inflation', '>', 27),
    blurb: 'A legal maximum price for rice, bread and garri. Popular within the hour. Shelves respond within the month.',
    result: 'The task force fans out with clipboards. Prices fall at the stalls that are inspected. At the others, goods simply stop appearing.',
    fx: [['approval', 4], ['bloc.street', 6], ['bloc.establishment', -6]],
    later: [{ after: [3, 5], fx: [['bonus.inflation', 1.5], ['approval', -4], ['nation.jobs', -2]], label: 'Price controls empty the shelves and feed a black market.', note: ['STAPLES VANISH FROM MARKETS UNDER PRICE CONTROLS', 'GARRI NO DEY MARKET. NA BLACK MARKET WE DEY BUY'] }],
    news: ['FG FIXES MAXIMUM PRICES FOR STAPLE FOODS', 'GOVERNMENT DON FIX PRICE OF RICE'],
    archive: 'Imposed price controls on staple foods.', sig: 2,
  },
  {
    ...moment, id: 'grain_release', name: 'Release the grain reserve onto the market', pc: 0, naira: 0, cooldown: 0,
    when: all({ flag: 'grain.reserve' }, v('nation.inflation', '>', 24)),
    blurb: 'You filled the silos in a good year. This is what they were for.',
    result: 'Two million tonnes go to market at cost. Prices of grain fall by a quarter in a fortnight. The silos are empty again, having done their job.',
    fx: [['nation.inflation', -3], ['approval', 3], ['bloc.street', 5]],
    flags: { 'grain.reserve': false },
    news: ['GRAIN RESERVE RELEASE CUTS FOOD PRICES', 'GOVERNMENT OPEN SILO. RICE DON CHEAP'],
    archive: 'Released the grain reserve to bring food prices down.', sig: 2,
  },
  {
    ...moment, id: 'vouchers', name: 'Transport vouchers for workers and students', pc: 0, naira: 0.35, cooldown: 18,
    levels: [{ label: 'Four million', word: 'four million', scale: 0.5, naira: 0.18 }, { label: 'Eight million', word: 'eight million', scale: 1 }, { label: 'Twelve million', word: 'twelve million', scale: 1.4, naira: 0.5 }],
    when: all({ flag: 'policy.subsidy', is: 'removed' }, v('hardship', '>', 55)),
    blurb: 'Targets the people the pump price hurts most, without bringing the subsidy back.',
    result: 'Vouchers go out to {AMT} workers and students through employers and schools. Fares are still high. Getting to work is no longer the first thing people mention.',
    fx: [['bloc.street', 7], ['approval', 3], ['pressure.wageGrievance', -14]],
    news: ['FG ISSUES TRANSPORT VOUCHERS TO {AMT}', 'TRANSPORT VOUCHER DON LAND FOR WORKERS'],
    archive: 'Issued transport vouchers to workers and students.',
  },
  {
    ...moment, id: 'xmas', name: 'A thirteenth-month salary for civil servants', pc: 0, naira: 0.25, cooldown: 11, window: 2,
    levels: [{ label: 'Half a month', word: 'half a month\'s', scale: 0.5, naira: 0.13 }, { label: 'A full month', word: 'a full month\'s', scale: 1 }],
    when: { month: [11, 12] },
    blurb: 'It is December. Everyone remembers who paid and who did not.',
    result: 'The alert arrives on the nineteenth. For one week the civil service is the most contented institution in the country.',
    fx: [['bloc.street', 4], ['bloc.establishment', 3], ['approval', 2], ['pressure.wageGrievance', -8]],
    news: ['FG PAYS 13TH-MONTH SALARY', 'CHRISTMAS BONUS DON ENTER'],
    archive: 'Paid civil servants a thirteenth-month salary.',
  },
  {
    ...moment, id: 'airlift', name: 'Emergency fertiliser before the rains', pc: 0, naira: 0.3, cooldown: 11, window: 3, target: 'zone',
    when: all({ month: [3, 4, 5] }, v('agenda.f1', '==', 0)),
    blurb: 'Planting starts in weeks. There are trucks for one region in time. Fertiliser delivered in August is a photo opportunity; in April it is a harvest.',
    result: 'Trucks reach the farms of {T} before the first rain. Some of it is diverted. Most of it is spread. The other regions notice whose farms came first.',
    fx: [['zone.$Z.approval', 6], ['approval', 0.5]],
    later: [{ after: [6, 8], fx: [['nation.inflation', -1.5], ['zone.$Z.approval', 3], ['approval', 1]], label: 'The harvest is better in {T}, where the fertiliser arrived on time.', note: ['HARVEST UP 20% WHERE INPUTS ARRIVED EARLY', 'FOOD DON PLENTY FOR {T_SHORT} THIS YEAR'] }],
    news: ['FG RUSHES FERTILISER TO {T_SHORT} AHEAD OF RAINS', 'FERTILISER REACH FARM BEFORE RAIN, FOR ONCE'],
    archive: 'Rushed fertiliser to farmers in {T} before the planting season.',
  },

  // ---------------------------------------------------------------- money
  {
    ...moment, id: 'bank_tax', name: 'A windfall tax aimed at one fortune', pc: 8, naira: 0, cooldown: 12, target: 'tycoon', hostile: 3,
    when: v('nation.debt', '>', 70),
    blurb: 'Somebody made record profits while the country did not. Write a levy that happens to fit one business exactly. It raises money and it sends a message; the rest of the business class receives it.',
    result: 'The levy is drafted so narrowly that only {T}\'s companies qualify. It raises ₦600bn in a quarter. Other chairmen check their own accounts.',
    fx: [['nation.fiscalSpace', 0.6], ['tycoon.$T', -25], ['bloc.establishment', -4], ['bloc.street', 3]],
    news: ['FG IMPOSES WINDFALL LEVY; {T_SHORT} GROUP HARDEST HIT', '{T_SHORT} DON MAKE TOO MUCH MONEY. GOVERNMENT DON COLLECT'],
    archive: 'Imposed a windfall tax written to fit {T}.', sig: 2,
  },
  {
    ...moment, id: 'asset_sale', name: 'Sell the state\'s idle assets, to a buyer you choose', pc: 8, naira: 0, cooldown: 0, target: 'tycoon',
    when: v('nation.debt', '>', 78),
    blurb: 'Eleven thousand abandoned federal properties, four hotels, a fleet of aircraft. A public auction would take years. A single buyer, chosen by you, would take a month and be grateful for a decade.',
    result: 'The portfolio goes to {T} in one transaction, at a price the Chronicle calls generous. Several properties turn out to be occupied by former ministers, who are given ninety days.',
    fx: [['nation.fiscalSpace', 1.1], ['nation.debt', -3], ['tycoon.$T', 15], ['bloc.party', -5], ['nation.integrity', -2]],
    news: ['FG SELLS FEDERAL PROPERTIES TO {T_SHORT} GROUP', 'GOVERNMENT DON SELL ALL THE HOUSE GIVE ONE MAN'],
    archive: 'Sold the federal government\'s idle assets to {T}.', sig: 2,
  },
  {
    ...moment, id: 'tax_cut', name: 'Cut taxes on small businesses', pc: 0, naira: 0, cooldown: 0,
    when: v('nation.fiscalSpace', '>=', 2.5),
    blurb: 'You have the room. Forty million small traders pay eleven different levies to five different agencies.',
    result: 'Businesses under ₦50m turnover are exempted. The informal sector does not formalise overnight. It does stop hiding.',
    fx: [['nation.jobs', 5], ['bonus.fiscal', -0.02], ['bonus.jobs', 0.03], ['bloc.street', 4], ['approval', 2]],
    news: ['FG EXEMPTS SMALL BUSINESSES FROM COMPANY TAX', 'SMALL BUSINESS NO GO PAY TAX AGAIN'],
    archive: 'Exempted small businesses from company tax.', sig: 2,
  },
  {
    ...moment, id: 'capex_surge', name: 'A capital spending surge', pc: 0, naira: 1.5, cooldown: 30,
    when: v('nation.fiscalSpace', '>=', 3),
    blurb: 'Release every stalled capital vote at once while you can pay for it. Contractors will actually be on site.',
    result: 'Capital releases hit 90% for the first time anyone at the Budget Office can recall. Cranes appear.',
    fx: [['nation.jobs', 5], ['nation.power', 3], ['approval', 2], ['bloc.party', 4]],
    later: [{ after: [8, 12], fx: [['nation.jobs', 4], ['nation.power', 3], ['nation.security', 2]], label: 'Projects funded in the capital surge are completed.' }],
    news: ['FG RELEASES 90% OF CAPITAL BUDGET', 'CONTRACTORS DON RETURN TO SITE'],
    archive: 'Released almost the entire capital budget at once.', sig: 2,
  },

  // ---------------------------------------------------------------- emergencies
  {
    ...moment, id: 'emergency_rule', name: 'Declare a state of emergency in one state', pc: 10, naira: 0.2, cooldown: 12, target: 'governor', hostile: 3,
    when: all(v('nation.security', '<', 40), v('senate', '>=', 48)),
    blurb: 'Federal control of security in one state, and the governor sidelined. Needs the Senate. You choose the state, which means you choose the governor.',
    result: 'The Senate approves by four votes. Troops move into {T_ZONE} under a single command. {T} learns the details from the radio and says so at length.',
    fx: [['theatre.$Z', -12], ['nation.security', 3], ['person.$T', -22], ['zone.$Z.approval', -2], ['bloc.party', -4], ['nation.integrity', -1]],
    later: [{ after: [5, 7], fx: [['theatre.$Z', -6], ['approval', 1]], label: 'Emergency rule reopens the roads in {T_ZONE}.' }],
    news: ['STATE OF EMERGENCY DECLARED; {T_SHORT} SIDELINED', 'EMERGENCY RULE: SOLDIERS DON TAKE OVER {T_SHORT} STATE'],
    archive: 'Declared a state of emergency and sidelined {T}.', sig: 3,
  },
  {
    ...moment, id: 'borders', name: 'Close the land borders', pc: 4, naira: 0, cooldown: 0,
    when: v('nation.security', '<', 38),
    blurb: 'Stops the guns and the smuggled rice. Also stops the trade that a third of the border states live on.',
    result: 'The borders close at midnight. Arms seizures fall. So do the neighbours\' economies, and they say so loudly.',
    fx: [['nation.security', 4], ['bonus.inflation', 1.5], ['nation.jobs', -3], ['zone.NW.approval', -3], ['zone.SW.approval', -3]],
    flags: { 'borders.closed': true },
    news: ['NIGERIA CLOSES LAND BORDERS', 'BORDER DON CLOSE. RICE GO COST'],
    archive: 'Closed the land borders.', sig: 2,
  },
  {
    ...moment, id: 'borders_open', name: 'Reopen the land borders', pc: 0, naira: 0, cooldown: 0,
    when: { flag: 'borders.closed' },
    blurb: 'It did what it could. It is now mostly costing you.',
    result: 'The borders reopen. Trade resumes within the hour, including the kinds you closed them to stop.',
    fx: [['bonus.inflation', -1.5], ['nation.jobs', 3], ['nation.security', -2], ['zone.NW.approval', 3], ['zone.SW.approval', 3]],
    flags: { 'borders.closed': false },
    news: ['LAND BORDERS REOPEN', 'BORDER DON OPEN. MARKET DON BOUNCE'],
    archive: 'Reopened the land borders.',
  },
  {
    ...moment, id: 'checkpoints', name: 'Take the checkpoints off the highways', pc: 6, naira: 0, cooldown: 0,
    when: v('nation.security', '>', 48),
    blurb: 'Security is good enough now. There are 300 checkpoints between Lagos and Kano, and every one of them charges.',
    result: 'The checkpoints come down. A lorry of tomatoes reaches Lagos from Kano in fourteen hours instead of four days.',
    fx: [['nation.jobs', 4], ['bonus.inflation', -1], ['approval', 3], ['bloc.establishment', -4], ['nation.integrity', 2]],
    news: ['300 HIGHWAY CHECKPOINTS DISMANTLED', 'NO MORE "WETIN YOU CARRY" FOR ROAD'],
    archive: 'Dismantled the highway checkpoints.', sig: 2,
  },
  {
    ...moment, id: 'relocate', name: 'Move the river communities to higher ground', pc: 6, naira: 0.5, cooldown: 0,
    when: all(v('count.flood', '>=', 1), { not: { flag: 'flood.defences' } }),
    blurb: 'Cheaper than the dams. People have lived on those banks for four hundred years and will not thank you.',
    result: 'Sixty thousand households are offered land and a grant. Two thirds accept. The rest say they will see you at the next flood.',
    fx: [['zone.NC.approval', -3], ['nation.capacity', 1]],
    flags: { 'flood.defences': true },
    news: ['FG RESETTLES 40,000 FLOOD-PLAIN HOUSEHOLDS', 'GOVERNMENT SAY MAKE DEM COMMOT FROM RIVERSIDE'],
    archive: 'Relocated river communities instead of building flood defences.', sig: 2,
  },

  // ---------------------------------------------------------------- integrity
  {
    ...moment, id: 'inquiry', name: 'A public inquiry into what went wrong', pc: 6, naira: 0, cooldown: 0,
    when: { any: [v('venture.steel', '==', -1), v('venture.rail', '==', -1), v('venture.crypto', '==', -1), v('venture.charter', '==', -1)] },
    blurb: 'Your big bet failed. Say so, in public, with the documents. It costs pride and buys back some trust.',
    result: 'The inquiry sits in public for six weeks. It finds what everyone knew. It is the first time anyone has said it on oath.',
    fx: [['nation.integrity', 4], ['bloc.press', 6], ['approval', 2], ['bloc.villa', -3], ['nation.capacity', 2]],
    news: ['PRESIDENT ORDERS PUBLIC INQUIRY INTO FAILED PROJECT', 'PRESIDENT GREE SAY THE THING FAIL'],
    archive: 'Ordered a public inquiry into your own failed project.', sig: 2,
  },

  // ---------------------------------------------------------------- the street and the press
  {
    ...moment, id: 'dialogue', name: 'A national dialogue with the young', pc: 4, naira: 0, cooldown: 0, econ: 'anger',
    when: v('bloc.street', '<', 35),
    blurb: 'Not a summit. Town halls, unscripted, in six cities, with you in the chair and no screening of questions.',
    result: 'The first one lasts four hours. You are shouted at for three. In the fourth, somebody says thank you for coming, and means it.',
    fx: [['bloc.street', 10], ['approval', 2], ['bloc.press', 4], ['pressure.wageGrievance', -8]],
    news: ['PRESIDENT FACES ANGRY TOWN HALL FOR FOUR HOURS', 'PRESIDENT SIDDON MAKE YOUTH YAB AM FOR FOUR HOURS'],
    archive: 'Held unscripted town halls with young people in six cities.', sig: 2,
  },
  {
    ...moment, id: 'ban_protest', name: 'Ban a rival\'s rallies', pc: 6, naira: 0, cooldown: 8, target: 'rival', hostile: 3,
    when: { termTurn: [24, 48] },
    blurb: 'The police discover security concerns at every venue one candidate books. It works for a while. Their supporters do not forget, and neither does the press.',
    result: 'Every rally {T} schedules is refused a permit on security grounds. The candidate holds them in churches, mosques and car parks, and films the police outside.',
    fx: [['rival.$T', -9], ['bloc.press', -6], ['nation.integrity', -3], ['bloc.street', -2], ['bloc.establishment', 2]],
    later: [{ after: [3, 5], fx: [['rival.$T', 4]], label: 'The car-park rallies of {T} draw bigger crowds than the stadiums would have.' }],
    news: ['POLICE REFUSE {T_SHORT} RALLY PERMITS NATIONWIDE', 'POLICE NO GREE {T_SHORT} DO RALLY'],
    archive: 'Had the police ban {T}\'s rallies.', sig: 3,
  },
  {
    ...moment, id: 'station', name: 'Have a newspaper\'s licence suspended', pc: 6, naira: 0, cooldown: 8, target: 'paper', hostile: 2,
    when: v('bloc.press', '<', 40),
    blurb: 'The regulator can find a breach in anything if asked. What it costs depends on whose paper it is: the paper of record, the street\'s paper, a businessman\'s, or the opposition\'s.',
    result: '{T} is off the newsstands by morning. It is online by noon, to five times the readers.',
    fx: [['paper', 1], ['nation.integrity', -2], ['approval', -1]],
    flags: { 'press.gag': true },
    news: ['REGULATOR SUSPENDS {T}', 'DEM SHUT DOWN {T}. E DON GO ONLINE'],
    archive: 'Had {T} suspended.', sig: 3,
  },

  // ---------------------------------------------------------------- the party and the rivals
  {
    ...moment, id: 'convention', name: 'Call an emergency party convention', pc: 8, naira: 0, cooldown: 30, econ: 'party',
    when: v('bloc.party', '<', 38),
    blurb: 'Put the leadership to a vote before they put you to one. You might lose control of your own party in public.',
    result: 'Three thousand delegates fill Eagle Square. You speak for an hour. The chairman survives; his faction does not get the secretariat.',
    fx: [['bloc.party', 12], ['pc', 4]],
    news: ['RULING PARTY HOLDS EMERGENCY CONVENTION', 'PARTY PEOPLE GATHER. PRESIDENT HOLD GROUND'],
    archive: 'Called an emergency party convention.', sig: 2,
  },
  {
    ...moment, id: 'coopt_fire', name: 'Offer the firebrand a ministry', pc: 8, naira: 0, cooldown: 0,
    when: v('rival.fire', '>', 52),
    blurb: 'He has two million followers and no office. Inside the government he is one voice in cabinet. He may refuse, loudly.',
    result: 'He accepts Youth and Digital Economy. Half his followers call it betrayal. The other half start following the ministry\'s account.',
    fx: [['rival.fire', -22], ['bloc.street', 5], ['bloc.party', -5], ['nation.jobs', 2]],
    news: ['OPPOSITION FIREBRAND JOINS CABINET', 'ENOUGH-IS-ENOUGH DON ENTER GOVERNMENT. E SHOCK US'],
    archive: 'Brought the opposition firebrand into the cabinet.', sig: 3,
  },
  {
    ...moment, id: 'woo_strong', name: 'Bring the defector home', pc: 6, naira: 0, cooldown: 0,
    when: v('rival.strong', '>', 52),
    blurb: 'He left with his delegates. He will come back for the Senate presidency or a clear run at the succession.',
    result: 'He returns "to his political family" at a rally. The price was a promise about the succession that you will have to keep or break.',
    fx: [['rival.strong', -25], ['bloc.party', 10], ['nation.integrity', -2]],
    flags: { 'promise.second_term': true },
    news: ['SENATOR DECAMP RETURNS TO RULING PARTY', 'DECAMP DON DECAMP BACK'],
    archive: 'Brought the defecting senator back with a promise about the succession.', sig: 2,
  },
  {
    ...moment, id: 'steal_alt', name: 'Adopt the opposition\'s best idea', pc: 4, naira: 0.3, cooldown: 0,
    when: v('rival.alt', '>', 52),
    blurb: 'His manifesto has one genuinely good proposal: a single window for every business permit. Take it. Credit him or do not.',
    result: 'The single window opens. He complains that it was his idea, which makes him sound like a man complaining that something good happened.',
    fx: [['rival.alt', -18], ['nation.jobs', 4], ['nation.capacity', 2], ['bloc.establishment', 4]],
    news: ['FG LAUNCHES SINGLE WINDOW FOR BUSINESS PERMITS', 'PRESIDENT DON COPY OPPOSITION HOMEWORK'],
    archive: 'Adopted the opposition\'s best policy as your own.', sig: 2,
  },
  {
    ...moment, id: 'retreat', name: 'Take the governors on a retreat', pc: 4, naira: 0.05, cooldown: 20,
    when: all(v('person.gov_sw', '<', 48), v('person.gov_ss', '<', 48)),
    blurb: 'Three days, no aides, no phones. Half of governing here is being in the same room.',
    result: 'By the second evening they are complaining about each other instead of about you, which is the purpose of a retreat.',
    fx: [['bloc.party', 7], ['person.gov_sw', 10], ['person.gov_ss', 10], ['person.gov_nw', 8], ['person.gov_nc', 8], ['person.gov_ne', 8], ['person.gov_se', 8]],
    news: ['PRESIDENT, GOVERNORS HOLD THREE-DAY RETREAT', 'PRESIDENT AND GOVERNORS GO HIDE FOR THREE DAYS'],
    archive: 'Took the governors on a three-day retreat.',
  },

  // ---------------------------------------------------------------- popularity, spent or lost
  {
    ...moment, id: 'cash_in', name: 'Spend your popularity on the party', pc: 0, naira: 0, cooldown: 30, econ: 'popularity',
    when: v('approval', '>', 62),
    blurb: 'You are popular enough that nobody in the party dares refuse you. That does not last. Use it.',
    result: 'You call in every senator and governor in a week and tell each what you expect. Nobody argues. Several take notes.',
    fx: [['pc', 18], ['bloc.party', 8], ['approval', -2]],
    news: ['PRESIDENT SUMMONS PARTY LEADERS IN SHOW OF STRENGTH', 'PRESIDENT DEY FLEX. NOBODY FIT TALK'],
    archive: 'Used high approval to bring the party into line.',
  },
  {
    ...moment, id: 'apology', name: 'A purge and an apology', pc: 6, naira: 0, cooldown: 0,
    when: v('approval', '<', 36),
    blurb: 'Sack the six least popular people around you, say plainly what went wrong, and ask for another hearing. It only works once.',
    result: 'You speak for nine minutes and use the word "wrong" about your own government four times. The six leave by the side gate.',
    fx: [['approval', 6], ['bloc.street', 8], ['bloc.press', 6], ['bloc.villa', -8], ['bloc.party', -4]],
    news: ['"WE GOT IT WRONG" — PRESIDENT SACKS SIX, RESETS', 'PRESIDENT SAY SORRY, SACK SIX PEOPLE'],
    archive: 'Purged your inner circle and apologised to the country.', sig: 3,
  },

  // ---------------------------------------------------------------- abroad
  {
    ...moment, id: 'state_visit', name: 'A state visit to bring back investment', pc: 0, naira: 0.05, cooldown: 14, target: 'tycoon',
    when: v('bloc.establishment', '>=', 45),
    blurb: 'Ten days, three capitals, a plane full of businessmen, and one of them in the seat beside yours. Works when the numbers at home are credible.',
    result: 'You return with $4bn in signed commitments; {T} signs the largest of them. About half of signed commitments ever arrive. That is still two.',
    fx: [['bloc.establishment', 4], ['tycoon.$T', 10]],
    later: [{ after: [6, 10], fx: [['nation.jobs', 5], ['nation.fiscalSpace', 0.3]], label: 'Investment pledged on the state visit begins to arrive.', note: ['FIRST FACTORIES OPEN FROM STATE VISIT PLEDGES', 'THE INVESTMENT WEY PRESIDENT GO FIND DON LAND'] }],
    news: ['PRESIDENT RETURNS WITH $4BN IN PLEDGES; {T_SHORT} ALONGSIDE', 'PRESIDENT DON RETURN FROM ABROAD WITH PROMISE'],
    archive: 'Made a state visit to secure foreign investment, with {T} beside you.',
  },
  {
    ...moment, id: 'cbn', name: 'Replace the central bank governor', pc: 14, naira: 0, cooldown: 0,
    when: all(v('senate', '>=', 54), v('nation.inflation', '>', 24), { turn: [8] }),
    blurb: 'She was appointed by your predecessor and answers to nobody. Removing her needs two thirds of the Senate, which you currently have.',
    result: 'The Senate votes 76 to 31. Your nominee takes office. The bank is now yours, including everything it does next.',
    fx: [['bonus.inflation', -2], ['bloc.establishment', -6], ['nation.integrity', -2]],
    news: ['SENATE REMOVES CENTRAL BANK GOVERNOR', 'CBN GOVERNOR DON GO. PRESIDENT PERSON DON ENTER'],
    archive: 'Removed the central bank governor with a Senate vote.', sig: 3,
  },

  // ---------------------------------------------------------------- the electoral calendar
  {
    ...moment, id: 'wage_decree', name: 'An election-year pay rise for civil servants', pc: 0, naira: 0.5, cooldown: 0, window: 6,
    levels: [{ label: '15%', word: '15%', scale: 0.5, naira: 0.25 }, { label: '30%', word: '30%', scale: 1 }, { label: '50%', word: '50%', scale: 1.6, naira: 0.8 }],
    when: all({ term: 1 }, { termTurn: [34, 44] }),
    blurb: 'The election is months away. Two million federal workers and their families vote.',
    result: 'A {AMT} rise takes effect from January. The opposition calls it a bribe, and promises to keep it.',
    fx: [['approval', 3], ['bloc.street', 6], ['pressure.wageGrievance', -18], ['bonus.fiscal', -0.03], ['bloc.establishment', -3]],
    news: ['FG APPROVES {AMT} PAY RISE FOR CIVIL SERVANTS', 'ELECTION DON NEAR: SALARY DON INCREASE'],
    archive: 'Raised civil service pay months before the election.', sig: 2,
  },
  {
    ...moment, id: 'commission_all', name: 'Commission everything that has a ribbon', pc: 0, naira: 0.1, cooldown: 0, window: 6,
    when: all({ term: 1 }, { termTurn: [38, 44] }),
    blurb: 'Finished, nearly finished, and one or two that are mostly a signboard. A tour of all six zones.',
    result: 'You cut forty-one ribbons in three weeks. Thirty are real. The press visits the other eleven the following Monday.',
    fx: [['approval', 3], ['bloc.party', 4], ['bloc.press', -4], ['nation.integrity', -1]],
    news: ['PRESIDENT COMMISSIONS 41 PROJECTS IN THREE WEEKS', 'PRESIDENT COMMISSION 41 PROJECT. ELEVEN NA SIGNBOARD'],
    archive: 'Commissioned forty-one projects in the run-up to the election.',
  },
  {
    ...moment, id: 'debate', name: 'Challenge your rival to a televised debate', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: all({ term: 1 }, { termTurn: [40, 44] }),
    blurb: 'Incumbents usually refuse. If your record is good, this is where it counts. If it is not, this is where it is read back to you.',
    result: 'Ninety minutes, live, no notes.',
    fx: [['bloc.press', 5]],
    later: [
      { after: 1, when: v('hardship', '<', 48), fx: [['approval', 4], ['bloc.street', 3]], label: 'You won the debate on the record.', note: ['PRESIDENT WINS DEBATE ON THE RECORD', 'PRESIDENT FINISH OPPOSITION FOR DEBATE'] },
      { after: 1, when: v('hardship', '>=', 48), fx: [['approval', -4], ['bloc.street', -3]], label: 'The debate turned on prices, and you lost it.', note: ['PRESIDENT STUMBLES ON COST OF LIVING IN DEBATE', 'DEM ASK PRESIDENT PRICE OF GARRI. E NO SABI'] },
    ],
    news: ['PRESIDENT TO DEBATE CHALLENGER LIVE', 'DEBATE! PRESIDENT VS OPPOSITION, LIVE'],
    archive: 'Debated your challenger live on television.', sig: 2,
  },

  // ---------------------------------------------------------------- the second term
  {
    ...moment, id: 'pardon', name: 'A presidential pardon for political prisoners and debtors', pc: 6, naira: 0, cooldown: 0,
    when: { term: 2 },
    blurb: 'Journalists, protesters, and forty thousand people in jail for fines under ₦50,000. You no longer need anyone\'s permission.',
    result: 'The prisons release 41,000 people in a week. The Controller of Prisons notes that the food budget is now adequate for the first time.',
    fx: [['bloc.street', 6], ['bloc.press', 6], ['nation.integrity', 3], ['bloc.establishment', -3], ['approval', 2]],
    news: ['PRESIDENT PARDONS 41,000', '41,000 PEOPLE DON COMMOT FROM PRISON'],
    archive: 'Pardoned 41,000 prisoners, including journalists and protesters.', sig: 3,
  },
  {
    ...moment, id: 'unpopular', name: 'Do the unpopular thing nobody facing an election would', pc: 12, naira: 0, cooldown: 0,
    when: all({ term: 2 }, { termTurn: [4, 30] }),
    blurb: 'Cost-reflective pricing across the board: water, tolls, tuition, rail. You will never be on a ballot again.',
    result: 'It is announced on a Friday. By Monday you are the least popular second-term President on record, and the agencies are solvent.',
    fx: [['bonus.fiscal', 0.05], ['approval', -6], ['bloc.street', -8], ['bloc.establishment', 8], ['nation.capacity', 3]],
    news: ['FG ENDS BELOW-COST PRICING ACROSS PUBLIC SERVICES', 'EVERYTHING DON COST. PRESIDENT NO SEND'],
    archive: 'Ended below-cost pricing across public services in your second term.', sig: 3,
  },
  {
    ...moment, id: 'monument', name: 'Build something with your name on it', pc: 0, naira: 0.8, cooldown: 0, target: 'state', place: 'The national library bearing your name',
    when: all({ term: 2 }, { termTurn: [20, 44] }),
    blurb: 'A presidential library, a national theatre, a bridge. Every second-term President does it. Few of them are finished. Where you put it is a statement.',
    result: 'The foundation stone is laid in {T}. It bears your name in letters you approved personally.',
    fx: [['bloc.villa', 4], ['zone.$Z.approval', 3], ['approval', -1], ['bloc.press', -3]],
    later: [{ after: [14, 18], when: v('nation.capacity', '>=', 50), fx: [['approval', 2], ['zone.$Z.approval', 5], ['nation.jobs', 2]], label: 'Your monument in {T} is completed and opened.', note: ['NATIONAL LIBRARY OPENS IN {T_SHORT}', 'THE BIG LIBRARY DON OPEN. E FINE'] }],
    news: ['PRESIDENT LAYS FOUNDATION OF NATIONAL LIBRARY IN {T_SHORT}', 'PRESIDENT DEY BUILD MONUMENT WEY CARRY PRESIDENT NAME'],
    archive: 'Began a monument bearing your name in {T}.', sig: 2,
  },
// ---------------------------------------------------------------- initiatives of your own
  // Not responses to anything. Things a President might simply decide to do,
  // each once, each with someone who loses.
  {
    ...moment, id: 'vip_police', name: 'Take the police off VIP escort duty', pc: 6, naira: 0, cooldown: 0, window: 5,
    when: { turn: [5] },
    blurb: 'A third of the police force guards politicians and their wives. Put them back on the street. Every one of those politicians has your number.',
    result: '110,000 officers return to stations. Crime falls. Senators discover what traffic is like.',
    fx: [['nation.security', 6], ['approval', 2], ['bloc.party', -6], ['bloc.establishment', -5], ['bonus.security', 0.03]],
    news: ['110,000 POLICE WITHDRAWN FROM VIP DUTY', 'BIG MAN NO GET POLICE ESCORT AGAIN'],
    archive: 'Withdrew the police from VIP escort duty.', sig: 2,
  },
  {
    ...moment, id: 'open_data', name: 'Publish every statistic the government holds', pc: 4, naira: 0, cooldown: 0, window: 5,
    when: { turn: [6] },
    blurb: 'Budget releases, oil volumes, school enrolment, all of it, monthly. Some of the numbers are bad and will be news.',
    result: 'The portal goes live. Journalists find eleven stories in the first week. Nine are unflattering. All are true.',
    fx: [['nation.capacity', 2], ['nation.integrity', 3], ['bloc.press', 5], ['approval', -1], ['bonus.integrity', 0.02]],
    news: ['FG OPENS ALL OFFICIAL STATISTICS TO PUBLIC', 'GOVERNMENT DON PUT ALL THE NUMBER FOR INTERNET'],
    archive: 'Published all government statistics monthly.',
  },
  {
    ...moment, id: 'exam_fees', name: 'Abolish examination fees', pc: 0, naira: 0.15, cooldown: 0, window: 5,
    levels: [{ label: 'Secondary exams', word: 'secondary school', scale: 1 }, { label: 'And university entrance', word: 'secondary and university entrance', scale: 1.5, naira: 0.25 }],
    when: { turn: [7] },
    blurb: 'Two million children a year do not sit their final exams because of a ₦27,000 fee.',
    result: 'Fees are abolished from this session. Registrations rise by a third.',
    fx: [['bloc.street', 5], ['approval', 2], ['bonus.fiscal', -0.008]],
    news: ['FG SCRAPS SECONDARY EXAM FEES', 'EXAM DON FREE'],
    archive: 'Abolished {AMT} examination fees.',
  },
  {
    ...moment, id: 'lg_autonomy', name: 'Pay local governments directly, starting with one state', pc: 12, naira: 0, cooldown: 0, window: 5, target: 'governor', hostile: 3,
    when: { turn: [8] },
    blurb: 'Council allocations go to the governors first and mostly stay there. Send them straight to the 774 councils, and make an example of one governor first. All of them will treat it as war; one of them will take it personally.',
    result: 'The first direct payments go to the councils of {T_ZONE}, with the audit published. {T} calls it an invasion. Thirty-five other governors compare notes.',
    fx: [['bloc.street', 5], ['nation.capacity', 3], ['nation.integrity', 2], ['bloc.party', -8], ['person.$T', -20], ['zone.$Z.approval', 2],
      ['person.gov_nw', -5], ['person.gov_ne', -5], ['person.gov_nc', -5], ['person.gov_sw', -5], ['person.gov_se', -5], ['person.gov_ss', -5]],
    news: ['LOCAL GOVERNMENTS TO RECEIVE ALLOCATIONS DIRECTLY; {T_SHORT} FIRST', 'LOCAL GOVERNMENT MONEY NO GO PASS GOVERNOR HAND AGAIN'],
    archive: 'Paid local government allocations directly, and made an example of {T}.', sig: 3,
  },
  {
    ...moment, id: 'ports24', name: 'Order the ports to work around the clock', pc: 4, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [9] }, v('agenda.i1', '==', 0)),
    blurb: 'The ports close at five. The ships do not. A directive, not a reform; it helps until someone finds a way round it.',
    result: 'Night shifts begin. Clearance times fall by a third. The agencies that lived off the delay are inventive, and will adapt.',
    fx: [['nation.jobs', 3], ['bonus.inflation', -0.5], ['bloc.establishment', -3]],
    news: ['PORTS BEGIN 24-HOUR OPERATIONS', 'PORT DEY WORK FOR NIGHT NOW'],
    archive: 'Ordered the ports to operate around the clock.',
  },
  {
    ...moment, id: 'census', name: 'Hold the census, at last', pc: 6, naira: 0.4, cooldown: 0, window: 6,
    when: { turn: [10] },
    blurb: 'Nobody knows how many Nigerians there are. Every state believes it has more than it is credited with, and revenue follows the number.',
    result: 'The count is held, digitally, in eleven days. The result pleases nobody, which the statisticians take as evidence of accuracy.',
    fx: [['nation.capacity', 5], ['bloc.establishment', 3]],
    later: [{ after: [3, 5], fx: [['bloc.party', -6], ['zone.NW.approval', -2], ['zone.SW.approval', -2], ['zone.SE.approval', -2]], label: 'The census figures are published and disputed by every state.', note: ['STATES REJECT CENSUS FIGURES', 'EVERY STATE SAY THEIR NUMBER NO CORRECT'] }],
    news: ['NIGERIA HOLDS FIRST CENSUS IN TWO DECADES', 'DEM DON COUNT US AT LAST'],
    archive: 'Held the first census in two decades.', sig: 2,
  },
  {
    ...moment, id: 'currency', name: 'Redesign the currency to flush out hoarded cash', pc: 6, naira: 0.1, cooldown: 0, econ: 'weak', window: 5,
    when: all({ turn: [12] }, v('nation.integrity', '<', 45)),
    blurb: 'Old notes expire in ninety days. Billions held in vaults and soakaways must surface or die. So must every market trader\'s savings.',
    result: 'The old notes expire before the new ones arrive. People sleep at cash machines. A man in Kano pays a transfer fee to buy bread. The hoarders changed theirs in bulk, quietly, in the first week.',
    fx: [['approval', -5], ['bloc.street', -8], ['nation.jobs', -3], ['nation.integrity', 2], ['pressure.scandalHeat', -8], ['bloc.party', -4]],
    news: ['CASH SHORTAGE AS OLD NOTES EXPIRE', 'NO CASH! PEOPLE DEY SLEEP FOR ATM'],
    archive: 'Redesigned the currency and caused a nationwide cash shortage.', sig: 3,
  },
  {
    ...moment, id: 'directors', name: 'Retire every director past eight years in post', pc: 8, naira: 0, cooldown: 0, window: 5,
    when: { turn: [14] },
    blurb: 'The rule exists and has never been enforced. Eleven hundred directors, each of whom knows where the files are.',
    result: 'They go in a single circular. A generation of deputies, who have been doing the work, finally get the offices.',
    fx: [['nation.capacity', 5], ['bloc.establishment', -7], ['bloc.villa', -3], ['bonus.capacity', 0.03]],
    news: ['1,100 DIRECTORS RETIRED IN CIVIL SERVICE SHAKE-UP', 'OLD OGAS DON GO. YOUNG ONES DON ENTER'],
    archive: 'Enforced the tenure rule and retired 1,100 directors.', sig: 2,
  },
  {
    ...moment, id: 'trade_pact', name: 'Open the continental free-trade corridor', pc: 6, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [16] }, { not: { flag: 'borders.closed' } }),
    blurb: 'Tariff-free trade with fifty countries. Your exporters gain a continent. Your weaker manufacturers gain competitors.',
    result: 'The first tariff-free consignments cross. Cement and noodles go out. Textiles come in.',
    fx: [['nation.jobs', 4], ['bonus.jobs', 0.03], ['bonus.inflation', -0.5], ['bloc.establishment', -4]],
    news: ['NIGERIA BEGINS TARIFF-FREE CONTINENTAL TRADE', 'WE DON START TO SELL TO THE WHOLE AFRICA'],
    archive: 'Opened tariff-free trade under the continental pact.', sig: 2,
  },
  {
    ...moment, id: 'homecoming', name: 'A year of return for the diaspora', pc: 0, naira: 0.1, cooldown: 0, econ: 'revenue', window: 5,
    when: { turn: [18] },
    blurb: 'Visa on arrival, a property guarantee, a festival. Seventeen million people with foreign salaries and aging parents.',
    result: 'December flights are full from October. The money spent in a month exceeds a quarter of oil revenue.',
    fx: [['nation.fiscalSpace', 0.5], ['nation.jobs', 2], ['bloc.street', 2], ['approval', 1]],
    news: ['RECORD DIASPORA ARRIVALS FOR "YEAR OF RETURN"', 'ABROAD PEOPLE FULL EVERYWHERE THIS DECEMBER'],
    archive: 'Declared a year of return for the diaspora.',
  },
  {
    ...moment, id: 'summit', name: 'Host an investment summit', pc: 0, naira: 0.1, cooldown: 26, window: 4,
    when: all({ turn: [9] }, v('bloc.establishment', '>=', 40)),
    blurb: 'Two thousand delegates, forty heads of industry. It works if there is something real to show them.',
    result: 'The summit runs for three days. The hotels are full. The pledges will be tested against what they find when they visit a ministry.',
    fx: [['bloc.establishment', 3]],
    later: [
      { after: [6, 9], when: v('nation.capacity', '>=', 42), fx: [['nation.jobs', 4], ['nation.fiscalSpace', 0.2]], label: 'Investment pledged at the summit arrives.' },
      { after: [6, 9], when: v('nation.capacity', '<', 42), fx: [['bloc.press', -3]], label: 'Most summit pledges never arrive.', note: ['SUMMIT PLEDGES: 6% HAVE MATERIALISED', 'THE INVESTORS COME, SEE, COMMOT'] },
    ],
    news: ['2,000 DELEGATES ATTEND ABUJA INVESTMENT SUMMIT', 'BIG SUMMIT FOR ABUJA. HOTEL FULL'],
    archive: 'Hosted an investment summit.',
  },
  // ---------------------------------------------------------------- aimed at someone
  {
    ...moment, id: 'probe', name: 'A public inquiry into a governor or senator', pc: 6, naira: 0, cooldown: 6, target: 'politician', hostile: 3,
    when: { termTurn: [6, 46] },
    blurb: 'A panel, televised, with the power to subpoena. Aim it at an enemy and it ruins them. Aim it at a friend and it makes the point to everyone else.',
    result: 'The panel sits in public. {T}\'s accounts are read into the record, one transfer at a time. Allies stop returning calls.',
    fx: [['person.$T', -16], ['bloc.press', 3], ['nation.integrity', 1], ['bloc.party', -4], ['zone.$Z.approval', -1]],
    news: ['PANEL OPENS PUBLIC INQUIRY INTO {T}', 'DEM DON CARRY {T_SHORT} GO PANEL'],
    archive: 'Set a public inquiry on {T}.', sig: 2,
  },
  {
    ...moment, id: 'detail', name: 'Withdraw a politician\'s security detail', pc: 3, naira: 0, cooldown: 4, target: 'politician', hostile: 2,
    when: { turn: [4, 96] },
    blurb: 'The police escort, the armoured car, the men at the gate: all federal. Recall them and see how brave a governor or senator feels driving home.',
    result: '{T}\'s police escort is recalled overnight for "redeployment". The armoured car is collected at dawn. {T_SHORT} travels with a private guard and a public grievance.',
    fx: [['person.$T', -14], ['bloc.party', -2], ['nation.integrity', -1]],
    news: ['POLICE WITHDRAW {T_SHORT}\'S SECURITY DETAIL', 'DEM DON COLLECT {T_SHORT} POLICE'],
    archive: 'Withdrew {T}\'s security detail.', sig: 1,
  },
  {
    ...moment, id: 'agency_move', name: 'Move a federal agency out of a governor\'s state', pc: 5, naira: 0.1, cooldown: 8, target: 'governor', hostile: 2,
    when: { turn: [6, 96] },
    blurb: 'Three thousand jobs and a headquarters building, transferred for "operational efficiency". The governor loses the jobs and the contracts, and the voters know whom to blame.',
    result: 'The agency\'s trucks leave {T_ZONE} on a Monday. {T} calls it punishment. The receiving state calls it overdue.',
    fx: [['person.$T', -15], ['zone.$Z.approval', -3], ['bloc.party', -2], ['nation.capacity', -1]],
    news: ['FEDERAL AGENCY RELOCATED OUT OF {T_SHORT} STATE', 'DEM DON CARRY THE AGENCY COMOT FOR {T_SHORT} STATE'],
    archive: 'Moved a federal agency out of {T}\'s state.', sig: 1,
  },
  {
    ...moment, id: 'project', name: 'Site a federal project where a friend needs it', pc: 0, naira: 0.3, cooldown: 4, target: 'politician',
    when: { turn: [3, 96] },
    blurb: 'A road, a hospital, a university campus. It goes somewhere; it may as well go where it buys someone. The money is spent either way.',
    result: 'Ground is broken in {T_ZONE}, with {T} holding the shovel next to you. The plaque has both names on it.',
    fx: [['person.$T', 14], ['zone.$Z.approval', 2], ['bloc.party', 1]],
    news: ['FG FLAGS OFF ROAD PROJECT; {T_SHORT} HAILS PRESIDENT', 'ROAD DON START FOR {T_SHORT} AREA'],
    archive: 'Sited a federal project to please {T}.', sig: 1,
  },
  {
    ...moment, id: 'licence', name: 'Revoke a businessman\'s licence', pc: 8, naira: 0, cooldown: 10, target: 'tycoon', hostile: 4,
    when: { turn: [6, 96] },
    blurb: 'Import permits, a banking licence, a broadcasting frequency, a depot: every fortune in the country rests on a paper you can withdraw. The rest of them will be watching.',
    result: 'The regulator withdraws {T}\'s licence at 4pm on a Friday, citing irregularities. Shares fall by a third by Monday. Every other chairman calls their lawyer, then calls you.',
    fx: [['tycoon.$T', -35], ['bloc.establishment', -6], ['nation.jobs', -1], ['nation.integrity', -2], ['bloc.street', 2]],
    news: ['REGULATOR REVOKES {T_SHORT} GROUP LICENCE', 'GOVERNMENT DON CANCEL {T_SHORT} LICENCE'],
    archive: 'Revoked {T}\'s licence.', sig: 2,
  },
  {
    ...moment, id: 'waiver', name: 'Grant a businessman a waiver', pc: 2, naira: 0, cooldown: 6, target: 'tycoon',
    when: { turn: [3, 96] },
    blurb: 'Duty-free imports, a tax holiday, an exemption from a rule everyone else follows. The treasury loses what it would have collected. Something comes back to you.',
    result: 'The waiver is signed without a press release. {T} sends thanks through an intermediary, and something else through another.',
    fx: [['tycoon.$T', 18], ['nation.fiscalSpace', -0.25], ['nation.integrity', -2], ['purse', 10]],
    exposure: { kind: 'personal', amount: 10, witnesses: ['fin'], trail: 2 },
    news: ['QUESTIONS OVER {T_SHORT} GROUP IMPORT WAIVER', 'WHO GIVE {T_SHORT} WAIVER?'],
    archive: 'Granted {T} a waiver.', sig: 1,
  },
  {
    ...moment, id: 'dossier', name: 'Leak a file on a rival', pc: 4, naira: 0, cooldown: 8, target: 'rival', hostile: 3,
    when: { termTurn: [18, 48] },
    blurb: 'The agencies keep files on everyone who matters. One of them could find its way to a newspaper. Whether it is true matters less than whether it is printed; whether it is traced back matters a great deal.',
    result: 'A file on {T} reaches the Chronicle\'s newsroom in a brown envelope. It runs on Sunday. On Monday the paper starts asking where it came from.',
    fx: [['rival.$T', -12], ['nation.integrity', -3], ['bloc.press', -2]],
    later: [{ after: [4, 6], fx: [['rival.$T', 4]], label: 'Sympathy for {T}: the leak is traced towards the Villa, and a victim polls better than a suspect.' }],
    exposure: { kind: 'political', amount: 0, witnesses: ['info'], trail: 2 },
    news: ['LEAKED FILE RAISES QUESTIONS ABOUT {T}', 'DEM DON LEAK {T_SHORT} FILE'],
    archive: 'Leaked a file on {T}.', sig: 2,
  },
  // ---------------------------------------------------------------- the way out
  {
    group: 'politics', id: 'exit_abroad', name: 'Move money abroad, quietly', pc: 0, naira: 0, cooldown: 0,
    when: all({ termTurn: [38, 48] }, { any: [v('exposure.kept', '>=', 20), v('purse', '>=', 20)] }),
    blurb: 'A property in a foreign capital, an account in a friendlier jurisdiction, a residence permit nobody needs to know about. If it goes wrong after you leave, you will have somewhere to go.',
    result: 'The transfers go through in small amounts over six weeks. A flat is bought through a company registered in a name that is almost yours.',
    fx: [['nation.integrity', -1]],
    flags: { 'exit.abroad': true },
    exposure: { kind: 'personal', amount: 0, witnesses: ['fin'], trail: 1 },
    news: ['QUESTIONS OVER PROPERTY PURCHASE ABROAD', 'DEM SAY BIG MAN DON BUY HOUSE FOR OVERSEAS'],
    archive: 'Moved money abroad against the day you might need it.', sig: 1,
  },
  {
    group: 'politics', id: 'exit_immunity', name: 'A law protecting former Presidents', pc: 15, naira: 0, cooldown: 0,
    when: all({ term: 2 }, { termTurn: [36, 46] }, v('senate', '>=', 55)),
    blurb: 'Lifelong immunity from prosecution for acts in office, dressed as protection for the dignity of the office. It will pass if the Senate is yours. Everyone will know exactly who it is for.',
    result: 'The bill passes on a voice vote at eleven at night. The Chronicle prints the names of every senator present. The street prints a cartoon.',
    fx: [['nation.integrity', -5], ['bloc.press', -8], ['bloc.street', -4], ['approval', -2]],
    flags: { 'exit.immunity': true },
    news: ['SENATE PASSES IMMUNITY FOR FORMER PRESIDENTS', 'DEM DON PASS LAW SAY PRESIDENT NO GO JAIL'],
    archive: 'Had the Senate grant former Presidents immunity.', sig: 3,
  },
  // ---------------------------------------------------------------- the naira
  {
    group: 'economy', id: 'fx_float', name: 'Let the naira float', pc: 10, naira: 0, cooldown: 6,
    when: v('fx.float', '==', 0),
    blurb: 'One rate, set by the market. Most of the gap to the street rate closes at the end of the month; prices jump with it. The black market dies, dollars come back, and the importers who lived on official allocations lose their business.',
    result: 'The central bank announces a single market rate. The street rate and the official rate meet within a week. Bureau de change operators stand outside empty kiosks.',
    fx: [['bloc.establishment', 6], ['bloc.street', -4], ['bloc.press', 2], ['nation.integrity', 1], ['tycoon.ty_trade', -10], ['tycoon.ty_maker', 6]],
    flags: { 'fx.stance': 'float' },
    news: ['NAIRA FLOATED: CBN ENDS MULTIPLE EXCHANGE RATES', 'NAIRA DON FREE. PRICE GO RISE BEFORE E SETTLE'],
    archive: 'Floated the naira.', sig: 3,
  },
  {
    group: 'economy', id: 'fx_managed', name: 'Return the naira to a managed rate', pc: 4, naira: 0, cooldown: 6,
    when: { not: { flag: 'fx.stance', is: 'managed' } },
    blurb: 'The central bank lets the rate move, but slowly, spending reserves to smooth it. A small premium on the street, a slow drain when dollars are short.',
    result: 'The central bank announces it will "manage volatility". The market waits to see what that means.',
    fx: [['bloc.establishment', 1]],
    flags: { 'fx.stance': 'managed' },
    news: ['CBN RETURNS TO MANAGED EXCHANGE RATE', 'CBN SAY DEM GO DEY MANAGE NAIRA'],
    archive: 'Returned the naira to a managed rate.', sig: 1,
  },
  {
    group: 'economy', id: 'fx_peg', name: 'Defend the naira', pc: 6, naira: 0, cooldown: 6,
    when: { not: { flag: 'fx.stance', is: 'peg' } },
    blurb: 'Hold the official rate where it is, selling reserves to anyone who asks at that price. It keeps import prices down for as long as the reserves last. The street rate goes its own way, and whoever gets dollars at the official rate gets rich.',
    result: 'The Governor of the central bank announces the rate "will not be allowed to fall". Importers queue at the banks. The street rate opens higher the next morning.',
    fx: [['bloc.street', 3], ['bloc.establishment', -4], ['tycoon.ty_trade', 8], ['tycoon.ty_maker', -4]],
    flags: { 'fx.stance': 'peg' },
    news: ['CBN VOWS TO DEFEND THE NAIRA', 'CBN SAY NAIRA NO GO FALL. WE DEY WATCH'],
    archive: 'Ordered the central bank to defend the naira.', sig: 2,
  },
  {
    group: 'economy', id: 'fx_allocation', name: 'Dollars at the official rate, for a friend', pc: 2, naira: 0, cooldown: 3, target: 'tycoon',
    when: all(v('fx.peg', '==', 1), v('fx.premium', '>=', 15)),
    blurb: 'The central bank sells dollars at the official rate to whoever the Villa says. The difference with the street rate is pure profit, and some of it finds its way back.',
    result: 'A letter goes to the central bank. {T} receives an allocation at the official rate and sells it on the street the same afternoon. Something arrives in the drawer.',
    fx: [['tycoon.$T', 14], ['fx.reserves', -1.5], ['purse', 12], ['nation.integrity', -2]],
    exposure: { kind: 'personal', amount: 12, witnesses: ['fin'], trail: 2 },
    news: ['QUESTIONS OVER FOREX ALLOCATIONS TO {T_SHORT} GROUP', 'WHO DEY GET DOLLAR FOR OFFICIAL RATE? {T_SHORT}'],
    archive: 'Had the central bank allocate dollars at the official rate to {T}.', sig: 1,
  },
];
