import type { Cond } from '../engine/types';
import type { Order } from './agenda';

// POWERS OF THE MOMENT
// Orders that exist only because of the situation: the season, the state of the
// country, the electoral calendar, a rising rival, something just done. The
// engine offers a handful at a time, each for a few months. When the moment
// passes, so does the option.

const all = (...c: Cond[]): Cond => ({ all: c });
const v = (path: string, op: '<' | '<=' | '>' | '>=' | '==', n: number): Cond => ({ v: [path, op, n] });
const moment = { group: 'moment', situational: true } as const;

export const SITUATIONAL: Order[] = [
  {
    ...moment, id: 'blame', name: 'Blame the previous administration', pc: 0, naira: 0, cooldown: 5, window: 14,
    when: { turn: [1, 14] },
    blurb: 'A press conference on the state in which you found things. It is true, it works, and it stops working after about a year.',
    result: 'The Minister of Information presents "The Rot We Met", with slides. The country nods. It will nod a little less each time.',
    fx: [['approval', 2], ['bloc.street', 2], ['bloc.press', -2], ['counter.blamed', 1]],
    news: ['FG PUBLISHES "THE ROT WE MET"', 'GOVERNMENT SAY NA THE LAST PEOPLE CAUSE AM'],
    archive: 'Blamed the previous administration.',
  },
  // ---------------------------------------------------------------- the first hundred days
  {
    ...moment, id: 'assets', name: 'Publish your own assets on day one', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [1, 6] }, v('exposure.count', '==', 0)),
    blurb: 'Before anyone asks. It will never be this cheap again, and it binds you for the rest of the term.',
    result: 'The declaration is published in full. Three newspapers print it. The cabinet reads it with visible unease.',
    fx: [['nation.integrity', 4], ['bloc.press', 6], ['approval', 2], ['bloc.villa', -4]],
    flags: { 'assets.published': true },
    news: ['PRESIDENT PUBLISHES ASSET DECLARATION', 'PRESIDENT SHOW US EVERYTHING E GET'],
    archive: 'Published your asset declaration in your first months.', sig: 2,
  },
  {
    ...moment, id: 'convoy', name: 'Cut your own convoy, salary and travel', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: { turn: [1, 8] },
    blurb: 'Symbolic. The savings are trivial. The symbolism is not, and your ministers will have to follow.',
    result: 'The convoy goes from forty vehicles to nine. Ministers are told the same applies to them. Several find this harder than any reform.',
    fx: [['approval', 3], ['bloc.street', 4], ['bloc.villa', -5], ['nation.fiscalSpace', 0.05]],
    news: ['PRESIDENT SLASHES CONVOY, PAY', 'PRESIDENT CONVOY NA NINE MOTOR NOW'],
    archive: 'Cut the presidential convoy, salary and travel budget.',
  },
  {
    ...moment, id: 'merge', name: 'Merge the ministries: 48 down to 24', pc: 14, naira: 0, cooldown: 0, window: 6,
    when: { turn: [1, 10] },
    blurb: 'Only possible while your mandate is fresh. Every ministry abolished is a minister, a permanent secretary and four hundred directors.',
    result: 'Twenty-four ministries are abolished by order. The civil service unions threaten, the party sulks, and the wage bill falls for the first time in a generation.',
    fx: [['nation.capacity', 5], ['bonus.fiscal', 0.025], ['bloc.party', -8], ['bloc.establishment', -5], ['bloc.press', 4]],
    news: ['PRESIDENT HALVES NUMBER OF MINISTRIES', '24 MINISTRIES DON CLOSE. BIG MEN DON LOSE OFFICE'],
    archive: 'Merged forty-eight ministries into twenty-four.', sig: 3,
  },

  // ---------------------------------------------------------------- hardship and prices
  {
    ...moment, id: 'price_control', name: 'Impose price controls on staple foods', pc: 4, naira: 0, cooldown: 30,
    when: v('nation.inflation', '>', 27),
    blurb: 'A legal maximum price for rice, bread and garri. Popular within the hour. Shelves respond within the month.',
    result: 'The task force fans out with clipboards. Prices fall at the stalls that are inspected. At the others, goods simply stop appearing.',
    fx: [['approval', 4], ['bloc.street', 6], ['bloc.establishment', -6]],
    later: [{ after: [3, 5], fx: [['bonus.inflation', 1.5], ['approval', -4], ['nation.jobs', -2]], label: 'Price controls empty the shelves and feed a black market.', note: ['STAPLES VANISH FROM MARKETS UNDER PRICE CONTROLS', 'GARRI NO DEY MARKET. NA BLACK MARKET WE DEY BUY'] }],
    news: ['FG FIXES MAXIMUM PRICES FOR STAPLE FOODS', 'GOVERNMENT DON FIX PRICE OF RICE'],
    archive: 'Imposed price controls on staple foods.', sig: 2,
  },
  {
    ...moment, id: 'grain_release', name: 'Release the grain reserve onto the market', pc: 0, naira: 0, cooldown: 0,
    when: all({ flag: 'grain.reserve' }, v('nation.inflation', '>', 24)),
    blurb: 'You filled the silos in a good year. This is what they were for.',
    result: 'Two million tonnes go to market at cost. Prices of grain fall by a quarter in a fortnight. The silos are empty again, having done their job.',
    fx: [['nation.inflation', -3], ['approval', 3], ['bloc.street', 5]],
    flags: { 'grain.reserve': false },
    news: ['GRAIN RESERVE RELEASE CUTS FOOD PRICES', 'GOVERNMENT OPEN SILO. RICE DON CHEAP'],
    archive: 'Released the grain reserve to bring food prices down.', sig: 2,
  },
  {
    ...moment, id: 'vouchers', name: 'Transport vouchers for workers and students', pc: 0, naira: 0.35, cooldown: 18,
    when: all({ flag: 'policy.subsidy', is: 'removed' }, v('hardship', '>', 55)),
    blurb: 'Targets the people the pump price hurts most, without bringing the subsidy back.',
    result: 'Eight million vouchers go out through employers and schools. Fares are still high. Getting to work is no longer the first thing people mention.',
    fx: [['bloc.street', 7], ['approval', 3], ['pressure.wageGrievance', -14]],
    news: ['FG ISSUES TRANSPORT VOUCHERS TO EIGHT MILLION', 'TRANSPORT VOUCHER DON LAND FOR WORKERS'],
    archive: 'Issued transport vouchers to workers and students.',
  },
  {
    ...moment, id: 'public_works', name: 'Hire a million young people on public works', pc: 0, naira: 0.7, cooldown: 24,
    when: v('nation.jobs', '<', 36),
    blurb: 'Drains, feeder roads, school repairs. Not careers. A wage, for two years, for a million people who have never had one.',
    result: 'Recruitment centres open in every local government. The queues are orderly and go around the block twice.',
    fx: [['nation.jobs', 6], ['bloc.street', 7], ['approval', 3], ['bonus.fiscal', -0.015]],
    news: ['ONE MILLION YOUTHS RECRUITED FOR PUBLIC WORKS', 'ONE MILLION YOUTH DON GET WORK'],
    archive: 'Hired a million young people on public works.', sig: 2,
  },
  {
    ...moment, id: 'xmas', name: 'A thirteenth-month salary for civil servants', pc: 0, naira: 0.25, cooldown: 11, window: 2,
    when: { month: [11, 12] },
    blurb: 'It is December. Everyone remembers who paid and who did not.',
    result: 'The alert arrives on the nineteenth. For one week the civil service is the most contented institution in the country.',
    fx: [['bloc.street', 4], ['bloc.establishment', 3], ['approval', 2], ['pressure.wageGrievance', -8]],
    news: ['FG PAYS 13TH-MONTH SALARY', 'CHRISTMAS BONUS DON ENTER'],
    archive: 'Paid civil servants a thirteenth-month salary.',
  },
  {
    ...moment, id: 'airlift', name: 'Emergency fertiliser before the rains', pc: 0, naira: 0.3, cooldown: 11, window: 3,
    when: all({ month: [3, 4, 5] }, v('agenda.f1', '==', 0)),
    blurb: 'Planting starts in weeks. Fertiliser delivered in August is a photo opportunity; in April it is a harvest.',
    result: 'Trucks reach the farm belt before the first rain. Some of it is diverted. Most of it is spread.',
    fx: [['zone.NW.approval', 3], ['zone.NC.approval', 3]],
    later: [{ after: [6, 8], fx: [['nation.inflation', -2], ['approval', 2]], label: 'The harvest is better where the fertiliser arrived on time.', note: ['HARVEST UP 20% WHERE INPUTS ARRIVED EARLY', 'FOOD DON PLENTY THIS YEAR'] }],
    news: ['FG RUSHES FERTILISER TO FARMERS AHEAD OF RAINS', 'FERTILISER REACH FARM BEFORE RAIN, FOR ONCE'],
    archive: 'Rushed fertiliser to farmers before the planting season.',
  },

  // ---------------------------------------------------------------- money
  {
    ...moment, id: 'bank_tax', name: 'A windfall tax on bank profits', pc: 8, naira: 0, cooldown: 0,
    when: v('nation.debt', '>', 78),
    blurb: 'The banks made record profits lending to the government at 20%. Take some of it back. They will remember at the next bond auction.',
    result: 'The levy raises ₦900bn in a quarter. Bank chairmen request a meeting. The next auction clears, at a slightly higher rate.',
    fx: [['nation.fiscalSpace', 0.9], ['bloc.establishment', -8], ['bloc.street', 3], ['nation.debt', 1]],
    news: ['FG IMPOSES WINDFALL LEVY ON BANKS', 'BANK DON MAKE TOO MUCH MONEY. GOVERNMENT DON COLLECT'],
    archive: 'Imposed a windfall tax on bank profits.', sig: 2,
  },
  {
    ...moment, id: 'asset_sale', name: 'Sell the state\'s idle assets', pc: 10, naira: 0, cooldown: 0,
    when: v('nation.debt', '>', 82),
    blurb: 'Eleven thousand abandoned federal properties, four hotels, a fleet of aircraft. Each has a caretaker with a godfather.',
    result: 'The first auctions are held in public. Several properties turn out to be occupied by former ministers, who are given ninety days.',
    fx: [['nation.fiscalSpace', 1.4], ['nation.debt', -4], ['bloc.party', -6], ['nation.integrity', 2]],
    news: ['FG AUCTIONS ABANDONED FEDERAL PROPERTIES', 'GOVERNMENT DEY SELL HOUSE WEY BIG MEN OCCUPY'],
    archive: 'Sold the federal government\'s idle assets.', sig: 2,
  },
  {
    ...moment, id: 'tax_cut', name: 'Cut taxes on small businesses', pc: 0, naira: 0, cooldown: 0,
    when: v('nation.fiscalSpace', '>=', 2.5),
    blurb: 'You have the room. Forty million small traders pay eleven different levies to five different agencies.',
    result: 'Businesses under ₦50m turnover are exempted. The informal sector does not formalise overnight. It does stop hiding.',
    fx: [['nation.jobs', 5], ['bonus.fiscal', -0.02], ['bonus.jobs', 0.03], ['bloc.street', 4], ['approval', 2]],
    news: ['FG EXEMPTS SMALL BUSINESSES FROM COMPANY TAX', 'SMALL BUSINESS NO GO PAY TAX AGAIN'],
    archive: 'Exempted small businesses from company tax.', sig: 2,
  },
  {
    ...moment, id: 'capex_surge', name: 'A capital spending surge', pc: 0, naira: 1.5, cooldown: 30,
    when: v('nation.fiscalSpace', '>=', 3),
    blurb: 'Release every stalled capital vote at once while you can pay for it. Contractors will actually be on site.',
    result: 'Capital releases hit 90% for the first time anyone at the Budget Office can recall. Cranes appear.',
    fx: [['nation.jobs', 5], ['nation.power', 3], ['approval', 2], ['bloc.party', 4]],
    later: [{ after: [8, 12], fx: [['nation.jobs', 4], ['nation.power', 3], ['nation.security', 2]], label: 'Projects funded in the capital surge are completed.' }],
    news: ['FG RELEASES 90% OF CAPITAL BUDGET', 'CONTRACTORS DON RETURN TO SITE'],
    archive: 'Released almost the entire capital budget at once.', sig: 2,
  },

  // ---------------------------------------------------------------- emergencies
  {
    ...moment, id: 'power_emergency', name: 'Declare an emergency in the power sector', pc: 10, naira: 0.6, cooldown: 0,
    when: all(v('nation.power', '<', 30), v('agenda.p2', '==', 0)),
    blurb: 'Suspend procurement rules, import mobile turbines, put an engineer in charge with a deadline. Fast, expensive, and it bypasses everyone.',
    result: 'Forty mobile turbines arrive in ninety days. Supply improves where they are parked. The procurement was not, strictly, lawful.',
    fx: [['nation.power', 9], ['approval', 3], ['nation.integrity', -2], ['bloc.establishment', 3]],
    news: ['PRESIDENT DECLARES POWER EMERGENCY', 'EMERGENCY! PRESIDENT DON CARRY TURBINE COME'],
    archive: 'Declared an emergency in the power sector.', sig: 3,
  },
  {
    ...moment, id: 'emergency_rule', name: 'Declare a state of emergency in three states', pc: 12, naira: 0.3, cooldown: 0,
    when: all(v('nation.security', '<', 33), v('senate', '>=', 48)),
    blurb: 'Federal control of security in the worst-hit states. Needs the Senate. The governors lose their security votes and say so.',
    result: 'The Senate approves by four votes. Troops move in under a single command. The three governors hold a joint press conference.',
    fx: [['nation.security', 8], ['zone.NW.security', 4], ['bloc.party', -6], ['nation.integrity', -1]],
    later: [{ after: [5, 7], fx: [['nation.security', 4], ['approval', 2]], label: 'Emergency rule restores the roads in three states.' }],
    news: ['STATE OF EMERGENCY DECLARED IN THREE STATES', 'EMERGENCY RULE: SOLDIERS DON TAKE OVER THREE STATES'],
    archive: 'Declared a state of emergency in three states.', sig: 3,
  },
  {
    ...moment, id: 'borders', name: 'Close the land borders', pc: 4, naira: 0, cooldown: 0,
    when: v('nation.security', '<', 38),
    blurb: 'Stops the guns and the smuggled rice. Also stops the trade that a third of the border states live on.',
    result: 'The borders close at midnight. Arms seizures fall. So do the neighbours\' economies, and they say so loudly.',
    fx: [['nation.security', 4], ['bonus.inflation', 1.5], ['nation.jobs', -3], ['zone.NW.approval', -3], ['zone.SW.approval', -3]],
    flags: { 'borders.closed': true },
    news: ['NIGERIA CLOSES LAND BORDERS', 'BORDER DON CLOSE. RICE GO COST'],
    archive: 'Closed the land borders.', sig: 2,
  },
  {
    ...moment, id: 'borders_open', name: 'Reopen the land borders', pc: 0, naira: 0, cooldown: 0,
    when: { flag: 'borders.closed' },
    blurb: 'It did what it could. It is now mostly costing you.',
    result: 'The borders reopen. Trade resumes within the hour, including the kinds you closed them to stop.',
    fx: [['bonus.inflation', -1.5], ['nation.jobs', 3], ['nation.security', -2], ['zone.NW.approval', 3], ['zone.SW.approval', 3]],
    flags: { 'borders.closed': false },
    news: ['LAND BORDERS REOPEN', 'BORDER DON OPEN. MARKET DON BOUNCE'],
    archive: 'Reopened the land borders.',
  },
  {
    ...moment, id: 'checkpoints', name: 'Take the checkpoints off the highways', pc: 6, naira: 0, cooldown: 0,
    when: v('nation.security', '>', 48),
    blurb: 'Security is good enough now. There are 300 checkpoints between Lagos and Kano, and every one of them charges.',
    result: 'The checkpoints come down. A lorry of tomatoes reaches Lagos from Kano in fourteen hours instead of four days.',
    fx: [['nation.jobs', 4], ['bonus.inflation', -1], ['approval', 3], ['bloc.establishment', -4], ['nation.integrity', 2]],
    news: ['300 HIGHWAY CHECKPOINTS DISMANTLED', 'NO MORE "WETIN YOU CARRY" FOR ROAD'],
    archive: 'Dismantled the highway checkpoints.', sig: 2,
  },
  {
    ...moment, id: 'relocate', name: 'Move the river communities to higher ground', pc: 6, naira: 0.5, cooldown: 0,
    when: all(v('count.flood', '>=', 1), { not: { flag: 'flood.defences' } }),
    blurb: 'Cheaper than the dams. People have lived on those banks for four hundred years and will not thank you.',
    result: 'Sixty thousand households are offered land and a grant. Two thirds accept. The rest say they will see you at the next flood.',
    fx: [['zone.NC.approval', -3], ['nation.capacity', 1]],
    flags: { 'flood.defences': true },
    news: ['FG RESETTLES 40,000 FLOOD-PLAIN HOUSEHOLDS', 'GOVERNMENT SAY MAKE DEM COMMOT FROM RIVERSIDE'],
    archive: 'Relocated river communities instead of building flood defences.', sig: 2,
  },

  // ---------------------------------------------------------------- integrity
  {
    ...moment, id: 'fearless', name: 'Appoint a fearless anti-corruption chief', pc: 10, naira: 0, cooldown: 0,
    when: all(v('pressure.scandalHeat', '>', 40), v('exposure.total', '<', 10)),
    blurb: 'Someone who cannot be called. She will go after your friends first, to prove a point.',
    result: 'She is sworn in on Monday. By Friday two of your own party\'s governors have been invited for questioning.',
    fx: [['nation.integrity', 6], ['bonus.integrity', 0.05], ['bloc.party', -8], ['bloc.press', 5], ['pressure.scandalHeat', -20]],
    flags: { 'efcc.fearless': true },
    news: ['NEW ANTI-GRAFT CHIEF SUMMONS TWO RULING-PARTY GOVERNORS', 'NEW ANTI-GRAFT OGA NO DEY LOOK FACE'],
    archive: 'Appointed an independent-minded anti-corruption chief.', sig: 3,
  },
  {
    ...moment, id: 'tame', name: 'Put a reliable man in charge of the anti-corruption agency', pc: 6, naira: 0, cooldown: 0,
    when: all(v('pressure.scandalHeat', '>', 45), v('exposure.count', '>=', 2)),
    blurb: 'The files on your desk drawer are a matter of time. A friendly chairman changes the time.',
    result: 'The new chairman announces a "strategic review of all pending investigations". Pending is the important word.',
    fx: [['pressure.scandalHeat', -30], ['nation.integrity', -6], ['bloc.press', -6], ['bloc.party', 5]],
    exposure: { kind: 'tolerated', amount: 0, witnesses: ['chairman'], trail: 1 },
    news: ['NEW ANTI-GRAFT CHAIRMAN ORDERS REVIEW OF ALL CASES', 'ALL THE CASE FILE DON GO "REVIEW"'],
    archive: 'Installed a compliant anti-corruption chairman.', sig: 3,
  },
  {
    ...moment, id: 'inquiry', name: 'A public inquiry into what went wrong', pc: 6, naira: 0, cooldown: 0,
    when: { any: [v('venture.steel', '==', -1), v('venture.rail', '==', -1), v('venture.crypto', '==', -1), v('venture.charter', '==', -1)] },
    blurb: 'Your big bet failed. Say so, in public, with the documents. It costs pride and buys back some trust.',
    result: 'The inquiry sits in public for six weeks. It finds what everyone knew. It is the first time anyone has said it on oath.',
    fx: [['nation.integrity', 4], ['bloc.press', 6], ['approval', 2], ['bloc.villa', -3], ['nation.capacity', 2]],
    news: ['PRESIDENT ORDERS PUBLIC INQUIRY INTO FAILED PROJECT', 'PRESIDENT GREE SAY THE THING FAIL'],
    archive: 'Ordered a public inquiry into your own failed project.', sig: 2,
  },

  // ---------------------------------------------------------------- the street and the press
  {
    ...moment, id: 'dialogue', name: 'A national dialogue with the young', pc: 4, naira: 0, cooldown: 0,
    when: v('bloc.street', '<', 35),
    blurb: 'Not a summit. Town halls, unscripted, in six cities, with you in the chair and no screening of questions.',
    result: 'The first one lasts four hours. You are shouted at for three. In the fourth, somebody says thank you for coming, and means it.',
    fx: [['bloc.street', 10], ['approval', 2], ['bloc.press', 4], ['pressure.wageGrievance', -8]],
    news: ['PRESIDENT FACES ANGRY TOWN HALL FOR FOUR HOURS', 'PRESIDENT SIDDON MAKE YOUTH YAB AM FOR FOUR HOURS'],
    archive: 'Held unscripted town halls with young people in six cities.', sig: 2,
  },
  {
    ...moment, id: 'ban_protest', name: 'Ban public processions', pc: 8, naira: 0, cooldown: 0,
    when: v('bloc.street', '<', 30),
    blurb: 'The police have drafted the order. It will work for a while. It is the kind of thing a legacy does not recover from.',
    result: 'The order is gazetted. The streets are quiet. Everyone who was on them is now somewhere you cannot see.',
    fx: [['bloc.street', -6], ['bloc.establishment', 5], ['bloc.press', -10], ['nation.integrity', -4], ['pressure.wageGrievance', 15]],
    flags: { 'protest.banned': true },
    news: ['FG BANS PUBLIC PROCESSIONS NATIONWIDE', 'DEM SAY WE NO FIT PROTEST AGAIN'],
    archive: 'Banned public processions.', sig: 3,
  },
  {
    ...moment, id: 'station', name: 'Suspend the licence of a hostile broadcaster', pc: 6, naira: 0, cooldown: 0,
    when: v('bloc.press', '<', 32),
    blurb: 'The regulator can find a breach in any broadcast if asked. The other stations will take the hint.',
    result: 'The station goes off air at 6pm. It is streaming online by 6:20, to five times the audience.',
    fx: [['bloc.press', -8], ['nation.integrity', -4], ['bloc.street', -4], ['approval', -2]],
    flags: { 'press.gag': true },
    news: ['REGULATOR SUSPENDS TV STATION\'S LICENCE', 'DEM SHUT DOWN TV STATION. E DON GO ONLINE'],
    archive: 'Had a hostile broadcaster taken off air.', sig: 3,
  },

  // ---------------------------------------------------------------- the party and the rivals
  {
    ...moment, id: 'convention', name: 'Call an emergency party convention', pc: 8, naira: 0, cooldown: 30,
    when: v('bloc.party', '<', 38),
    blurb: 'Put the leadership to a vote before they put you to one. You might lose control of your own party in public.',
    result: 'Three thousand delegates fill Eagle Square. You speak for an hour. The chairman survives; his faction does not get the secretariat.',
    fx: [['bloc.party', 12], ['pc', 4]],
    news: ['RULING PARTY HOLDS EMERGENCY CONVENTION', 'PARTY PEOPLE GATHER. PRESIDENT HOLD GROUND'],
    archive: 'Called an emergency party convention.', sig: 2,
  },
  {
    ...moment, id: 'coopt_fire', name: 'Offer the firebrand a ministry', pc: 8, naira: 0, cooldown: 0,
    when: v('rival.fire', '>', 52),
    blurb: 'He has two million followers and no office. Inside the government he is one voice in cabinet. He may refuse, loudly.',
    result: 'He accepts Youth and Digital Economy. Half his followers call it betrayal. The other half start following the ministry\'s account.',
    fx: [['rival.fire', -22], ['bloc.street', 5], ['bloc.party', -5], ['nation.jobs', 2]],
    news: ['OPPOSITION FIREBRAND JOINS CABINET', 'ENOUGH-IS-ENOUGH DON ENTER GOVERNMENT. E SHOCK US'],
    archive: 'Brought the opposition firebrand into the cabinet.', sig: 3,
  },
  {
    ...moment, id: 'woo_strong', name: 'Bring the defector home', pc: 6, naira: 0, cooldown: 0,
    when: v('rival.strong', '>', 52),
    blurb: 'He left with his delegates. He will come back for the Senate presidency or a clear run at the succession.',
    result: 'He returns "to his political family" at a rally. The price was a promise about the succession that you will have to keep or break.',
    fx: [['rival.strong', -25], ['bloc.party', 10], ['nation.integrity', -2]],
    flags: { 'promise.second_term': true },
    news: ['SENATOR DECAMP RETURNS TO RULING PARTY', 'DECAMP DON DECAMP BACK'],
    archive: 'Brought the defecting senator back with a promise about the succession.', sig: 2,
  },
  {
    ...moment, id: 'steal_alt', name: 'Adopt the opposition\'s best idea', pc: 4, naira: 0.3, cooldown: 0,
    when: v('rival.alt', '>', 52),
    blurb: 'His manifesto has one genuinely good proposal: a single window for every business permit. Take it. Credit him or do not.',
    result: 'The single window opens. He complains that it was his idea, which makes him sound like a man complaining that something good happened.',
    fx: [['rival.alt', -18], ['nation.jobs', 4], ['nation.capacity', 2], ['bloc.establishment', 4]],
    news: ['FG LAUNCHES SINGLE WINDOW FOR BUSINESS PERMITS', 'PRESIDENT DON COPY OPPOSITION HOMEWORK'],
    archive: 'Adopted the opposition\'s best policy as your own.', sig: 2,
  },
  {
    ...moment, id: 'retreat', name: 'Take the governors on a retreat', pc: 4, naira: 0.05, cooldown: 20,
    when: all(v('person.gov_sw', '<', 48), v('person.gov_ss', '<', 48)),
    blurb: 'Three days, no aides, no phones. Half of governing here is being in the same room.',
    result: 'By the second evening they are complaining about each other instead of about you, which is the purpose of a retreat.',
    fx: [['bloc.party', 7], ['person.gov_sw', 10], ['person.gov_ss', 10], ['person.gov_nw', 8], ['person.gov_nc', 8], ['person.gov_ne', 8], ['person.gov_se', 8]],
    news: ['PRESIDENT, GOVERNORS HOLD THREE-DAY RETREAT', 'PRESIDENT AND GOVERNORS GO HIDE FOR THREE DAYS'],
    archive: 'Took the governors on a three-day retreat.',
  },

  // ---------------------------------------------------------------- popularity, spent or lost
  {
    ...moment, id: 'cash_in', name: 'Spend your popularity on the party', pc: 0, naira: 0, cooldown: 30,
    when: v('approval', '>', 62),
    blurb: 'You are popular enough that nobody in the party dares refuse you. That does not last. Use it.',
    result: 'You call in every senator and governor in a week and tell each what you expect. Nobody argues. Several take notes.',
    fx: [['pc', 18], ['bloc.party', 8], ['approval', -2]],
    news: ['PRESIDENT SUMMONS PARTY LEADERS IN SHOW OF STRENGTH', 'PRESIDENT DEY FLEX. NOBODY FIT TALK'],
    archive: 'Used high approval to bring the party into line.',
  },
  {
    ...moment, id: 'apology', name: 'A purge and an apology', pc: 6, naira: 0, cooldown: 0,
    when: v('approval', '<', 36),
    blurb: 'Sack the six least popular people around you, say plainly what went wrong, and ask for another hearing. It only works once.',
    result: 'You speak for nine minutes and use the word "wrong" about your own government four times. The six leave by the side gate.',
    fx: [['approval', 6], ['bloc.street', 8], ['bloc.press', 6], ['bloc.villa', -8], ['bloc.party', -4]],
    news: ['"WE GOT IT WRONG" — PRESIDENT SACKS SIX, RESETS', 'PRESIDENT SAY SORRY, SACK SIX PEOPLE'],
    archive: 'Purged your inner circle and apologised to the country.', sig: 3,
  },

  // ---------------------------------------------------------------- abroad
  {
    ...moment, id: 'state_visit', name: 'A state visit to bring back investment', pc: 0, naira: 0.05, cooldown: 14,
    when: v('bloc.establishment', '>=', 45),
    blurb: 'Ten days, three capitals, a plane full of businessmen. Works when the numbers at home are credible.',
    result: 'You return with $4bn in signed commitments. About half of signed commitments ever arrive. That is still two.',
    fx: [['bloc.establishment', 4]],
    later: [{ after: [6, 10], fx: [['nation.jobs', 5], ['nation.fiscalSpace', 0.3]], label: 'Investment pledged on the state visit begins to arrive.', note: ['FIRST FACTORIES OPEN FROM STATE VISIT PLEDGES', 'THE INVESTMENT WEY PRESIDENT GO FIND DON LAND'] }],
    news: ['PRESIDENT RETURNS WITH $4BN IN INVESTMENT PLEDGES', 'PRESIDENT DON RETURN FROM ABROAD WITH PROMISE'],
    archive: 'Made a state visit to secure foreign investment.',
  },
  {
    ...moment, id: 'cbn', name: 'Replace the central bank governor', pc: 14, naira: 0, cooldown: 0,
    when: all(v('senate', '>=', 54), v('nation.inflation', '>', 24), { turn: [8] }),
    blurb: 'She was appointed by your predecessor and answers to nobody. Removing her needs two thirds of the Senate, which you currently have.',
    result: 'The Senate votes 76 to 31. Your nominee takes office. The bank is now yours, including everything it does next.',
    fx: [['bonus.inflation', -2], ['bloc.establishment', -6], ['nation.integrity', -2]],
    news: ['SENATE REMOVES CENTRAL BANK GOVERNOR', 'CBN GOVERNOR DON GO. PRESIDENT PERSON DON ENTER'],
    archive: 'Removed the central bank governor with a Senate vote.', sig: 3,
  },

  // ---------------------------------------------------------------- the electoral calendar
  {
    ...moment, id: 'wage_decree', name: 'An election-year pay rise for civil servants', pc: 0, naira: 0.5, cooldown: 0, window: 6,
    when: all({ term: 1 }, { termTurn: [34, 44] }),
    blurb: 'The election is months away. Two million federal workers and their families vote.',
    result: 'A 30% rise takes effect from January. The opposition calls it a bribe, and promises to keep it.',
    fx: [['approval', 3], ['bloc.street', 6], ['pressure.wageGrievance', -18], ['bonus.fiscal', -0.03], ['bloc.establishment', -3]],
    news: ['FG APPROVES 30% PAY RISE FOR CIVIL SERVANTS', 'ELECTION DON NEAR: SALARY DON INCREASE'],
    archive: 'Raised civil service pay months before the election.', sig: 2,
  },
  {
    ...moment, id: 'commission_all', name: 'Commission everything that has a ribbon', pc: 0, naira: 0.1, cooldown: 0, window: 6,
    when: all({ term: 1 }, { termTurn: [38, 44] }),
    blurb: 'Finished, nearly finished, and one or two that are mostly a signboard. A tour of all six zones.',
    result: 'You cut forty-one ribbons in three weeks. Thirty are real. The press visits the other eleven the following Monday.',
    fx: [['approval', 3], ['bloc.party', 4], ['bloc.press', -4], ['nation.integrity', -1]],
    news: ['PRESIDENT COMMISSIONS 41 PROJECTS IN THREE WEEKS', 'PRESIDENT COMMISSION 41 PROJECT. ELEVEN NA SIGNBOARD'],
    archive: 'Commissioned forty-one projects in the run-up to the election.',
  },
  {
    ...moment, id: 'debate', name: 'Challenge your rival to a televised debate', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: all({ term: 1 }, { termTurn: [40, 44] }),
    blurb: 'Incumbents usually refuse. If your record is good, this is where it counts. If it is not, this is where it is read back to you.',
    result: 'Ninety minutes, live, no notes.',
    fx: [['bloc.press', 5]],
    later: [
      { after: 1, when: v('hardship', '<', 48), fx: [['approval', 4], ['bloc.street', 3]], label: 'You won the debate on the record.', note: ['PRESIDENT WINS DEBATE ON THE RECORD', 'PRESIDENT FINISH OPPOSITION FOR DEBATE'] },
      { after: 1, when: v('hardship', '>=', 48), fx: [['approval', -4], ['bloc.street', -3]], label: 'The debate turned on prices, and you lost it.', note: ['PRESIDENT STUMBLES ON COST OF LIVING IN DEBATE', 'DEM ASK PRESIDENT PRICE OF GARRI. E NO SABI'] },
    ],
    news: ['PRESIDENT TO DEBATE CHALLENGER LIVE', 'DEBATE! PRESIDENT VS OPPOSITION, LIVE'],
    archive: 'Debated your challenger live on television.', sig: 2,
  },

  // ---------------------------------------------------------------- the second term
  {
    ...moment, id: 'pardon', name: 'A presidential pardon for political prisoners and debtors', pc: 6, naira: 0, cooldown: 0,
    when: { term: 2 },
    blurb: 'Journalists, protesters, and forty thousand people in jail for fines under ₦50,000. You no longer need anyone\'s permission.',
    result: 'The prisons release 41,000 people in a week. The Controller of Prisons notes that the food budget is now adequate for the first time.',
    fx: [['bloc.street', 6], ['bloc.press', 6], ['nation.integrity', 3], ['bloc.establishment', -3], ['approval', 2]],
    news: ['PRESIDENT PARDONS 41,000', '41,000 PEOPLE DON COMMOT FROM PRISON'],
    archive: 'Pardoned 41,000 prisoners, including journalists and protesters.', sig: 3,
  },
  {
    ...moment, id: 'unpopular', name: 'Do the unpopular thing nobody facing an election would', pc: 12, naira: 0, cooldown: 0,
    when: all({ term: 2 }, { termTurn: [4, 30] }),
    blurb: 'Cost-reflective pricing across the board: water, tolls, tuition, rail. You will never be on a ballot again.',
    result: 'It is announced on a Friday. By Monday you are the least popular second-term President on record, and the agencies are solvent.',
    fx: [['bonus.fiscal', 0.05], ['approval', -6], ['bloc.street', -8], ['bloc.establishment', 8], ['nation.capacity', 3]],
    news: ['FG ENDS BELOW-COST PRICING ACROSS PUBLIC SERVICES', 'EVERYTHING DON COST. PRESIDENT NO SEND'],
    archive: 'Ended below-cost pricing across public services in your second term.', sig: 3,
  },
  {
    ...moment, id: 'monument', name: 'Build something with your name on it', pc: 0, naira: 0.8, cooldown: 0,
    when: all({ term: 2 }, { termTurn: [20, 44] }),
    blurb: 'A presidential library, a national theatre, a bridge. Every second-term President does it. Few of them are finished.',
    result: 'The foundation stone is laid. It bears your name in letters you approved personally.',
    fx: [['bloc.villa', 4], ['approval', -1], ['bloc.press', -3]],
    later: [{ after: [14, 18], when: v('nation.capacity', '>=', 50), fx: [['approval', 3], ['nation.jobs', 2]], label: 'Your monument is completed and opened.', note: ['NATIONAL LIBRARY OPENS', 'THE BIG LIBRARY DON OPEN. E FINE'] }],
    news: ['PRESIDENT LAYS FOUNDATION OF NATIONAL LIBRARY', 'PRESIDENT DEY BUILD MONUMENT WEY CARRY PRESIDENT NAME'],
    archive: 'Began a monument bearing your name.', sig: 2,
  },
// ---------------------------------------------------------------- initiatives of your own
  // Not responses to anything. Things a President might simply decide to do,
  // each once, each with someone who loses.
  {
    ...moment, id: 'jets', name: 'Sell half the presidential air fleet', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: { turn: [3] },
    blurb: 'Ten aircraft, for one President. Five would be generous.',
    result: 'Five aircraft are auctioned. One is bought by a governor, which becomes its own story.',
    fx: [['approval', 3], ['nation.fiscalSpace', 0.1], ['bloc.villa', -4], ['bloc.press', 3]],
    news: ['PRESIDENCY SELLS FIVE AIRCRAFT', 'PRESIDENT DON SELL FIVE JET'],
    archive: 'Sold half the presidential air fleet.',
  },
  {
    ...moment, id: 'vip_police', name: 'Take the police off VIP escort duty', pc: 6, naira: 0, cooldown: 0, window: 5,
    when: { turn: [5] },
    blurb: 'A third of the police force guards politicians and their wives. Put them back on the street. Every one of those politicians has your number.',
    result: '110,000 officers return to stations. Crime falls. Senators discover what traffic is like.',
    fx: [['nation.security', 6], ['approval', 2], ['bloc.party', -6], ['bloc.establishment', -5], ['bonus.security', 0.03]],
    news: ['110,000 POLICE WITHDRAWN FROM VIP DUTY', 'BIG MAN NO GET POLICE ESCORT AGAIN'],
    archive: 'Withdrew the police from VIP escort duty.', sig: 2,
  },
  {
    ...moment, id: 'medical', name: 'Ban officials from medical treatment abroad', pc: 5, naira: 0, cooldown: 0, window: 5,
    when: { turn: [4] },
    blurb: 'Including you. If the people who run the hospitals have to use them, the hospitals change.',
    result: 'The ban takes effect. Within the month three teaching hospitals have new equipment and a waiting list of ministers.',
    fx: [['approval', 3], ['bloc.street', 4], ['bloc.villa', -6], ['bloc.party', -3]],
    later: [{ after: [8, 12], fx: [['nation.capacity', 2], ['approval', 1.5]], label: 'Hospitals improve once officials have to use them.' }],
    news: ['OFFICIALS BARRED FROM FOREIGN MEDICAL TRIPS', 'NO MORE LONDON HOSPITAL FOR BIG MEN'],
    archive: 'Banned officials, yourself included, from medical treatment abroad.', sig: 2,
  },
  {
    ...moment, id: 'open_data', name: 'Publish every statistic the government holds', pc: 4, naira: 0, cooldown: 0, window: 5,
    when: { turn: [6] },
    blurb: 'Budget releases, oil volumes, school enrolment, all of it, monthly. Some of the numbers are bad and will be news.',
    result: 'The portal goes live. Journalists find eleven stories in the first week. Nine are unflattering. All are true.',
    fx: [['nation.capacity', 2], ['nation.integrity', 3], ['bloc.press', 5], ['approval', -1]],
    news: ['FG OPENS ALL OFFICIAL STATISTICS TO PUBLIC', 'GOVERNMENT DON PUT ALL THE NUMBER FOR INTERNET'],
    archive: 'Published all government statistics monthly.',
  },
  {
    ...moment, id: 'exam_fees', name: 'Abolish examination fees', pc: 0, naira: 0.15, cooldown: 0, window: 5,
    when: { turn: [7] },
    blurb: 'Two million children a year do not sit their final exams because of a ₦27,000 fee.',
    result: 'Fees are abolished from this session. Registrations rise by a third.',
    fx: [['bloc.street', 5], ['approval', 2], ['bonus.fiscal', -0.008]],
    news: ['FG SCRAPS SECONDARY EXAM FEES', 'EXAM DON FREE'],
    archive: 'Abolished secondary school examination fees.',
  },
  {
    ...moment, id: 'lg_autonomy', name: 'Pay local governments directly', pc: 12, naira: 0, cooldown: 0, window: 5,
    when: { turn: [8] },
    blurb: 'Their allocation goes to the governors first and mostly stays there. Send it straight to the 774 councils. The governors will treat this as a declaration of war.',
    result: 'The first direct payment is made. Council chairmen who had never controlled a budget now do. Thirty-six governors compare notes.',
    fx: [['bloc.street', 5], ['nation.capacity', 3], ['nation.integrity', 2], ['bloc.party', -8],
      ['person.gov_nw', -10], ['person.gov_ne', -8], ['person.gov_nc', -10], ['person.gov_sw', -10], ['person.gov_se', -8], ['person.gov_ss', -10]],
    news: ['LOCAL GOVERNMENTS TO RECEIVE ALLOCATIONS DIRECTLY', 'LOCAL GOVERNMENT MONEY NO GO PASS GOVERNOR HAND AGAIN'],
    archive: 'Paid local government allocations directly, bypassing the governors.', sig: 3,
  },
  {
    ...moment, id: 'ports24', name: 'Order the ports to work around the clock', pc: 4, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [9] }, v('agenda.i1', '==', 0)),
    blurb: 'The ports close at five. The ships do not. A directive, not a reform; it helps until someone finds a way round it.',
    result: 'Night shifts begin. Clearance times fall by a third. The agencies that lived off the delay are inventive, and will adapt.',
    fx: [['nation.jobs', 3], ['bonus.inflation', -0.5], ['bloc.establishment', -3]],
    news: ['PORTS BEGIN 24-HOUR OPERATIONS', 'PORT DEY WORK FOR NIGHT NOW'],
    archive: 'Ordered the ports to operate around the clock.',
  },
  {
    ...moment, id: 'census', name: 'Hold the census, at last', pc: 6, naira: 0.4, cooldown: 0, window: 6,
    when: { turn: [10] },
    blurb: 'Nobody knows how many Nigerians there are. Every state believes it has more than it is credited with, and revenue follows the number.',
    result: 'The count is held, digitally, in eleven days. The result pleases nobody, which the statisticians take as evidence of accuracy.',
    fx: [['nation.capacity', 5], ['bloc.establishment', 3]],
    later: [{ after: [3, 5], fx: [['bloc.party', -6], ['zone.NW.approval', -2], ['zone.SW.approval', -2], ['zone.SE.approval', -2]], label: 'The census figures are published and disputed by every state.', note: ['STATES REJECT CENSUS FIGURES', 'EVERY STATE SAY THEIR NUMBER NO CORRECT'] }],
    news: ['NIGERIA HOLDS FIRST CENSUS IN TWO DECADES', 'DEM DON COUNT US AT LAST'],
    archive: 'Held the first census in two decades.', sig: 2,
  },
  {
    ...moment, id: 'paycut', name: 'Halve the pay of political office holders', pc: 10, naira: 0, cooldown: 0, window: 5,
    when: { turn: [12] },
    blurb: 'Legislators here are among the best paid in the world. They also vote on your bills.',
    result: 'The order covers the executive at once. The Assembly is "invited to follow". It forms a committee to consider the invitation.',
    fx: [['approval', 4], ['bloc.street', 5], ['bloc.party', -8], ['person.sen_pres', -10], ['person.sen_approp', -10], ['person.sen_rebel', 8], ['nation.fiscalSpace', 0.1]],
    news: ['PRESIDENT HALVES PAY OF POLITICAL APPOINTEES', 'PRESIDENT CUT POLITICIAN SALARY. SENATORS DEY VEX'],
    archive: 'Halved the pay of political office holders.', sig: 2,
  },
  {
    ...moment, id: 'currency', name: 'Redesign the currency to flush out hoarded cash', pc: 6, naira: 0.1, cooldown: 0, window: 5,
    when: all({ turn: [12] }, v('nation.integrity', '<', 45)),
    blurb: 'Old notes expire in ninety days. Billions held in vaults and soakaways must surface or die. So must every market trader\'s savings.',
    result: 'The old notes expire before the new ones arrive. People sleep at cash machines. A man in Kano pays a transfer fee to buy bread. The hoarders changed theirs in bulk, quietly, in the first week.',
    fx: [['approval', -5], ['bloc.street', -8], ['nation.jobs', -3], ['nation.integrity', 2], ['pressure.scandalHeat', -8], ['bloc.party', -4]],
    news: ['CASH SHORTAGE AS OLD NOTES EXPIRE', 'NO CASH! PEOPLE DEY SLEEP FOR ATM'],
    archive: 'Redesigned the currency and caused a nationwide cash shortage.', sig: 3,
  },
  {
    ...moment, id: 'directors', name: 'Retire every director past eight years in post', pc: 8, naira: 0, cooldown: 0, window: 5,
    when: { turn: [14] },
    blurb: 'The rule exists and has never been enforced. Eleven hundred directors, each of whom knows where the files are.',
    result: 'They go in a single circular. A generation of deputies, who have been doing the work, finally get the offices.',
    fx: [['nation.capacity', 5], ['bloc.establishment', -7], ['bloc.villa', -3], ['bonus.capacity', 0.03]],
    news: ['1,100 DIRECTORS RETIRED IN CIVIL SERVICE SHAKE-UP', 'OLD OGAS DON GO. YOUNG ONES DON ENTER'],
    archive: 'Enforced the tenure rule and retired 1,100 directors.', sig: 2,
  },
  {
    ...moment, id: 'trade_pact', name: 'Open the continental free-trade corridor', pc: 6, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [16] }, { not: { flag: 'borders.closed' } }),
    blurb: 'Tariff-free trade with fifty countries. Your exporters gain a continent. Your weaker manufacturers gain competitors.',
    result: 'The first tariff-free consignments cross. Cement and noodles go out. Textiles come in.',
    fx: [['nation.jobs', 4], ['bonus.jobs', 0.03], ['bonus.inflation', -0.5], ['bloc.establishment', -4]],
    news: ['NIGERIA BEGINS TARIFF-FREE CONTINENTAL TRADE', 'WE DON START TO SELL TO THE WHOLE AFRICA'],
    archive: 'Opened tariff-free trade under the continental pact.', sig: 2,
  },
  {
    ...moment, id: 'homecoming', name: 'A year of return for the diaspora', pc: 0, naira: 0.1, cooldown: 0, window: 5,
    when: { turn: [18] },
    blurb: 'Visa on arrival, a property guarantee, a festival. Seventeen million people with foreign salaries and aging parents.',
    result: 'December flights are full from October. The money spent in a month exceeds a quarter of oil revenue.',
    fx: [['nation.fiscalSpace', 0.5], ['nation.jobs', 2], ['bloc.street', 2], ['approval', 1]],
    news: ['RECORD DIASPORA ARRIVALS FOR "YEAR OF RETURN"', 'ABROAD PEOPLE FULL EVERYWHERE THIS DECEMBER'],
    archive: 'Declared a year of return for the diaspora.',
  },
  {
    ...moment, id: 'timetable', name: 'Publish an honest power-rationing timetable', pc: 0, naira: 0, cooldown: 0, window: 5,
    when: all({ turn: [5] }, v('nation.power', '<', 44)),
    blurb: 'There is not enough to go round. Say so, and tell people when theirs is coming, so they can plan.',
    result: 'The timetable is published by district. It is kept to, mostly. People iron on Tuesdays.',
    fx: [['approval', 2], ['bloc.press', 3], ['bloc.street', 2], ['nation.jobs', 1]],
    news: ['POWER RATIONING TIMETABLE PUBLISHED BY DISTRICT', 'NOW WE KNOW WHEN LIGHT GO COME'],
    archive: 'Published an honest power-rationing timetable.',
  },
  {
    ...moment, id: 'summit', name: 'Host an investment summit', pc: 0, naira: 0.1, cooldown: 26, window: 4,
    when: all({ turn: [9] }, v('bloc.establishment', '>=', 40)),
    blurb: 'Two thousand delegates, forty heads of industry. It works if there is something real to show them.',
    result: 'The summit runs for three days. The hotels are full. The pledges will be tested against what they find when they visit a ministry.',
    fx: [['bloc.establishment', 3]],
    later: [
      { after: [6, 9], when: v('nation.capacity', '>=', 42), fx: [['nation.jobs', 4], ['nation.fiscalSpace', 0.2]], label: 'Investment pledged at the summit arrives.' },
      { after: [6, 9], when: v('nation.capacity', '<', 42), fx: [['bloc.press', -3]], label: 'Most summit pledges never arrive.', note: ['SUMMIT PLEDGES: 6% HAVE MATERIALISED', 'THE INVESTORS COME, SEE, COMMOT'] },
    ],
    news: ['2,000 DELEGATES ATTEND ABUJA INVESTMENT SUMMIT', 'BIG SUMMIT FOR ABUJA. HOTEL FULL'],
    archive: 'Hosted an investment summit.',
  },
];
