import type { Track } from '../engine/types';

// Four tracks where the items can be taken in any order. Each item does something
// the core tracks cannot: it changes how a system behaves for as long as it stands,
// usually as a standing policy costed every month in the Treasury. Few are free of
// a price, and some are better for the President than for the country.

const SENATE = { needs: { v: ['senate', '>=', 50] as [string, '>=', number] }, needsText: 'You do not have the Senate. Win over your senators first.' };

export const LOOSE_TRACKS: Track[] = [
  {
    id: 'federation', name: 'Restructure the Federation', goal: 'Who holds power, and where', metric: 'nation.capacity', loose: true,
    milestones: [
      {
        id: 'r6', name: 'A census, the first in twenty years', pc: 6, naira: 0.4, months: 8,
        during: [['zone.NW.approval', -0.4], ['zone.SW.approval', -0.4], ['pressure.scandalHeat', 0.5]], duringText: 'Every zone is sure it is being undercounted, and says so nightly.',
        lasting: 'Every programme that pays people costs less and reaches the right ones: the cash transfer is a third cheaper and the tax net finds a million new payers.',
        blurb: 'Nobody knows how many Nigerians there are, so every formula, every seat and every transfer is a guess that someone is stealing from. A count settles the guess. It also settles arguments some people would rather keep.',
        done: [['nation.capacity', 4], ['bonus.fiscal', 0.006], ['nation.integrity', 2], ['bloc.establishment', 3]],
        flags: { census: true },
        news: ['FIRST CENSUS IN TWO DECADES PUTS POPULATION AT 231 MILLION', 'DEM DON COUNT US. NA 231 MILLION. YOUR STATE DEY VEX?'],
        archive: 'Held the first census in twenty years.',
      },
      {
        id: 'r1', name: 'Pay the local governments directly', pc: 10, naira: 0, months: 5,
        lasting: 'Councils pay teachers and clinic staff themselves. Where the state is able to audit them they deliver; where it is not, they steal the money the governors used to.',
        blurb: 'Council money goes to councils, not through the governors\' joint accounts. Primary schools, health posts and local roads stop waiting on a governor\'s mood. Every governor in the country will oppose it, including yours.',
        start: [['bloc.party', -5], ['person.gov_ss', -8], ['person.gov_nw', -8], ['person.gov_sw', -8]],
        done: [['nation.capacity', 3], ['bloc.street', 5], ['nation.integrity', 2], ['person.gov_ne', -6], ['person.gov_nc', -6], ['person.gov_se', -6]],
        news: ['COUNCILS RECEIVE ALLOCATIONS DIRECTLY FOR FIRST TIME', 'LOCAL GOVERNMENT MONEY NO DEY PASS GOVERNOR HAND AGAIN'],
        archive: 'Paid local governments directly, over the governors\' objections.',
      },
      {
        id: 'r7', name: 'The governors\' compact: a bigger share, for their loyalty', pc: 4, naira: 0, months: 3, popular: true, ...SENATE,
        lasting: 'Every governor warms to you a little every month, and a governor who likes you delivers their state on election day. The centre pays for it out of its share, every month.',
        blurb: 'The states\' share of the federation account rises by three points, and in return the governors stop fighting you in the Assembly and the party. It is the oldest bargain in the federation. It buys elections; it does not buy anything that lasts after you.',
        done: [['person.gov_nw', 10], ['person.gov_ne', 10], ['person.gov_nc', 10], ['person.gov_sw', 10], ['person.gov_se', 10], ['person.gov_ss', 10], ['bloc.party', 6]],
        news: ['STATES\' SHARE OF REVENUE RAISED; GOVERNORS PLEDGE SUPPORT', 'GOVERNORS DON COLLECT BIGGER SHARE. DEM DON BECOME PRESIDENT PEOPLE'],
        archive: 'Raised the states\' share of revenue in return for the governors\' loyalty.',
      },
      {
        id: 'r3', name: 'Resource control: producing states keep a quarter', pc: 12, naira: 0, months: 7, ...SENATE,
        during: [['zone.NW.approval', -0.75], ['zone.NE.approval', -0.75]], duringText: 'The north reads it as oil money leaving.',
        lasting: 'Communities paid from the oil guard the pipelines: violence in the creeks keeps falling every month, and output rises with it.',
        blurb: 'Derivation rises from 13% to 25%. It may be the only thing that quiets the creeks for good, and quiet creeks pump more oil. It comes out of the centre\'s share and the North\'s, and the North will say so.',
        start: [['zone.NW.approval', -3], ['zone.NE.approval', -3]],
        done: [['theatre.SS', -12], ['drift.SS', -0.15], ['zone.SS.approval', 10], ['person.gov_ss', 15], ['bonus.fiscal', -0.03], ['zone.NW.approval', -4], ['zone.NE.approval', -4], ['person.gov_nw', -8]],
        news: ['DERIVATION RAISED TO 25%; OIL STATES CELEBRATE', 'NIGER DELTA GO NOW KEEP QUARTER OF THE OIL MONEY'],
        archive: 'Raised derivation to 25% for the oil-producing states.',
      },
      {
        id: 'r4', name: 'Results transmitted from the polling unit, by law', pc: 12, naira: 0.1, months: 6, ...SENATE,
        lasting: 'The party machine counts for 40% less at elections, yours and everyone\'s, and a win must be under 4 points instead of 7 to be petitioned.',
        blurb: 'Every result sheet photographed and published before it leaves the polling unit. It is the reform every opposition demands and every incumbent postpones. You are the incumbent. If your approval is your strength and the machine is theirs, it is also your best weapon.',
        start: [['bloc.party', -6]],
        done: [['nation.integrity', 6], ['bloc.press', 7], ['bloc.street', 4], ['bloc.party', -6], ['bloc.establishment', 3], ['rival.fire', -5]],
        flags: { 'electoral.reform': true },
        news: ['ELECTORAL ACT AMENDED: RESULTS TO BE PUBLISHED AT THE POLLING UNIT', 'NO MORE "SERVER ISSUE". RESULT GO SHOW FOR POLLING UNIT'],
        archive: 'Made polling-unit results public by law, against your own party\'s interest.',
      },
    ],
  },
  {
    id: 'welfare', name: 'Relief for the People', goal: 'Cash, prices and comfort', metric: 'bloc.street', loose: true,
    milestones: [
      {
        id: 'h3', name: 'A monthly transfer to the ten million poorest households', pc: 4, naira: 0.5, months: 7,
        lasting: 'A cushion under the poorest: the harder the times, the more it is worth in calm and goodwill. It costs money every month, less after a census.',
        blurb: 'Paid to a verified identity, published by ward. There is no ribbon to cut. When prices spike or a harvest fails, it is the difference between a hard month and a riot.',
        done: [['bloc.street', 6], ['approval', 3], ['pressure.wageGrievance', -8], ['nation.jobs', 2]],
        news: ['TEN MILLION HOUSEHOLDS NOW RECEIVE MONTHLY TRANSFER', 'ALERT DEY ENTER EVERY MONTH FOR POOR PEOPLE. E REAL'],
        archive: 'Began a monthly cash transfer to the ten million poorest households.',
      },
      {
        id: 'h6', name: 'Gas buses in every city, and conversion kits at cost', pc: 4, naira: 0.6, months: 8,
        lasting: 'Fares are set by gas, not petrol. Worth a little on its own; after the subsidy is gone, it takes most of the sting out of the pump price.',
        blurb: 'Ten thousand buses on compressed gas and a kit for every danfo and keke that wants one. The country sits on more gas than it can sell. If you mean to end the petrol subsidy, this is the thing to have running first.',
        done: [['approval', 2], ['bloc.street', 4], ['nation.jobs', 2], ['tycoon.ty_fuel', -5]],
        news: ['GAS BUSES ROLL OUT IN TWELVE CITIES; FARES FALL', 'GAS MOTOR DON LAND. TRANSPORT DON CHEAP SMALL'],
        archive: 'Put gas buses in every city and sold conversion kits at cost.',
      },
      {
        id: 'h7', name: 'A three-year deal with labour: pay tied to prices, no strikes', pc: 6, naira: 0.2, months: 4,
        lasting: 'Labour anger drains away every month and there are no general strikes. Wages rise with prices, so every point of inflation above 10% is a bill you pay.',
        blurb: 'The unions get a wage that keeps pace with prices; you get three years without a general strike. A President who keeps inflation down gets peace for almost nothing. One who lets it run is paying for the inflation twice.',
        start: [['tycoon.ty_maker', -4]],
        done: [['pressure.wageGrievance', -25], ['bloc.street', 5], ['approval', 2]],
        news: ['FG AND LABOUR SIGN THREE-YEAR WAGE PACT', 'LABOUR DON SIGN. NO STRIKE FOR THREE YEARS. WE GO SEE'],
        archive: 'Signed a three-year wage deal with labour, pay tied to prices.',
      },
      {
        id: 'h5', name: 'A million homes, on mortgages people can get', pc: 6, naira: 1.2, months: 16,
        lasting: 'Building sites hire every month and the banks earn on twenty-year loans, as long as inflation stays under 20%. Above that, mortgages stop and the subsidy keeps costing.',
        blurb: 'Land titles that can be registered in a week, and twenty-year loans at single digits. The biggest employer of young men without degrees is a building site. The banks will need persuading, and then they will want all of it.',
        done: [['nation.jobs', 6], ['approval', 4], ['tycoon.ty_bank', 6], ['bloc.street', 4]],
        news: ['FIRST 200,000 FAMILIES MOVE INTO MORTGAGE HOMES', 'ORDINARY PERSON DON GET HOUSE LOAN. FOR NIGERIA'],
        archive: 'Built a million homes on long mortgages.',
      },
      {
        id: 'h1', name: 'A price control board for staple foods', pc: 2, naira: 0.1, months: 3, popular: true,
        lasting: 'When inflation is high it holds shelf prices down, by up to 5 points. The higher prices are, the more it costs in farmers who stop selling and inspectors who are paid to look away.',
        blurb: 'Rice, garri, bread and cooking oil sold at the government\'s price or not at all. In a price crisis nothing else works as fast. Traders will sell at that price for about a fortnight, and then stop selling.',
        done: [['approval', 5], ['bloc.street', 7], ['nation.jobs', -2], ['tycoon.ty_trade', -12], ['nation.integrity', -2], ['bloc.establishment', -5]],
        news: ['PRICE CONTROL BOARD FIXES COST OF RICE, BREAD, GARRI', 'GOVERNMENT DON FIX PRICE. NOW THE RICE DON DISAPPEAR'],
        archive: 'Set up a price control board for staple foods.',
      },
    ],
  },
  {
    id: 'order', name: 'Order and National Pride', goal: 'Discipline, borders and the flag', metric: 'approval', loose: true,
    milestones: [
      {
        id: 'o6', name: 'Watch the northern border: drones, scanners and one customs system', pc: 6, naira: 0.5, months: 8,
        lasting: 'Fewer guns come in from the Sahel: attacks in the North West and North East ease every month. Duty that used to be paid to officers is paid to the treasury.',
        blurb: 'Fifteen hundred kilometres of border watched from the air, every truck scanned, every declaration in one system that an officer cannot quietly edit. The guns used in the North West come across it. So does a great deal of untaxed rice, and the people who move it will notice.',
        start: [['bloc.establishment', -3]],
        done: [['theatre.NW', -5], ['theatre.NE', -3], ['drift.NW', -0.12], ['drift.NE', -0.06], ['bonus.fiscal', 0.012], ['tycoon.ty_trade', -10], ['nation.integrity', 2]],
        news: ['NEW BORDER SYSTEM GOES LIVE; ARMS SEIZURES TRIPLE', 'BORDER DON GET EYE FOR SKY. SMUGGLER DEY FEEL AM'],
        archive: 'Put the northern border under drones, scanners and a single customs system.',
      },
      {
        id: 'o7', name: 'An amnesty for fighters who hand in their guns', pc: 8, naira: 0.4, months: 4,
        lasting: 'Attacks fall at once. For two years the men who came in must be given something to do: with a youth jobs corps or technical training running, they stay out; without, some go back to the bush every month.',
        blurb: 'Lay down your rifle, give your name, and walk away with a stipend and a trade. It is the fastest way to empty the forests and the most hated policy you could announce. The families of the dead will be on the news. Whether it works depends on what the men find when they come out.',
        start: [['bloc.press', -4], ['bloc.street', -3]],
        done: [['theatre.NW', -10], ['theatre.NE', -8], ['theatre.NC', -4], ['bloc.establishment', 2]],
        news: ['THOUSANDS SURRENDER WEAPONS UNDER AMNESTY', 'BANDITS DEY SUBMIT GUN. DEM GO GET STIPEND. PEOPLE DEY VEX'],
        archive: 'Offered an amnesty to fighters who handed in their guns.',
      },
      {
        id: 'o3', name: 'Ranching law and grazing reserves', pc: 12, naira: 0.6, months: 10, ...SENATE,
        during: [['theatre.NC', 0.5], ['theatre.NW', 0.5]], duringText: 'Herders are moved off routes they have used for generations, and some of them fight.',
        lasting: 'The killing in the farm belt keeps falling, and food grown there reaches market.',
        blurb: 'Open grazing ends; ranches are built and paid for. It goes to the root of the killing in the farm belt. Herders\' leaders and half the northern caucus will call it an attack on a way of life.',
        start: [['zone.NW.approval', -4], ['person.gov_nw', -8]],
        done: [['theatre.NC', -14], ['drift.NC', -0.15], ['zone.NC.approval', 8], ['person.gov_nc', 12], ['bonus.inflation', -1], ['zone.NW.approval', -3], ['nation.jobs', 3]],
        news: ['FARM-BELT ATTACKS FALL AS RANCHES OPEN', 'COW DON GET HIM OWN HOUSE. FARMER FIT SLEEP'],
        archive: 'Ended open grazing and built ranches.',
      },
      {
        id: 'o8', name: 'Bring the loot home: a public register, spent on named projects', pc: 8, naira: 0, months: 6,
        lasting: 'Money is recovered every month, more with an honest government and an anti-corruption agency, and each sum is spent on a project with its source on the signboard. The people named do not forget.',
        blurb: 'Every naira recovered from abroad or from a former official listed online, by name, and spent on a school, a clinic or a bridge with a plaque saying whose money it was. It is national pride with a receipt. Some of the names will be your party\'s.',
        start: [['bloc.party', -4]],
        done: [['nation.fiscalSpace', 0.4], ['approval', 3], ['bloc.street', 5], ['bloc.press', 4], ['nation.integrity', 3]],
        news: ['FIRST RECOVERED-LOOT REGISTER PUBLISHED; ₦400BN TO BE SPENT ON 60 PROJECTS', 'THE MONEY DEM THIEF DON COME BACK. NA SCHOOL E GO BUILD'],
        archive: 'Published a register of recovered loot and spent it on named projects.',
      },
      {
        id: 'o1', name: 'A law against "falsehood" on the internet', pc: 5, naira: 0, months: 4, popular: true, ...SENATE,
        lasting: 'Bad stories die faster every month. With integrity low, it is used on critics, and costs a little integrity each month.',
        blurb: 'Fines and prison for publishing what a minister certifies to be false. Your own people have drafted it and are keen. It would make your worst weeks quieter, and it would be used by every President after you.',
        start: [['bloc.villa', 4], ['bloc.press', -5]],
        done: [['pressure.scandalHeat', -18], ['bloc.villa', 4], ['bloc.press', -12], ['bloc.street', -8], ['nation.integrity', -4], ['rival.fire', 9], ['bloc.establishment', -3]],
        news: ['INTERNET FALSEHOOD ACT SIGNED; FIRST ARRESTS MADE', 'TALK TRUE FOR ONLINE, GO PRISON. NA THE NEW LAW'],
        archive: 'Signed a law against "falsehood" on the internet.',
      },
    ],
  },
  {
    id: 'resources', name: 'Beyond Oil', goal: 'Gas, minerals, crops and the money sent home', metric: 'nation.jobs', loose: true,
    milestones: [
      {
        id: 'g1', name: 'End gas flaring: pipe it to plants and kitchens', pc: 6, naira: 0.7, months: 12,
        lasting: 'Less of the budget rides on crude, and the plants have gas when the grid is under strain.',
        blurb: 'The gas burned off in the creeks every night would run a third of the grid. Capture it, pipe it and sell it.',
        done: [['nation.power', 6], ['bonus.power', 0.03], ['bonus.fiscal', 0.012], ['zone.SS.approval', 4], ['nation.jobs', 3]],
        news: ['FLARES GO OUT ACROSS THE DELTA AS GAS REACHES POWER PLANTS', 'THE FIRE WEY DEY BURN FOR CREEK DON QUENCH'],
        archive: 'Ended gas flaring and piped the gas to power plants and homes.',
      },
      {
        id: 'g2', name: 'Mining licences auctioned in public', pc: 9, naira: 0.2, months: 8,
        lasting: 'Less of the budget rides on crude, and the illegal mines that pay for the gangs in the North West close.',
        blurb: 'Every gold, lithium and tin licence bid for in the open, and the old ones reviewed. Much of the illegal mining in the North West belongs to people you know, and some of it pays for the gangs.',
        start: [['person.gov_nw', -8], ['bloc.party', -4]],
        done: [['bonus.fiscal', 0.02], ['nation.jobs', 5], ['theatre.NW', -5], ['drift.NW', -0.06], ['nation.integrity', 3], ['bloc.establishment', 4]],
        news: ['FIRST PUBLIC MINING AUCTION RAISES ₦400BN', 'GOLD LICENCE NOW NA AUCTION. BIG MEN DEY VEX'],
        archive: 'Auctioned mining licences in public and reviewed the old ones.',
      },
      {
        id: 'g7', name: 'Cocoa, sesame and cashew, graded and sold abroad at scale', pc: 4, naira: 0.5, months: 10,
        lasting: 'Dollars from crops every month, a budget that leans less on oil, and when world crop prices boom the country is ready to sell into it.',
        blurb: 'Grading sheds, export certificates and a single agency that answers a buyer in a week instead of a year. The country was the world\'s second cocoa grower once. Farmers in the South West, the Middle Belt and the North all gain; the middlemen who buy cheap at the farm gate do not.',
        done: [['nation.jobs', 4], ['zone.SW.approval', 3], ['zone.NC.approval', 3], ['zone.NW.approval', 2], ['tycoon.ty_trade', -4]],
        news: ['CROP EXPORTS DOUBLE AS GRADING CENTRES OPEN', 'COCOA DON DEY GO OUTSIDE AGAIN. FARMERS DEY SMILE'],
        archive: 'Built an export trade in graded cocoa, sesame and cashew.',
      },
      {
        id: 'g6', name: 'Make sending money home cheap, fast and official', pc: 5, naira: 0.1, months: 5,
        lasting: 'More dollars arrive through the banks every month instead of the black market, as long as the official rate is close to the street rate. A wide gap sends it back underground.',
        blurb: 'Fees capped, transfers landing in minutes, and the official rate honoured on arrival. Nigerians abroad send home more than the oil industry earns in some years; most of it travels through the black market. Bring it into the open and it props up the naira. The banks lose a fat margin and will tell you so.',
        done: [['tycoon.ty_bank', -6], ['approval', 1], ['fx.reserves', 1]],
        news: ['FEES ON MONEY SENT HOME CAPPED; TRANSFERS NOW INSTANT', 'MONEY FROM ABROAD DON DEY LAND SHARP SHARP. NO MORE BLACK MARKET'],
        archive: 'Made sending money home cheap, fast and official.',
      },
      {
        id: 'g4', name: 'Sell the state\'s shares in the oil joint ventures', pc: 8, naira: 0, months: 6,
        during: [['bloc.street', -0.75], ['bloc.press', -0.75]], duringText: '"Selling the family silver" runs every week.',
        lasting: 'Oil revenue is smaller in every term after this, and so is the damage when the price falls.',
        blurb: 'About ₦3.5tn, in cash, in your term. In exchange the Treasury gives up that share of oil revenue for good, and with it some of its exposure to the price. Whether this is prudence or pawning depends entirely on what you do with the money.',
        start: [['bloc.street', -3]],
        done: [['nation.fiscalSpace', 3.5], ['bonus.fiscal', -0.045], ['bloc.establishment', 6], ['bloc.street', -4], ['tycoon.ty_bank', 5]],
        news: ['FG SELLS JOINT VENTURE STAKES FOR ₦3.5TN', 'GOVERNMENT DON SELL OIL SHARE. THE MONEY, WHERE E DEY GO?'],
        archive: 'Sold the state\'s shares in the oil joint ventures.',
      },
    ],
  },
];
