import type { GameState, Milestone, Track } from '../engine/types';

// THE REFORM LIBRARY, SECOND EDITION
// Reforms are policy generations, not a list to finish. Each track has its
// foundations (in order, or any order on a loose track); once they are delivered
// the deepening opens; and some problems appear only because of what an earlier
// government did, and only while they exist. Some reforms are rival answers to
// the same question: choosing one closes the other, and neither is the right one.
// Some can be undone by a President for a gain now; the next one inherits the
// damage and can restore them. Programmes that exist in some form at the start
// are on the statute book: the work is doing them properly.
// Names of laws and programmes are invented.

const SENATE = { needs: { v: ['senate', '>=', 50] as [string, '>=', number] }, needsText: 'You do not have the Senate. Win over your senators first.' };
const AMEND = { needs: { v: ['senate', '>=', 56] as [string, '>=', number] }, needsText: 'It changes the constitution: two thirds of the Senate and the state assemblies. Your senators and governors must be firmly with you.' };

const done = (s: GameState, id: string) => s.agenda.done.includes(id);
const openCases = (s: GameState) => (s.cases ?? []).filter((c) => !c.outcome).length;

// ------------------------------------------------------------ renamed and rewritten
// Same reform, same consequences; a name and a promise that make sense of it.
export const REWRITE: Record<string, Partial<Milestone>> = {
  p4: {
    name: 'Complete the state electricity-market transition',
    onBooks: 'The Power Sector Act already lets states run their own electricity markets. Most have not started. The work is making them.',
    blurb: 'States regulate and buy their own power; private firms generate and sell. The law exists; the regulators, the tariffs and the contracts do not.',
    news: ['STATES TAKE OVER THEIR ELECTRICITY MARKETS', 'STATES DON DEY RUN THEIR OWN LIGHT'],
    archive: 'Completed the transition to state electricity markets.',
  },
  p5: {
    name: 'Ten high-reliability electricity zones',
    blurb: 'Ten industrial and city zones on ring-fenced feeders, metered, with penalties for every hour off. A mechanism that can fail, not a promise that can be broken.',
    news: ['TEN HIGH-RELIABILITY POWER ZONES GO LIVE', 'TEN PLACES WEY LIGHT NO DEY GO'],
    archive: 'Built ten high-reliability electricity zones.',
  },
  s2: {
    name: 'Joint security commands in the worst-hit theatres',
    blurb: 'Army, police and intelligence under one commander in each theatre that is losing, with forward bases where the attacks come from.',
    news: ['JOINT COMMANDS TAKE OVER IN THE WORST-HIT STATES', 'ARMY, POLICE, DSS DON JOIN HAND'],
    archive: 'Set up joint security commands in the worst-hit theatres.',
  },
  s4: {
    onBooks: 'A draft framework for state police has sat with the Assembly since the last government. Most of the drafting is done; the votes are not.',
  },
  s5: {
    name: 'Local justice and policing hubs in every underserved district',
    blurb: 'A magistrate, a police post and a legal-aid desk where there are none: somewhere to report a crime and somewhere to try it.',
    news: ['JUSTICE HUBS OPEN IN UNDERSERVED DISTRICTS', 'POLICE AND COURT DON REACH OUR AREA'],
    archive: 'Opened local justice and policing hubs in underserved districts.',
  },
  f2: {
    name: 'Farm security corridors and rural intelligence',
    blurb: 'Patrolled corridors from farm to market for the months that matter, and informants paid to say where the gangs are camped.',
    news: ['FARM CORRIDORS OPEN; FARMERS RETURN TO ABANDONED LAND', 'FARMERS DON RETURN TO FARM'],
  },
  f4: {
    name: 'An automatic food-import trigger',
    blurb: 'When staple prices rise past a threshold, import duties fall by themselves until they ease. An institution, not a favour the President remembers to grant. Farmers will hate it in a good harvest.',
    news: ['FOOD-IMPORT TRIGGER BECOMES LAW', 'WHEN FOOD COST, BORDER GO OPEN BY ITSELF'],
    archive: 'Made staple imports open automatically when prices spike.',
  },
  i5: {
    name: 'Make Nigeria a net exporter of refined petroleum products',
    blurb: 'Refineries that compete, crude sold to them at market, and product sold abroad. The aim is competitiveness, not a ban.',
    news: ['NIGERIA BECOMES NET EXPORTER OF REFINED FUEL', 'WE DON DEY SELL FUEL GIVE OTHER COUNTRY'],
    archive: 'Made Nigeria a net exporter of refined petroleum products.',
  },
  d1: { name: 'Fibre backbone, open to every operator, in every local government', news: ['OPEN-ACCESS FIBRE REACHES ALL 774 LOCAL GOVERNMENTS', 'NETWORK DON REACH VILLAGE'] },
  d2: {
    name: 'Apply the Founders\' Charter in full',
    onBooks: 'The Founders\' Charter was passed years ago. The regulators never applied it, and three of them still ban things by press release.',
    blurb: 'The sandbox, the tax holiday and the founder visas the Charter promised, actually granted, with a deadline for every regulator.',
    news: ['FOUNDERS\' CHARTER FINALLY APPLIED; STARTUPS RELOCATE HOME', 'TECH BROS DON RETURN FROM ABROAD'],
    archive: 'Applied the Founders\' Charter in full.',
  },
  d3: {
    name: 'Turn the Skills Million programme into jobs and exports',
    onBooks: 'The Skills Million programme already trains young people. Too few of them find work at the end of it.',
    blurb: 'Training paid for by results: a job, a contract or an export earning. Certificates nobody hires on stop being funded.',
    news: ['SKILLS MILLION GRADUATES NOW EARN IN DOLLARS REMOTELY', 'YOUTHS DEY EARN DOLLAR FROM HOUSE'],
    archive: 'Tied the Skills Million programme to jobs and exports.',
  },
  d4: { name: 'Interoperable identity, payments and government rails' },
  d5: {
    name: 'A Nigerian cloud and compute market',
    blurb: 'Data centres on cheap gas power, open to any provider, and a rule that public data is processed at home.',
    news: ['NIGERIAN CLOUD MARKET OPENS WITH SIX PROVIDERS', 'BIG TECH DON COME BUILD FOR NAIJA'],
    archive: 'Built a Nigerian cloud and compute market.',
  },
  e2: {
    name: 'Universities funded through a predictable settlement',
    blurb: 'A funding formula in law, paid on a date, so that lecturers stop striking for what was agreed eleven years ago.',
    news: ['UNIVERSITIES GET FUNDING FORMULA IN LAW', 'ASUU NO GO STRIKE AGAIN? WE GO SEE'],
    archive: 'Put university funding on a predictable legal settlement.',
  },
  e4: { name: 'National health insurance, expanded to fifty million' },
  h3: { onBooks: 'A cash-transfer register already exists. It reaches a third of the people on it.' },
  h5: { name: 'Mortgage-market reform: a million homes people can buy' },
  o6: { name: 'A modern border and immigration system' },
  g4: { excludes: ['g13'] },
};

// ------------------------------------------------------------ reversals
// Undoing a reform is sometimes the rational thing to do. It is recorded, and the next President inherits it.
export const REVERSALS: Record<string, NonNullable<Milestone['reversal']>> = {
  w2: { label: 'Borrow from the road fund, "temporarily"', text: 'The road fund lends the Treasury what it holds. Everyone agrees it will be paid back.', gain: [['nation.fiscalSpace', 0.6], ['bonus.jobs', -0.02]], news: ['ROAD FUND "BORROWED" TO COVER SHORTFALL', 'ROAD MONEY DON ENTER ANOTHER POCKET'] },
  t3: { label: 'Restore the waivers, for friends', text: 'Duty waivers return for a list of approved importers. The list is not published.', gain: [['pc', 6], ['tycoon.ty_trade', 15], ['tycoon.ty_maker', 10], ['bonus.fiscal', -0.02], ['nation.integrity', -3]], news: ['IMPORT WAIVERS QUIETLY RESTORED', 'WAIVER DON RETURN. WHO GET AM?'] },
  p3: { label: 'Cap the electricity tariff', text: 'The tariff is capped by directive. The distribution companies are told the difference will be paid. It will not be.', gain: [['approval', 3], ['bloc.street', 5], ['bonus.power', -0.04], ['bonus.fiscal', -0.02]], news: ['PRESIDENT CAPS ELECTRICITY TARIFF', 'LIGHT BILL DON COME DOWN. LIGHT GO FOLLOW?'] },
  v5: { label: 'Take the functions back from the states', text: 'Sixty functions return to Abuja, with the money and the appointments that go with them.', gain: [['bloc.villa', 6], ['pc', 4], ['nation.capacity', -5], ['bloc.party', -5]], news: ['FEDERAL GOVERNMENT RECENTRALISES SIXTY FUNCTIONS', 'ABUJA DON COLLECT THEIR WORK BACK'] },
  c3: { label: 'Exempt serving officials from publishing their assets', text: 'Declarations by serving officials are "deferred" until they leave office.', gain: [['bloc.party', 6], ['bloc.villa', 4], ['nation.integrity', -6], ['bloc.press', -5]], news: ['SERVING OFFICIALS EXEMPTED FROM ASSET DISCLOSURE', 'DEM DON HIDE THEIR PROPERTY AGAIN'] },
  c4: { label: 'Bring the prosecutor back under the Attorney General', text: 'The independent prosecutor is merged into the Attorney General\'s office "for coordination".', gain: [['bloc.villa', 5], ['bloc.party', 5], ['nation.integrity', -5], ['bloc.press', -4]], news: ['INDEPENDENT PROSECUTOR MERGED INTO JUSTICE MINISTRY', 'PROSECUTOR DON GET OGA AGAIN'] },
  t4: { label: 'Suspend the debt ceiling for an "emergency"', text: 'The ceiling is suspended for twelve months. The emergency is not specified.', gain: [['nation.fiscalSpace', 1.0], ['debt.bonds', 1.2], ['bloc.establishment', -6]], news: ['DEBT CEILING SUSPENDED UNDER EMERGENCY CLAUSE', 'DEM DON REMOVE THE BORROW LIMIT'] },
  c1: { label: 'Exempt security contracts from open contracting', text: 'Anything with "security" in the title is exempt. Within a month, most contracts are.', gain: [['bloc.establishment', 4], ['pc', 4], ['nation.integrity', -4]], news: ['SECURITY CONTRACTS EXEMPTED FROM PUBLICATION', 'NA SECURITY: DEM NO GO SHOW US CONTRACT AGAIN'] },
  f4: { label: 'Suspend the import trigger to protect farmers', text: 'The trigger is suspended "for this harvest". The licence-holders send their thanks.', gain: [['zone.NC.approval', 4], ['zone.NW.approval', 4], ['bloc.party', 4], ['bonus.inflation', 1]], news: ['FOOD-IMPORT TRIGGER SUSPENDED', 'BORDER DON CLOSE AGAIN FOR FOOD'] },
  j7: { label: 'Take judicial appointments back into the Villa', text: 'The commission is "restructured". Its shortlists now come from the Villa.', gain: [['bloc.villa', 5], ['nation.integrity', -4], ['bloc.establishment', -5]], news: ['JUDICIAL APPOINTMENTS COMMISSION RESTRUCTURED', 'NA PRESIDENT GO DEY PICK JUDGE AGAIN'] },
  c9: { label: 'Appoint the watchdog heads yourself again', text: 'The independent panel is dissolved. The next heads of the watchdogs will be people you trust.', gain: [['bloc.villa', 4], ['pc', 3], ['nation.integrity', -4]], news: ['WATCHDOG APPOINTMENTS PANEL DISSOLVED', 'PRESIDENT GO DEY PICK WHO GO WATCH AM'] },
};

// ------------------------------------------------------------ helpers for writing reforms compactly
type M = Milestone;
const g2 = (m: Omit<M, 'gen'>): M => ({ ...m, gen: 2 });
const g3 = (m: Omit<M, 'gen'>): M => ({ ...m, gen: 3 });

// ------------------------------------------------------------ the deepening, and the repairs, by track
export const ADD: Record<string, M[]> = {
  power: [
    g2({ id: 'p6', name: 'Meter everyone and attack distribution losses', pc: 8, naira: 0.6, months: 12, blurb: 'Eight million meters, and an end to estimated billing. A third of the power that leaves the grid is stolen or never billed.', start: [['tycoon.ty_fuel', -6]], done: [['nation.power', 6], ['bonus.fiscal', 0.02], ['bonus.power', 0.03], ['bloc.street', 3]], news: ['EIGHT MILLION METERS INSTALLED; ESTIMATED BILLS END', 'NO MORE CRAZY BILL. METER DON COME'], archive: 'Metered every customer and attacked distribution losses.' }),
    g2({ id: 'p7', name: 'Auction new generation and storage competitively', pc: 6, naira: 0.2, months: 10, blurb: 'New plants and batteries bought at public auction, lowest price wins. The friends who used to be handed licences will not bid.', start: [['tycoon.ty_fuel', -8]], done: [['nation.power', 8], ['bonus.power', 0.04], ['nation.integrity', 2]], news: ['FIRST POWER AUCTION CUTS PRICE BY A THIRD', 'LIGHT AUCTION DON START. CHEAP POWER DEY COME'], archive: 'Auctioned new generation and storage competitively.' }),
    g2({ id: 'p8', name: 'Fix gas-to-power payments and pipelines', pc: 6, naira: 0.7, months: 12, lasting: 'Gas debt stops building up: the plants are paid through an escrow the Treasury cannot touch.', blurb: 'An escrow that pays gas suppliers first, and the pipelines that keep breaking repaired and guarded.', done: [['nation.power', 7], ['debt.gas', -0.3], ['bonus.power', 0.03]], flags: { 'power.escrow': true }, news: ['GAS-TO-POWER ESCROW ENDS PLANT SHUTDOWNS', 'GAS PEOPLE DON DEY COLLECT THEIR MONEY'], archive: 'Fixed gas-to-power payments and pipelines.' }),
    g2({ id: 'p9', name: 'Connect state markets and mini-grids', pc: 6, naira: 0.5, months: 10, blurb: 'Mini-grids in villages the grid never reached, and state markets connected so a surplus in one can light another.', done: [['nation.power', 6], ['nation.jobs', 3], ['bonus.power', 0.03], ['zone.NE.approval', 2], ['zone.NW.approval', 2]], news: ['TEN THOUSAND MINI-GRIDS LIGHT VILLAGES FOR FIRST TIME', 'VILLAGE DON SEE LIGHT FIRST TIME'], archive: 'Connected state markets and built mini-grids.' }),
    g2({ id: 'p10', name: 'Grid reserves and blackout recovery', pc: 4, naira: 0.6, months: 10, blurb: 'Spare capacity held in reserve and a plan to restart the grid in hours, not days, when it falls.', done: [['nation.power', 5], ['bonus.power', 0.04], ['approval', 2]], news: ['GRID RESTORED IN THREE HOURS AFTER COLLAPSE', 'LIGHT GO, LIGHT COME BACK QUICK'], archive: 'Built grid reserves and a blackout recovery plan.' }),
    g2({ id: 'p14', name: 'Re-tender the distribution companies and regulate them hard', pc: 12, naira: 0, months: 10, excludes: ['p15'], blurb: 'The failing distribution companies lose their licences to bidders who must meet targets or pay. The private road, made to work.', start: [['tycoon.ty_bank', -6], ['bloc.party', -3]], done: [['nation.power', 9], ['bonus.fiscal', 0.02], ['bonus.power', 0.03], ['bloc.establishment', 5]], news: ['DISTRIBUTION LICENCES RE-TENDERED UNDER STRICT TARGETS', 'DISCOS WEY NO PERFORM DON COMOT'], archive: 'Re-tendered the distribution companies under hard regulation.' }),
    g2({ id: 'p15', name: 'A public power company that answers to the President', pc: 8, naira: 1.0, months: 14, excludes: ['p14'], blurb: 'The state buys back distribution and runs it. Accountable to you, and to everyone who will ever want a job in it.', start: [['bloc.establishment', -5]], done: [['nation.power', 7], ['bloc.street', 5], ['bonus.fiscal', -0.02], ['nation.jobs', 3], ['nation.integrity', -1]], news: ['FEDERAL POWER COMPANY TAKES OVER DISTRIBUTION', 'GOVERNMENT DON BUY BACK NEPA'], archive: 'Created a public power company to run distribution.' }),
    g3({ id: 'p11', name: 'Enforce the lifeline band', pc: 4, naira: 0.3, months: 6, emerge: (s) => done(s, 'p3') && s.nation.inflation >= 22, emergeText: 'The tariff paid for the power sector; the poorest are paying for it too, because the lifeline band was never enforced.', blurb: 'Audits of every distribution company\'s lifeline customers, and refunds where the poor were billed as rich.', done: [['bloc.street', 6], ['approval', 2], ['pressure.wageGrievance', -6]], news: ['LIFELINE TARIFF ENFORCED; MILLIONS REFUNDED', 'POOR PEOPLE LIGHT BILL DON COME DOWN'], archive: 'Enforced the electricity lifeline band.' }),
    g3({ id: 'p12', name: 'Clean up the meter market', pc: 6, naira: 0.1, months: 6, emerge: (s) => done(s, 'p6') && s.nation.integrity < 35, emergeText: 'Mass metering created a market in fake meters and paid-for bypasses.', blurb: 'Every meter registered and tamper-proofed; installers licensed; the bypass trade prosecuted.', done: [['nation.power', 4], ['bonus.fiscal', 0.01], ['nation.integrity', 2]], news: ['FAKE METER RACKET BROKEN UP', 'FAKE METER DON CATCH'], archive: 'Cleaned up the meter market.' }),
    g3({ id: 'p13', name: 'One grid, many markets', pc: 8, naira: 0.4, months: 8, emerge: (s) => done(s, 'p4') && s.nation.power < 45, emergeText: 'The state markets work on their own and fight each other over the shared grid.', blurb: 'A single grid code and a settlement system that every state market must use.', done: [['nation.power', 6], ['bonus.power', 0.03], ['nation.capacity', 2]], news: ['ONE GRID CODE ENDS STATE POWER WARS', 'STATES DON AGREE ON ONE GRID'], archive: 'Brought the state electricity markets under one grid code.' }),
  ],
  security: [
    g2({ id: 's6', name: 'Professional police: recruitment, pay and promotion', pc: 8, naira: 0.6, months: 12, emerge: (s) => s.flags['night.coup'] === 'real' || s.flags['night.coup'] === 'probe', emergeText: 'The night of the rumour showed how thin the line was.', blurb: 'Recruitment by exam, promotion by record, and pay that does not need a checkpoint to top it up.', done: [['nation.security', 6], ['nation.integrity', 2], ['sec.hold', 0.3], ['bonus.fiscal', -0.015]], news: ['POLICE RECRUITMENT BY EXAM; PAY DOUBLED', 'POLICE NO GO NEED TO COLLECT BRIBE AGAIN?'], archive: 'Professionalised police recruitment, pay and promotion.' }),
    g2({ id: 's7', name: 'An independent policing standards inspectorate', pc: 8, naira: 0.1, months: 8, blurb: 'Inspectors who answer to the Assembly, publish every station\'s record, and can close the worst.', start: [['bloc.establishment', -3]], done: [['nation.integrity', 4], ['bloc.street', 4], ['sec.shield', 0.2]], news: ['POLICE INSPECTORATE PUBLISHES FIRST STATION RANKINGS', 'POLICE STATION DON GET REPORT CARD'], archive: 'Created an independent policing standards inspectorate.' }),
    g2({ id: 's8', name: 'A national crime and forensic data network', pc: 4, naira: 0.5, months: 10, lasting: 'Prosecutions are better evidenced: convictions are likelier.', blurb: 'Fingerprints, ballistics and case files in one system, and laboratories that can test what is found.', done: [['nation.security', 4], ['nation.capacity', 3], ['sec.strike', 0.2]], news: ['NATIONAL FORENSIC NETWORK SOLVES ITS FIRST COLD CASES', 'POLICE DON GET LAB. CRIMINAL DEY FEAR'], archive: 'Built a national crime and forensic data network.' }),
    g2({ id: 's9', name: 'Witness protection and prosecution reform', pc: 6, naira: 0.2, months: 8, lasting: 'Witnesses testify: convictions are likelier.', blurb: 'Witnesses who are protected, and prosecutors who are trained and paid to win.', done: [['nation.integrity', 3], ['nation.security', 2]], news: ['WITNESS PROTECTION LAW SIGNED; KEY TRIALS RESUME', 'WITNESS FIT TALK NOW WITHOUT FEAR'], archive: 'Created witness protection and reformed prosecution.' }),
    g2({ id: 's10', name: 'Rebuild and compensate communities taken back from armed groups', pc: 4, naira: 0.8, months: 12, blurb: 'Homes, markets and schools rebuilt where the army has cleared, and compensation paid to the families who lost them, so that cleared ground stays cleared.', done: [['sec.hold', 0.4], ['drift.NE', -0.08], ['drift.NW', -0.06], ['zone.NE.approval', 5], ['zone.NW.approval', 3]], news: ['RECOVERED TOWNS REBUILT; FAMILIES RETURN', 'PEOPLE DON RETURN TO THEIR VILLAGE'], archive: 'Rebuilt and compensated communities recovered from armed groups.' }),
    g3({ id: 's11', name: 'A federal policing equalisation fund', pc: 6, naira: 0.5, months: 8, emerge: (s) => done(s, 's4') && s.nation.capacity < 45, emergeText: 'State police works in rich states. Poor states cannot pay theirs.', blurb: 'Federal money for state police in the states that cannot afford them, tied to standards.', done: [['nation.security', 4], ['sec.shield', 0.2], ['bloc.party', 3], ['bonus.fiscal', -0.01]], news: ['POOR STATES GET FEDERAL HELP TO PAY THEIR POLICE', 'FG GO HELP STATES PAY THEIR POLICE'], archive: 'Created a federal equalisation fund for state police.' }),
    g3({ id: 's12', name: 'An independent state police inspectorate', pc: 10, naira: 0.1, months: 8, emerge: (s) => done(s, 's4') && (s.nation.integrity < 35 || s.pressures.scandalHeat > 55), emergeText: 'Some governors are using their police against their opponents.', blurb: 'An inspectorate that can suspend a state police command used for politics.', start: [['bloc.party', -6]], done: [['nation.integrity', 5], ['bloc.street', 4], ['bloc.press', 4]], news: ['STATE POLICE INSPECTORATE SUSPENDS TWO COMMANDS', 'GOVERNOR POLICE DON GET WHO GO CHECK AM'], archive: 'Created an independent inspectorate for state police.' }),
    g3({ id: 's13', name: 'A national policing compact', pc: 6, naira: 0, months: 6, emerge: (s) => done(s, 's11') && done(s, 's12'), emergeText: 'State and federal police are fighting over who has jurisdiction.', blurb: 'Who arrests whom, for what, written down and signed by every governor.', done: [['nation.security', 4], ['nation.capacity', 2], ['bloc.party', 2]], news: ['GOVERNORS SIGN NATIONAL POLICING COMPACT', 'POLICE DON KNOW WHO GET WETIN'], archive: 'Signed a national policing compact with the states.' }),
  ],
  treasury: [
    g2({ id: 't6', name: 'An independent fiscal council', pc: 6, naira: 0, months: 6, lasting: 'The oil forecast the budget is built on is checked by the council: it leans less and errs less.', blurb: 'Economists who publish their own forecast beside the Finance Minister\'s, and say so when the budget is fiction.', start: [['bloc.party', -2]], done: [['bloc.establishment', 6], ['nation.capacity', 2], ['nation.debt', -2]], news: ['FISCAL COUNCIL\'S FIRST REPORT CALLS BUDGET "OPTIMISTIC"', 'NEW COUNCIL SAY BUDGET NA STORY'], archive: 'Created an independent fiscal council.' }),
    g2({ id: 't7', name: 'No contract without cash behind it', pc: 8, naira: 0, months: 4, lasting: 'Shortfalls stop turning into contractor arrears as fast: nothing is signed that cannot be paid.', blurb: 'A contract is signed only when the money is in the account. The ribbon-cutting stops; so do the abandoned sites.', start: [['bloc.party', -4]], done: [['nation.capacity', 3], ['bloc.establishment', 4], ['nation.jobs', -2]], news: ['NO CASH, NO CONTRACT: NEW RULE TAKES EFFECT', 'NO MONEY, NO CONTRACT AGAIN'], archive: 'Banned contracts without cash backing.' }),
    g2({ id: 't8', name: 'Publish every subsidy and every arrear', pc: 6, naira: 0, months: 4, blurb: 'What the government owes and to whom, and every subsidy it pays, online every quarter.', done: [['nation.integrity', 4], ['bloc.press', 4], ['bloc.establishment', 3], ['pressure.scandalHeat', 4]], news: ['GOVERNMENT PUBLISHES WHAT IT OWES, LINE BY LINE', 'NOW WE KNOW WHO GOVERNMENT DEY OWE'], archive: 'Published every subsidy and arrear.' }),
    g2({ id: 't9', name: 'An oil-windfall stabilisation rule', pc: 8, naira: 0, months: 4, ...SENATE, blurb: 'Oil money above the benchmark is saved by law, not shared at the next governors\' meeting.', start: [['bloc.party', -5]], done: [['fund.buffer', 0.3], ['bloc.establishment', 5], ['nation.debt', -2]], news: ['OIL WINDFALL RULE SIGNED: EXCESS TO BE SAVED', 'OIL MONEY GO DEY SAVE BY LAW'], archive: 'Signed an oil-windfall stabilisation rule.' }),
    g2({ id: 't10', name: 'A performance-based fiscal compact with the states', pc: 8, naira: 0.3, months: 8, blurb: 'Extra money for states that publish their budgets, pay salaries and collect their own taxes.', done: [['nation.capacity', 3], ['bonus.fiscal', 0.015], ['bloc.party', 2]], news: ['STATES THAT PERFORM GET MORE UNDER NEW COMPACT', 'STATE WEY DO WELL GO GET MORE MONEY'], archive: 'Signed a performance-based fiscal compact with the states.' }),
    g3({ id: 't11', name: 'Clear the arrears the cash rule exposed', pc: 4, naira: 0.6, months: 6, emerge: (s) => done(s, 't7') && s.debts.contractors > 1, emergeText: 'The cash rule stopped new arrears and revealed how many old ones there were.', blurb: 'A verified, published schedule to pay the old arrears, oldest and smallest first.', done: [['debt.contractors', -0.5], ['nation.jobs', 3], ['bloc.establishment', 3]], news: ['GOVERNMENT PUBLISHES SCHEDULE TO CLEAR OLD ARREARS', 'CONTRACTORS GO COLLECT THEIR MONEY FINALLY'], archive: 'Cleared the arrears the cash rule exposed.' }),
  ],
  clean: [
    g2({ id: 'c6', name: 'A whistleblower protection law', pc: 6, naira: 0, months: 6, emerge: (s) => s.pressures.scandalHeat > 60, emergeText: 'The scandals keep coming from inside; nobody inside is protected for saying so.', blurb: 'Protection and a share of what is recovered for anyone who reports theft of public money.', start: [['bloc.party', -3]], done: [['nation.integrity', 5], ['bloc.press', 4], ['pressure.scandalHeat', 5]], news: ['WHISTLEBLOWER LAW SIGNED; FIRST REWARDS PAID', 'IF YOU TALK, YOU GO CHOP REWARD'], archive: 'Signed a whistleblower protection law.' }),
    g2({ id: 'c7', name: 'A beneficial-ownership and lobbying register', pc: 8, naira: 0, months: 6, blurb: 'Who really owns every company that wins a contract, and who they paid to meet a minister.', start: [['tycoon.ty_trade', -6], ['tycoon.ty_fuel', -6]], done: [['nation.integrity', 5], ['bloc.establishment', 3], ['bloc.press', 3]], news: ['WHO OWNS WHAT: OWNERSHIP REGISTER GOES ONLINE', 'NOW WE KNOW WHO GET THE COMPANY'], archive: 'Created a beneficial-ownership and lobbying register.' }),
    g2({ id: 'c8', name: 'Transparent political finance', pc: 10, naira: 0, months: 8, ...SENATE, lasting: 'Campaign money from businessmen must be declared: it counts for a little less, and costs a little less integrity.', blurb: 'Every donation over a limit published, and spending limits enforced.', start: [['bloc.party', -6]], done: [['nation.integrity', 6], ['bloc.street', 4], ['bloc.press', 4]], flags: { 'finance.open': true }, news: ['CAMPAIGN DONATIONS TO BE PUBLISHED BY LAW', 'WHO DEY FUND POLITICIAN? WE GO KNOW NOW'], archive: 'Made political finance transparent.' }),
    g2({ id: 'c9', name: 'Independent appointments for the watchdogs', pc: 8, naira: 0, months: 6, blurb: 'The heads of the anti-corruption agency, the auditor and the electoral commission chosen by an independent panel, not by you.', start: [['bloc.villa', -4]], done: [['nation.integrity', 5], ['bloc.establishment', 4], ['bonus.integrity', 0.03]], news: ['WATCHDOG HEADS TO BE CHOSEN BY INDEPENDENT PANEL', 'PRESIDENT NO GO PICK WHO GO WATCH AM'], archive: 'Gave the watchdogs independent appointments.' }),
    g2({ id: 'c10', name: 'Lifestyle audits of public officials', pc: 8, naira: 0.1, months: 6, blurb: 'An official whose spending does not match their salary is asked to explain the difference.', start: [['bloc.party', -4], ['bloc.villa', -2]], done: [['nation.integrity', 5], ['bloc.street', 4], ['pressure.scandalHeat', 3]], news: ['LIFESTYLE AUDITS BEGIN; THREE OFFICIALS SUSPENDED', 'YOUR SALARY NO REACH YOUR HOUSE? EXPLAIN'], archive: 'Introduced lifestyle audits of public officials.' }),
  ],
  service: [
    g2({ id: 'v6', name: 'Merge or abolish duplicate agencies', pc: 10, naira: 0, months: 8, blurb: 'Five hundred agencies, a third of them doing what another already does. Each one is someone\'s board seat.', start: [['bloc.party', -5]], done: [['nation.capacity', 6], ['bonus.fiscal', 0.02]], news: ['NINETY AGENCIES MERGED OR ABOLISHED', 'DEM DON CLOSE AGENCIES WEY NO DEY DO ANYTHING'], archive: 'Merged or abolished duplicate agencies.' }),
    g2({ id: 'v7', name: 'Performance contracts for permanent secretaries', pc: 6, naira: 0, months: 6, blurb: 'Targets in writing, published, and renewal only if they are met.', done: [['nation.capacity', 5], ['bonus.capacity', 0.03]], news: ['PERMANENT SECRETARIES SIGN PERFORMANCE CONTRACTS', 'PERM SEC GO PERFORM OR GO HOME'], archive: 'Put permanent secretaries on performance contracts.' }),
    g2({ id: 'v8', name: 'One government licensing portal', pc: 4, naira: 0.2, months: 8, blurb: 'Every federal licence and permit applied for, paid for and tracked in one place, with a clock that runs.', done: [['nation.capacity', 3], ['nation.jobs', 4], ['nation.integrity', 2]], news: ['ONE PORTAL FOR EVERY FEDERAL LICENCE', 'YOU FIT GET LICENCE ONLINE NOW'], archive: 'Built one licensing portal for the federal government.' }),
    g2({ id: 'v9', name: 'Public-service standards citizens can enforce', pc: 6, naira: 0, months: 6, blurb: 'A passport in two weeks, a certificate in five days, and compensation when the government is late.', done: [['nation.capacity', 3], ['bloc.street', 5], ['approval', 2]], news: ['CITIZENS CAN NOW SUE FOR LATE GOVERNMENT SERVICE', 'GOVERNMENT LATE? DEM GO PAY YOU'], archive: 'Made public-service standards enforceable.' }),
    g2({ id: 'v10', name: 'Capacity grants for states that perform', pc: 4, naira: 0.5, months: 8, blurb: 'Money and expertise for the states and local governments that show they can use it.', done: [['nation.capacity', 4], ['bloc.party', 3], ['bonus.capacity', 0.02]], news: ['CAPACITY GRANTS FOR STATES THAT DELIVER', 'STATES WEY DEY WORK GO GET HELP'], archive: 'Gave capacity grants to states that perform.' }),
    g3({ id: 'v11', name: 'Pay the civil servants the merit reform left behind', pc: 4, naira: 0.4, months: 6, emerge: (s) => done(s, 'v2') && s.pressures.wageGrievance > 60, emergeText: 'Merit pay raised the new recruits and left the old staff behind, and the old staff are the union.', blurb: 'A transition allowance and a path into the new grades for those already in post.', done: [['pressure.wageGrievance', -15], ['nation.capacity', 2], ['bonus.fiscal', -0.01]], news: ['OLD CIVIL SERVANTS GET PATH INTO NEW PAY GRADES', 'OLD STAFF NO GO SUFFER AGAIN'], archive: 'Brought older civil servants into the merit pay grades.' }),
  ],
  food: [
    g2({ id: 'f6', name: 'Secure, tradable agricultural leases', pc: 8, naira: 0.2, months: 10, blurb: 'Farmers who lease land for twenty-five years invest in it; lenders lend against it.', start: [['zone.NC.approval', -2]], done: [['bonus.inflation', -1], ['nation.jobs', 4], ['bonus.jobs', 0.02]], news: ['FARMERS GET 25-YEAR LEASES THEY CAN BORROW AGAINST', 'FARMER FIT USE LAND COLLECT LOAN NOW'], archive: 'Created secure, tradable agricultural leases.' }),
    g2({ id: 'f7', name: 'Modern extension, soil and weather services', pc: 4, naira: 0.4, months: 10, blurb: 'An extension worker for every thousand farmers, soil tests, and a text message before the rains fail.', done: [['bonus.inflation', -1.5], ['nation.jobs', 3]], news: ['FARMERS GET WEATHER WARNINGS BY TEXT', 'PHONE DON DEY TELL FARMER WHEN RAIN GO FALL'], archive: 'Built modern extension, soil and weather services.' }),
    g2({ id: 'f8', name: 'Warehouse receipts and commodity markets', pc: 6, naira: 0.3, months: 10, blurb: 'Grain stored in certified warehouses, sold on an exchange, borrowed against. The middlemen who buy at harvest and sell in the hungry season will notice.', start: [['tycoon.ty_trade', -6]], done: [['bonus.inflation', -1.5], ['nation.jobs', 3], ['bloc.establishment', 3]], news: ['COMMODITY EXCHANGE TRADES ITS FIRST MILLION TONNES', 'FARMER FIT SELL GRAIN FOR EXCHANGE NOW'], archive: 'Set up warehouse receipts and commodity markets.' }),
    g2({ id: 'f9', name: 'A national crop insurance pool', pc: 4, naira: 0.5, months: 8, blurb: 'A failed harvest is insured, not a ruin.', done: [['bloc.street', 3], ['zone.NW.approval', 3], ['zone.NE.approval', 3], ['bonus.fiscal', -0.01]], news: ['CROP INSURANCE PAYS OUT AFTER DROUGHT', 'FARM SPOIL? INSURANCE GO PAY'], archive: 'Created a national crop insurance pool.' }),
    g2({ id: 'f10', name: 'A cold chain and agro-processing network', pc: 4, naira: 0.8, months: 12, blurb: 'Half the tomatoes rot between farm and market. Cold stores and factories near the farms.', done: [['bonus.inflation', -2], ['nation.jobs', 6], ['bonus.jobs', 0.03]], news: ['COLD CHAIN CUTS FOOD WASTE BY HALF', 'TOMATO NO GO ROT AGAIN'], archive: 'Built a cold chain and agro-processing network.' }),
    g3({ id: 'f11', name: 'Compensate farmers hit by the import trigger', pc: 4, naira: 0.3, months: 4, emerge: (s) => done(s, 'f4') && s.zones.NC.approval < 45, emergeText: 'The import trigger kept prices down in the cities and broke farmers in the North Central.', blurb: 'A price floor paid to registered farmers when the trigger opens the borders.', done: [['zone.NC.approval', 6], ['zone.NW.approval', 4], ['bloc.party', 3], ['bonus.fiscal', -0.01]], news: ['FARMERS COMPENSATED WHEN IMPORT TRIGGER OPENS', 'FARMER GO GET SOMETHING WHEN BORDER OPEN'], archive: 'Compensated farmers hit by the food-import trigger.' }),
  ],
  industry: [
    g2({ id: 'i6', name: 'A national single trade window', pc: 6, naira: 0.3, months: 8, blurb: 'One submission for every import and export document, in place of fourteen agencies at the port.', done: [['nation.jobs', 4], ['nation.capacity', 2], ['bonus.fiscal', 0.01], ['nation.integrity', 2]], news: ['SINGLE TRADE WINDOW REPLACES FOURTEEN PORT AGENCIES', 'ONE FORM FOR PORT NOW'], archive: 'Built a national single trade window.' }),
    g2({ id: 'i7', name: 'Export credit and insurance', pc: 4, naira: 0.5, months: 8, blurb: 'Exporters insured against buyers who do not pay, and financed on their orders.', done: [['nation.jobs', 5], ['bonus.jobs', 0.03]], news: ['EXPORT CREDIT AGENCY BACKS FIRST THOUSAND EXPORTERS', 'EXPORTERS DON GET BACKUP'], archive: 'Created export credit and insurance.' }),
    g2({ id: 'i8', name: 'Standards and testing that buyers trust', pc: 4, naira: 0.4, months: 10, blurb: 'Laboratories whose certificates are accepted abroad, so that Nigerian goods stop being rejected at foreign ports.', done: [['nation.jobs', 4], ['bonus.jobs', 0.02], ['nation.capacity', 2]], news: ['NIGERIAN STANDARDS NOW ACCEPTED IN EUROPE', 'OYINBO DON ACCEPT OUR CERTIFICATE'], archive: 'Built standards and testing that foreign buyers trust.' }),
    g2({ id: 'i9', name: 'Competition and anti-cartel enforcement', pc: 10, naira: 0, months: 8, blurb: 'Prices fixed by three firms in cement, sugar and flour, investigated and fined.', start: [['tycoon.ty_maker', -10], ['tycoon.ty_trade', -6]], done: [['bonus.inflation', -1.5], ['nation.jobs', 3], ['bloc.street', 4], ['nation.integrity', 2]], news: ['CEMENT AND SUGAR CARTELS FINED', 'CEMENT PRICE DON FALL AFTER FINE'], archive: 'Enforced competition law against cartels.' }),
    g2({ id: 'i10', name: 'A domestic supplier-development programme', pc: 4, naira: 0.4, months: 10, blurb: 'Big firms and the state helped to buy from small Nigerian suppliers that meet the standard.', done: [['nation.jobs', 5], ['bonus.jobs', 0.03], ['bloc.street', 2]], news: ['SMALL FIRMS WIN BIG CONTRACTS UNDER SUPPLIER PROGRAMME', 'SMALL BUSINESS DON DEY SUPPLY BIG COMPANY'], archive: 'Started a domestic supplier-development programme.' }),
    g3({ id: 'i11', name: 'Break the cartel that grew behind the procurement mandate', pc: 6, naira: 0, months: 6, emerge: (s) => done(s, 'i3') && s.nation.integrity < 35, emergeText: 'Buy Nigerian created three "Nigerian" suppliers who import, relabel and charge double.', blurb: 'Audit every mandated supplier; those relabelling imports lose their status.', start: [['tycoon.ty_maker', -8]], done: [['nation.integrity', 4], ['bonus.fiscal', 0.01], ['nation.jobs', 2]], news: ['RELABELLED-IMPORT RING BROKEN UP', 'DEM DEY CHANGE LABEL. NOW DEM DON CATCH'], archive: 'Broke the cartel behind the procurement mandate.' }),
  ],
  digital: [
    g2({ id: 'd6', name: 'Government cloud and open interfaces', pc: 4, naira: 0.4, months: 10, blurb: 'Every ministry\'s systems on one cloud, talking to each other through open interfaces any firm can build on.', done: [['nation.capacity', 5], ['nation.jobs', 3], ['bonus.capacity', 0.02]], news: ['MINISTRIES MOVE TO ONE GOVERNMENT CLOUD', 'GOVERNMENT COMPUTER DON DEY TALK TO EACH OTHER'], archive: 'Built a government cloud with open interfaces.' }),
    g2({ id: 'd7', name: 'Cybersecurity and data-protection enforcement', pc: 6, naira: 0.2, months: 8, blurb: 'A regulator that fines those who leak citizens\' data, the government included.', done: [['nation.capacity', 2], ['bloc.press', 3], ['nation.integrity', 2]], news: ['FIRST FINE FOR LEAKING CITIZENS\' DATA', 'WHO LEAK YOUR DATA GO PAY'], archive: 'Enforced cybersecurity and data protection.' }),
    g2({ id: 'd8', name: 'University research, turned into companies', pc: 4, naira: 0.3, months: 10, blurb: 'Universities allowed to own and license what they invent, and grants that follow the ones that sell.', done: [['nation.jobs', 3], ['bonus.jobs', 0.02], ['bloc.establishment', 2]], news: ['UNIVERSITY SPIN-OFFS RAISE FIRST ROUNDS', 'UNIVERSITY DON START TO MAKE MONEY'], archive: 'Turned university research into companies.' }),
    g2({ id: 'd9', name: 'A framework for exporting digital services', pc: 4, naira: 0.1, months: 6, blurb: 'Contracts, tax and payments set up so that Nigerians selling services abroad can be paid at home, officially.', done: [['nation.jobs', 4], ['bonus.fiscal', 0.01], ['bonus.jobs', 0.02]], news: ['DIGITAL EXPORTS EARN A BILLION DOLLARS', 'WE DON DEY SELL SERVICE GIVE OYINBO'], archive: 'Built a framework for exporting digital services.' }),
    g2({ id: 'd10', name: 'Competitive spectrum and open-access telecoms', pc: 8, naira: 0, months: 8, blurb: 'Spectrum auctioned in public, towers shared, and an end to the operators who hold frequencies they never use.', start: [['tycoon.ty_bank', -4]], done: [['nation.jobs', 4], ['bonus.fiscal', 0.015], ['bloc.street', 3]], news: ['SPECTRUM AUCTION RAISES RECORD; DATA PRICES FALL', 'DATA DON CHEAP'], archive: 'Auctioned spectrum and opened telecoms access.' }),
    g3({ id: 'd11', name: 'Bring the data breaches to account', pc: 4, naira: 0.1, months: 4, emerge: (s) => done(s, 'd4') && !!s.flags['data.breach'], emergeText: 'A newspaper has published samples of identity records offered for sale. The agency denies it, and nobody has yet investigated: it is an allegation, not a finding.', blurb: 'An inquiry, prosecutions, and a rule that breaches are reported within three days.', done: [['nation.integrity', 3], ['bloc.press', 4], ['pressure.scandalHeat', -6]], news: ['IDENTITY DATA BREACH: OFFICIALS CHARGED', 'WHO SELL OUR DATA DON CATCH'], archive: 'Brought the data breaches to account.' }),
  ],
  works: [
    g2({ id: 'w6', name: 'Roads maintained under performance contracts', pc: 4, naira: 0.5, months: 10, blurb: 'Contractors paid for roads kept passable, not for roads announced.', done: [['nation.jobs', 4], ['bonus.jobs', 0.02], ['approval', 2]], news: ['ROADS NOW MAINTAINED BY RESULT', 'ROAD NO GO SPOIL AGAIN?'], archive: 'Put road maintenance on performance contracts.' }),
    g2({ id: 'w7', name: 'Open-access freight rail', pc: 6, naira: 0.3, months: 10, blurb: 'Any licensed operator can run freight trains on the national lines, for a published fee.', done: [['nation.jobs', 4], ['bonus.inflation', -0.5], ['bonus.fiscal', 0.01]], news: ['PRIVATE FREIGHT TRAINS RUN ON NATIONAL LINES', 'GOODS DON DEY MOVE BY TRAIN'], archive: 'Opened freight rail to any licensed operator.' }),
    g2({ id: 'w8', name: 'Independent appraisal before anything is built', pc: 6, naira: 0, months: 4, lasting: 'Big bets are appraised before they start: their odds are better.', blurb: 'Every project over ₦50bn appraised by an independent office before a contract is signed, and the appraisal published.', start: [['bloc.party', -4]], done: [['nation.capacity', 3], ['nation.integrity', 2], ['bloc.establishment', 4]], news: ['NO MEGA-PROJECT WITHOUT PUBLISHED APPRAISAL', 'NO MORE WHITE ELEPHANT PROJECT?'], archive: 'Required independent appraisal before construction.' }),
    g2({ id: 'w9', name: 'National logistics corridors and dry ports', pc: 4, naira: 0.8, months: 12, blurb: 'Inland container depots linked to the ports by rail, so that a container leaves Lagos in a day, not a month.', done: [['nation.jobs', 5], ['bonus.inflation', -0.5], ['bonus.jobs', 0.02]], news: ['DRY PORTS OPEN IN KANO AND KADUNA', 'CONTAINER NO GO STAY FOR PORT AGAIN'], archive: 'Built national logistics corridors and dry ports.' }),
    g2({ id: 'w10', name: 'Toll concessions on the main highways', pc: 8, naira: 0, months: 8, blurb: 'Private operators rebuild and run the busiest highways and charge tolls. The roads improve; the people who drive them pay.', start: [['bloc.street', -4]], done: [['nation.jobs', 3], ['bonus.fiscal', 0.02], ['bloc.street', -3], ['bloc.establishment', 4]], news: ['HIGHWAY TOLL CONCESSIONS SIGNED', 'TOLL GATE DON RETURN'], archive: 'Concessioned the main highways with tolls.' }),
  ],
  federation: [
    g2({ id: 'r8', name: 'Hard rules for state borrowing', pc: 8, naira: 0, months: 6, ...SENATE, blurb: 'States borrow only within a limit tied to what they collect.', start: [['bloc.party', -5]], done: [['nation.debt', -2], ['bloc.establishment', 4], ['nation.capacity', 2]], news: ['NEW LAW CAPS STATE BORROWING', 'STATES NO GO BORROW ANYHOW AGAIN'], archive: 'Imposed hard rules on state borrowing.' }),
    g2({ id: 'r9', name: 'Equalisation grants for poorer states', pc: 6, naira: 0.5, months: 6, blurb: 'A floor under the poorest states so that restructuring does not leave them behind.', done: [['zone.NE.approval', 4], ['zone.NW.approval', 3], ['bloc.party', 3], ['bonus.fiscal', -0.01]], news: ['POORER STATES GET EQUALISATION GRANTS', 'POOR STATES NO GO SUFFER'], archive: 'Created equalisation grants for poorer states.' }),
    g2({ id: 'r10', name: 'Who taxes what, and who does what, in the constitution', pc: 14, naira: 0, months: 12, ...AMEND, blurb: 'A clean list of which level of government taxes what and is responsible for what, in place of a concurrent list everyone blames.', done: [['nation.capacity', 5], ['bonus.capacity', 0.02], ['bloc.party', 3]], news: ['CONSTITUTION AMENDED: WHO TAXES WHAT IS NOW CLEAR', 'NOW WE KNOW WHO GO DO WETIN'], archive: 'Amended the constitution to assign taxes and functions.' }),
    g2({ id: 'r11', name: 'An intergovernmental dispute council', pc: 6, naira: 0, months: 6, blurb: 'Disputes between Abuja and the states settled at a table before they reach a court.', done: [['nation.capacity', 3], ['bloc.party', 3]], news: ['DISPUTE COUNCIL SETTLES FIRST FEDERAL-STATE ROW', 'FG AND STATES DON SETTLE'], archive: 'Created an intergovernmental dispute council.' }),
    g2({ id: 'r12', name: 'Autonomy tied to accountability', pc: 8, naira: 0, months: 8, blurb: 'States and local governments that publish their accounts and hold elections on time get more autonomy; those that do not, less.', start: [['bloc.party', -3]], done: [['nation.integrity', 3], ['nation.capacity', 3], ['bloc.street', 3]], news: ['STATE AUTONOMY NOW TIED TO PUBLISHED ACCOUNTS', 'PUBLISH YOUR ACCOUNT, GET YOUR FREEDOM'], archive: 'Tied state and local autonomy to accountability.' }),
    g3({ id: 'r13', name: 'Settle the census dispute', pc: 6, naira: 0.1, months: 4, emerge: (s) => done(s, 'r6') && s.blocs.party < 40, emergeText: 'The census moved seats and money from some states to others, and the losers say it was rigged.', blurb: 'An independent recount in the contested states, with the results binding.', done: [['bloc.party', 6], ['nation.integrity', 2]], news: ['CENSUS RECOUNT CONFIRMS MOST FIGURES', 'CENSUS QUARREL DON SETTLE'], archive: 'Settled the census dispute with an independent recount.' }),
  ],
  welfare: [
    { id: 'h8', name: 'A disability income floor', pc: 4, naira: 0.3, months: 6, blurb: 'A monthly payment for people who cannot work, verified once and paid without queues.', done: [['bloc.street', 4], ['approval', 2], ['bonus.fiscal', -0.008]], news: ['DISABILITY INCOME FLOOR BEGINS PAYMENTS', 'PEOPLE WITH DISABILITY GO GET MONTHLY MONEY'], archive: 'Created a disability income floor.' },
    g2({ id: 'h9', name: 'Transfers that rise with prices', pc: 4, naira: 0.3, months: 4, lasting: 'The monthly transfer keeps its value when inflation rises, so it does not have to be fought for again.', blurb: 'The transfer rises automatically with inflation.', done: [['bloc.street', 4], ['pressure.wageGrievance', -5], ['bonus.fiscal', -0.008]], news: ['CASH TRANSFERS NOW RISE WITH PRICES', 'TRANSFER GO FOLLOW PRICE GO UP'], archive: 'Indexed the cash transfers to inflation.' }),
    g2({ id: 'h10', name: 'A public-works guarantee in hard years', pc: 4, naira: 0.5, months: 6, blurb: 'In a downturn, a hundred days of paid work for anyone who asks, on roads, drains and schools.', done: [['nation.jobs', 4], ['bloc.street', 5], ['pressure.wageGrievance', -6], ['bonus.fiscal', -0.01]], news: ['PUBLIC-WORKS GUARANTEE OPENS IN ALL STATES', 'WORK DEY FOR ANYBODY WEY WANT'], archive: 'Created a public-works guarantee for hard years.' }),
    g2({ id: 'h11', name: 'A child nutrition benefit', pc: 4, naira: 0.4, months: 6, blurb: 'A payment to mothers of children under two, tied to clinic visits.', done: [['bloc.street', 4], ['approval', 2], ['bonus.fiscal', -0.008]], news: ['CHILD NUTRITION BENEFIT REACHES FIVE MILLION MOTHERS', 'MAMA DEM DON DEY COLLECT FOR PIKIN'], archive: 'Created a child nutrition benefit.' }),
    g2({ id: 'h12', name: 'A social pension for the over-seventies', pc: 4, naira: 0.5, months: 6, blurb: 'A small monthly pension for every citizen over seventy, paid by phone.', done: [['bloc.street', 5], ['approval', 3], ['bonus.fiscal', -0.012]], news: ['EVERY CITIZEN OVER 70 TO GET A PENSION', 'OLD PEOPLE DON GET PENSION'], archive: 'Created a social pension for the over-seventies.' }),
    g2({ id: 'h13', name: 'Unemployment insurance for formal workers', pc: 6, naira: 0.2, months: 8, blurb: 'Workers and employers pay in; a worker who loses a job is paid while they find the next.', done: [['pressure.wageGrievance', -6], ['nation.jobs', 2], ['bloc.establishment', 2]], news: ['UNEMPLOYMENT INSURANCE SCHEME LAUNCHED', 'IF YOU LOSE WORK, YOU GO STILL GET SOMETHING'], archive: 'Created unemployment insurance for formal workers.' }),
    g3({ id: 'h15', name: 'Re-index the transfers after the price shock', pc: 2, naira: 0.3, months: 3, emerge: (s) => done(s, 'h3') && !done(s, 'h9') && s.nation.inflation > 25, emergeText: 'Inflation has eaten half of what the monthly transfer was worth.', blurb: 'A one-off increase to restore what prices took.', done: [['bloc.street', 5], ['pressure.wageGrievance', -5], ['bonus.fiscal', -0.006]], news: ['CASH TRANSFERS RAISED AFTER PRICE SHOCK', 'TRANSFER MONEY DON INCREASE'], archive: 'Re-indexed the cash transfers after a price shock.' }),
  ],
  order: [
    { id: 'o9', name: 'A national disaster-response service', pc: 4, naira: 0.5, months: 8, emerge: (s) => s.flags['night.dam'] === 'large', emergeText: 'The water came in the night and there was nobody to send.', lasting: 'When the rivers rise, there is a service to send: the nights of the water go better.', blurb: 'Boats, helicopters and trained crews in every zone, with the authority to evacuate.', done: [['nation.capacity', 3], ['bloc.street', 3], ['approval', 2]], news: ['NATIONAL DISASTER SERVICE STANDS UP IN ALL SIX ZONES', 'WHEN FLOOD COME, HELP GO COME'], archive: 'Created a national disaster-response service.' },
    { id: 'o10', name: 'Community reconciliation and peace commissions', pc: 6, naira: 0.3, months: 10, blurb: 'Commissions in the worst-divided communities, with compensation and the power to name who started it.', done: [['drift.NC', -0.08], ['drift.NW', -0.05], ['drift.SE', -0.05], ['zone.NC.approval', 3]], news: ['PEACE COMMISSIONS BEGIN HEARINGS IN THE FARM BELT', 'PEACE TALK DON START'], archive: 'Set up community reconciliation and peace commissions.' },
    { id: 'o11', name: 'National service, made a real civic programme', pc: 6, naira: 0.4, months: 10, blurb: 'A year of service that builds something, in a state far from home, with skills at the end.', done: [['nation.jobs', 3], ['bloc.street', 3], ['nation.capacity', 2]], news: ['REFORMED NATIONAL SERVICE BUILDS 10,000 CLASSROOMS', 'CORPERS DON DEY BUILD SCHOOL'], archive: 'Reformed national service into a civic programme.' },
    { id: 'o12', name: 'Citizenship and residency rights that work everywhere', pc: 10, naira: 0, months: 8, ...SENATE, blurb: 'A Nigerian who lives in a state is a resident of it, whatever their parents\' origin: jobs, schools and land on the same terms.', start: [['bloc.party', -4]], done: [['nation.integrity', 2], ['bloc.street', 4], ['nation.jobs', 2], ['drift.all', -0.03]], news: ['RESIDENCY RIGHTS LAW ENDS "INDIGENE" DISCRIMINATION', 'WHERE YOU DEY LIVE NA YOUR STATE'], archive: 'Made citizenship and residency rights work everywhere.' },
    { id: 'o13', name: 'A public order act: permits for large demonstrations', pc: 5, naira: 0, months: 4, popular: true, ...SENATE, lasting: 'Protests need a permit. The principled can no longer embarrass you in the street as easily; the government is a little less trusted every month.', blurb: 'Any gathering over five hundred needs a police permit. Your security chiefs are keen. So were the last three governments\' security chiefs.', start: [['bloc.villa', 4], ['bloc.press', -4]], done: [['pressure.wageGrievance', -10], ['bloc.establishment', 3], ['bloc.street', -6], ['nation.integrity', -3]], flags: { 'order.permits': true }, news: ['PUBLIC ORDER ACT: PROTESTS NOW NEED POLICE PERMIT', 'TO PROTEST, YOU GO NEED PERMIT NOW'], archive: 'Signed a public order act requiring permits for demonstrations.' },
    { id: 'o14', name: 'National harmony broadcasting rules', pc: 5, naira: 0, months: 4, popular: true, lasting: 'Broadcasters who "threaten national harmony" lose their licences. Coverage softens; the press trusts you less.', blurb: 'A code for broadcasters, enforced by a commission you appoint, against content that "threatens national harmony".', start: [['bloc.press', -6]], done: [['pressure.scandalHeat', -10], ['bloc.villa', 3], ['bloc.press', -8], ['nation.integrity', -3]], news: ['BROADCASTERS PUT ON NEW "NATIONAL HARMONY" CODE', 'TV NO FIT TALK ANYHOW AGAIN'], archive: 'Imposed national harmony rules on broadcasters.' },
    g3({ id: 'o15', name: 'Repeal the emergency powers', pc: 6, naira: 0, months: 4, emerge: (s) => (done(s, 'o13') || done(s, 'o1') || done(s, 'o14')) && s.blocs.street < 35, emergeText: 'The powers that were meant for disorder are being used on ordinary critics, and the street knows it.', blurb: 'The permit rule, the broadcasting code and the falsehood law, reviewed and cut back by an independent panel.', start: [['bloc.villa', -4]], done: [['bloc.street', 6], ['bloc.press', 6], ['nation.integrity', 4]], news: ['EMERGENCY POWERS CUT BACK AFTER REVIEW', 'DEM DON REDUCE THE POWER WEY DEM DEY USE PRESS US'], archive: 'Repealed the emergency powers after an independent review.' }),
  ],
  resources: [
    { id: 'g13', name: 'A national energy company that keeps the oil stakes', pc: 8, naira: 0.3, months: 10, excludes: ['g4'], blurb: 'The state keeps its share of the oil ventures and builds a company to run it like a business. Accountable, if you let it be.', done: [['bonus.fiscal', 0.03], ['nation.jobs', 3], ['bloc.establishment', -2], ['nation.integrity', -1]], news: ['NATIONAL ENERGY COMPANY TO HOLD STATE\'S OIL STAKES', 'GOVERNMENT GO KEEP THE OIL SHARE'], archive: 'Created a national energy company to keep the oil stakes.' },
    g2({ id: 'g8', name: 'Gas-based industrialisation', pc: 6, naira: 0.8, months: 14, blurb: 'Fertiliser, methanol and steel built on gas that used to be flared.', done: [['nation.jobs', 6], ['bonus.jobs', 0.03], ['bonus.fiscal', 0.015]], news: ['GAS INDUSTRIAL PARK OPENS IN THE DELTA', 'GAS DON DEY MAKE FERTILISER'], archive: 'Built gas-based industries.' }),
    g2({ id: 'g9', name: 'A geological survey and a modern mining cadastre', pc: 4, naira: 0.4, months: 10, blurb: 'Know what is in the ground, and record who holds every licence, in public.', done: [['nation.jobs', 3], ['bonus.fiscal', 0.01], ['nation.integrity', 2]], news: ['FIRST NATIONAL GEOLOGICAL MAP IN FIFTY YEARS', 'NOW WE KNOW WETIN DEY UNDER GROUND'], archive: 'Completed a geological survey and a mining cadastre.' }),
    g2({ id: 'g10', name: 'Export certification and logistics for crops', pc: 4, naira: 0.3, months: 8, blurb: 'Certified, traced and shipped: crops that used to be rejected at foreign ports accepted at a premium.', done: [['nation.jobs', 3], ['bonus.fiscal', 0.01], ['zone.NW.approval', 2], ['zone.SW.approval', 2]], news: ['NIGERIAN SESAME AND COCOA WIN PREMIUM CERTIFICATION', 'OUR CROPS DON DEY SELL FOR HIGH PRICE ABROAD'], archive: 'Built export certification and logistics for crops.' }),
    g2({ id: 'g11', name: 'Creative and tourism exports', pc: 4, naira: 0.3, months: 8, blurb: 'Film, music and travel treated as the exports they are: visas, copyright enforcement and payment rails.', done: [['nation.jobs', 4], ['bloc.street', 3], ['bonus.fiscal', 0.01]], news: ['NOLLYWOOD AND MUSIC EXPORTS PASS OIL BLOCK REVENUE', 'MUSIC DON DEY BRING DOLLAR'], archive: 'Made creative and tourism exports a strategy.' }),
    g2({ id: 'g12', name: 'A green industrial and carbon-market strategy', pc: 6, naira: 0.3, months: 10, blurb: 'Solar assembly, carbon credits from forests and flaring cuts, sold at a price.', done: [['nation.jobs', 3], ['bonus.fiscal', 0.01], ['bloc.establishment', 3]], news: ['FIRST CARBON CREDITS SOLD FROM FLARING CUTS', 'CARBON DON DEY BRING MONEY'], archive: 'Adopted a green industrial and carbon-market strategy.' }),
    g3({ id: 'g14', name: 'Share the gas revenue with the host communities', pc: 6, naira: 0.3, months: 6, emerge: (s) => done(s, 'g1') && s.theatres.SS >= 60, emergeText: 'The gas is being piped away from the villages it came from, and the creeks are angry.', blurb: 'A share of gas revenue paid into community trusts in the producing villages.', done: [['theatre.SS', -6], ['drift.SS', -0.06], ['zone.SS.approval', 5]], news: ['HOST COMMUNITIES GET SHARE OF GAS REVENUE', 'GAS MONEY DON REACH VILLAGE'], archive: 'Shared gas revenue with host communities.' }),
  ],
};

// ------------------------------------------------------------ new tracks
export const NEW_TRACKS: Track[] = [
  {
    id: 'schools', name: 'Schools and Skills', goal: 'Children who are in school and learning', metric: 'bloc.street',
    milestones: [
      { id: 'k1', name: 'Every child actually in basic education', pc: 4, naira: 0.5, months: 10, blurb: 'Ten million children out of school, counted by name and brought in: places, teachers and a reason for parents to send them.', done: [['bloc.street', 5], ['approval', 2], ['bonus.jobs', 0.02], ['zone.NW.approval', 3], ['zone.NE.approval', 3]], news: ['FIVE MILLION OUT-OF-SCHOOL CHILDREN ENROLLED', 'PIKIN DEM DON ENTER SCHOOL'], archive: 'Brought out-of-school children into basic education.' },
      { id: 'k2', name: 'Teacher payroll and attendance, cleaned up', pc: 6, naira: 0, months: 6, blurb: 'Every teacher seen in a classroom before being paid. Some schools have more teachers on the payroll than pupils.', start: [['pressure.wageGrievance', 4]], done: [['nation.capacity', 3], ['bonus.fiscal', 0.01], ['nation.integrity', 2]], news: ['TEACHER PAYROLL AUDIT REMOVES 60,000 GHOST TEACHERS', 'TEACHER WEY NO DEY CLASS NO GO COLLECT SALARY'], archive: 'Cleaned up teacher payroll and attendance.' },
      g2({ id: 'k6', name: 'National learning assessments', pc: 4, naira: 0.1, months: 6, blurb: 'Every child tested at nine and twelve, every school\'s results published.', done: [['nation.capacity', 3], ['bloc.press', 3]], news: ['FIRST NATIONAL LEARNING RESULTS PUBLISHED', 'NOW WE KNOW WHICH SCHOOL DEY TEACH'], archive: 'Introduced national learning assessments.' }),
      g2({ id: 'k7', name: 'Teachers as professionals: training, licensing and pay', pc: 6, naira: 0.6, months: 12, blurb: 'Licensed teachers, trained properly, paid like the profession they are.', done: [['bloc.street', 4], ['pressure.wageGrievance', -6], ['bonus.jobs', 0.02], ['bonus.fiscal', -0.01]], news: ['TEACHERS GET PROFESSIONAL LICENCES AND NEW PAY', 'TEACHER DON BECOME PROFESSIONAL'], archive: 'Professionalised teaching.' }),
      g2({ id: 'k8', name: 'Technical colleges and apprenticeships', pc: 4, naira: 0.5, months: 10, blurb: 'Colleges run with employers, and apprenticeships that end in a certificate the employers wrote.', done: [['nation.jobs', 5], ['bonus.jobs', 0.03]], news: ['TECHNICAL COLLEGES REOPEN WITH INDUSTRY PARTNERS', 'TECHNICAL SCHOOL DON RETURN'], archive: 'Rebuilt technical colleges and apprenticeships.' }),
      g2({ id: 'k9', name: 'A school inspectorate with teeth', pc: 4, naira: 0.1, months: 6, blurb: 'Inspectors who can close a school that does not teach, public or private.', done: [['nation.capacity', 2], ['bloc.street', 3]], news: ['SCHOOL INSPECTORS CLOSE 300 FAILING SCHOOLS', 'SCHOOL WEY NO DEY TEACH DON CLOSE'], archive: 'Created a school inspectorate with teeth.' }),
      g2({ id: 'k10', name: 'Early-years classes in every public school', pc: 4, naira: 0.4, months: 10, blurb: 'A year of school before primary, where the gap between rich and poor children starts.', done: [['bloc.street', 4], ['bonus.jobs', 0.02], ['bonus.fiscal', -0.008]], news: ['NURSERY CLASSES OPEN IN EVERY PUBLIC SCHOOL', 'PIKIN FIT START SCHOOL EARLY NOW'], archive: 'Opened early-years classes in every public school.' }),
      g2({ id: 'k11', name: 'Universities set fees; student loans follow the student', pc: 10, naira: 0.2, months: 8, excludes: ['k12'], blurb: 'Universities run themselves and charge what they need; any student admitted can borrow, repaying only when they earn.', start: [['bloc.street', -6], ['pressure.wageGrievance', 4]], done: [['nation.capacity', 3], ['bonus.fiscal', 0.01], ['bloc.establishment', 5], ['bonus.jobs', 0.02]], news: ['UNIVERSITIES GAIN AUTONOMY; STUDENT LOANS LAUNCHED', 'SCHOOL FEES DON COME, LOAN DEY TOO'], archive: 'Gave universities autonomy, with fees and student loans.' }),
      g2({ id: 'k12', name: 'Free public universities, funded in full', pc: 6, naira: 1.0, months: 12, excludes: ['k11'], blurb: 'No fees at any public university, and the federation pays what it costs.', done: [['bloc.street', 8], ['approval', 3], ['pressure.wageGrievance', -5], ['bonus.fiscal', -0.025]], news: ['PUBLIC UNIVERSITIES ABOLISH FEES', 'UNIVERSITY DON FREE'], archive: 'Made public universities free and funded them.' }),
    ],
  },
  {
    id: 'justice', name: 'Justice That Works', goal: 'Courts that decide, and decisions that stick', metric: 'nation.integrity',
    milestones: [
      { id: 'j1', name: 'Clear the criminal remand backlog', pc: 4, naira: 0.2, months: 8, blurb: 'Seven in ten prisoners have never been tried. Judges sent into the prisons to hear their cases.', done: [['nation.integrity', 3], ['bloc.street', 4], ['nation.security', 2], ['bonus.fiscal', 0.005]], news: ['TWENTY THOUSAND REMAND CASES HEARD IN SIX MONTHS', 'PEOPLE WEY DEY PRISON WITHOUT TRIAL DON GET JUDGEMENT'], archive: 'Cleared the criminal remand backlog.' },
      { id: 'j2', name: 'Digitise the courts and publish every judgment', pc: 4, naira: 0.4, months: 10, lasting: 'Trials move faster: cases reach a verdict sooner.', blurb: 'Filing, scheduling and judgments online. Adjournments recorded and counted.', done: [['nation.capacity', 3], ['nation.integrity', 2]], news: ['EVERY JUDGMENT NOW ONLINE', 'COURT DON ENTER INTERNET'], archive: 'Digitised the courts and published every judgment.' },
      { id: 'j3', name: 'Commercial courts with hard timelines', pc: 6, naira: 0.2, months: 8, blurb: 'Contract disputes decided in a year, so that a business can enforce what it signed.', done: [['nation.jobs', 4], ['bonus.jobs', 0.02], ['bloc.establishment', 4]], news: ['COMMERCIAL COURTS DECIDE CASES IN UNDER A YEAR', 'BUSINESS CASE NO GO TAKE TEN YEARS AGAIN'], archive: 'Created commercial courts with hard timelines.' },
      { id: 'j4', name: 'Legal aid that reaches every state', pc: 4, naira: 0.3, months: 8, blurb: 'A lawyer for anyone who cannot afford one, in every state, from arrest.', done: [['bloc.street', 4], ['nation.integrity', 2]], news: ['LEGAL AID NOW IN ALL 36 STATES', 'POOR PEOPLE FIT GET LAWYER NOW'], archive: 'Extended legal aid to every state.' },
      { id: 'j5', name: 'Prison and sentencing reform', pc: 6, naira: 0.3, months: 8, ...SENATE, blurb: 'Non-custodial sentences for petty crime, parole that works, and prisons that are not schools for gangs.', start: [['bloc.press', -2]], done: [['nation.security', 3], ['nation.integrity', 2], ['bonus.fiscal', 0.008]], news: ['SENTENCING REFORM HALVES PRISON OVERCROWDING', 'SMALL CRIME NO GO PRISON AGAIN'], archive: 'Reformed prisons and sentencing.' },
      g2({ id: 'j6', name: 'Professional court administration', pc: 4, naira: 0.3, months: 8, blurb: 'Court managers who run the registry, so judges judge.', done: [['nation.capacity', 3], ['nation.integrity', 2]], news: ['COURT MANAGERS CUT CASE DELAYS BY A THIRD', 'COURT DON DEY RUN WELL'], archive: 'Professionalised court administration.' }),
      g2({ id: 'j7', name: 'An independent judicial appointments commission', pc: 10, naira: 0, months: 8, ...SENATE, lasting: 'Judges are chosen on merit: no judge you appoint can be reached, and the bench is harder to buy.', blurb: 'Judges chosen by a commission on published criteria, not by the Villa\'s list.', start: [['bloc.villa', -5]], done: [['nation.integrity', 5], ['bloc.establishment', 5], ['bonus.integrity', 0.03]], flags: { 'bench.merit': true }, news: ['JUDGES TO BE APPOINTED BY INDEPENDENT COMMISSION', 'PRESIDENT NO GO PICK JUDGE AGAIN'], archive: 'Created an independent judicial appointments commission.' }),
      g2({ id: 'j8', name: 'Enforce judgments against the government', pc: 8, naira: 0.5, months: 6, blurb: 'When the government loses in court, it pays, from a fund set aside for it.', start: [['bloc.villa', -2]], done: [['bloc.establishment', 6], ['nation.jobs', 3], ['nation.integrity', 3], ['bonus.fiscal', -0.01]], news: ['GOVERNMENT PAYS COURT JUDGMENTS FOR FIRST TIME', 'GOVERNMENT DON PAY WETIN COURT SAY'], archive: 'Enforced court judgments against the government.' }),
      g2({ id: 'j9', name: 'Modern evidence and forensic law', pc: 6, naira: 0.1, months: 6, ...SENATE, lasting: 'Digital and forensic evidence is admissible: convictions are likelier.', blurb: 'Phone records, video and forensic reports admissible, with rules for how they are gathered.', done: [['nation.integrity', 3], ['nation.security', 2]], news: ['NEW EVIDENCE LAW ADMITS DIGITAL PROOF', 'PHONE RECORD FIT ENTER COURT NOW'], archive: 'Modernised the law of evidence.' }),
      g2({ id: 'j10', name: 'A constitutional court for disputes between governments', pc: 14, naira: 0.2, months: 12, ...AMEND, lasting: 'Disputes over reforms go to a court that only hears them: freezing a reform is far harder.', blurb: 'A court that hears only constitutional cases, fast, so that the Supreme Court is not a queue.', done: [['nation.capacity', 3], ['nation.integrity', 3], ['bloc.establishment', 4]], news: ['CONSTITUTIONAL COURT SITS FOR THE FIRST TIME', 'NEW COURT FOR CONSTITUTION MATTER'], archive: 'Created a constitutional court.' }),
      g3({ id: 'j11', name: 'Clear the backlog the anti-corruption courts created', pc: 4, naira: 0.2, months: 6, emerge: (s) => done(s, 'c2') && openCases(s) >= 3, emergeText: 'The anti-corruption courts are working; so many cases are waiting that the time limits are being missed.', blurb: 'More judges, more prosecutors, and the time limits kept.', done: [['nation.integrity', 3], ['bloc.press', 3]], news: ['ANTI-CORRUPTION COURTS DOUBLED TO CLEAR BACKLOG', 'MORE JUDGE FOR CORRUPTION CASE'], archive: 'Cleared the anti-corruption courts\' backlog.' }),
    ],
  },
  {
    id: 'cities', name: 'Cities, Water and Housing', goal: 'Cities people can live in', metric: 'approval',
    milestones: [
      { id: 'u1', name: 'Clean water in the major urban systems', pc: 4, naira: 0.8, months: 12, blurb: 'Treatment works and pipes so that a city tap runs clean, not just on the day it is commissioned.', done: [['approval', 3], ['bloc.street', 5], ['zone.SW.approval', 2], ['zone.NW.approval', 2], ['bonus.fiscal', -0.008]], news: ['CLEAN TAP WATER RETURNS TO SIX CITIES', 'TAP WATER DON DEY RUN'], archive: 'Restored clean water to the major urban systems.' },
      { id: 'u2', name: 'Sewage and sanitation', pc: 4, naira: 0.7, months: 12, blurb: 'Sewers, treatment and public toilets. Cholera is a choice a city makes by not building them.', done: [['approval', 2], ['bloc.street', 4], ['nation.capacity', 2]], news: ['CHOLERA CASES FALL AS SEWERS OPEN', 'GUTTER DON DEY FLOW'], archive: 'Built sewage and sanitation systems.' },
      { id: 'u3', name: 'A modern land registry and planning permission', pc: 8, naira: 0.3, months: 10, blurb: 'Title in weeks, not years, and permission to build that follows a published plan.', start: [['bloc.party', -3]], done: [['nation.jobs', 4], ['bonus.fiscal', 0.01], ['nation.integrity', 3], ['bonus.jobs', 0.02]], news: ['LAND TITLE NOW IN SIX WEEKS', 'C OF O NO GO TAKE TEN YEARS AGAIN'], archive: 'Modernised the land registry and planning.' },
      { id: 'u4', name: 'Mass-transit compacts with the states', pc: 6, naira: 0.8, months: 14, blurb: 'Federal money for state bus and rail systems, if the state runs them properly.', done: [['approval', 3], ['bloc.street', 4], ['nation.jobs', 3], ['bonus.inflation', -0.5]], news: ['MASS TRANSIT OPENS IN LAGOS, KANO AND PORT HARCOURT', 'BUS AND TRAIN DON DEY FOR CITY'], archive: 'Signed mass-transit compacts with the states.' },
      g2({ id: 'u6', name: 'Slum upgrading, not demolition', pc: 6, naira: 0.5, months: 10, blurb: 'Water, drains, paths and title for the settlements where most city people live, instead of bulldozers.', done: [['bloc.street', 6], ['approval', 2], ['nation.integrity', 1]], news: ['SLUMS UPGRADED, NOT DEMOLISHED', 'DEM NO GO PULL DOWN OUR HOUSE AGAIN'], archive: 'Upgraded slums instead of demolishing them.' }),
      g2({ id: 'u7', name: 'A municipal property-tax compact', pc: 8, naira: 0, months: 8, blurb: 'Cities that value property and collect the tax keep it, and spend it where it was collected.', start: [['bloc.street', -3]], done: [['nation.capacity', 3], ['bonus.fiscal', 0.015], ['bloc.establishment', 2]], news: ['CITIES THAT COLLECT PROPERTY TAX GET TO KEEP IT', 'PROPERTY TAX DON START'], archive: 'Signed a municipal property-tax compact.' }),
      g2({ id: 'u8', name: 'Waste collection and recycling markets', pc: 4, naira: 0.3, months: 8, blurb: 'Collection paid by results, and a market for what is collected.', done: [['approval', 2], ['nation.jobs', 3], ['bloc.street', 3]], news: ['WASTE COLLECTION CONTRACTS PAID BY RESULT', 'DIRT DON DEY CLEAR'], archive: 'Built waste collection and recycling markets.' }),
      g2({ id: 'u9', name: 'Drainage built for the rains that are coming', pc: 4, naira: 0.7, months: 12, blurb: 'Drains, canals and retention basins built for the rains of the next thirty years.', done: [['approval', 3], ['bloc.street', 3], ['nation.capacity', 2]], news: ['NEW DRAINS HOLD AS RAINS BREAK RECORDS', 'FLOOD NO ENTER HOUSE THIS YEAR'], archive: 'Built climate-resilient drainage.' }),
      g2({ id: 'u10', name: 'New-city infrastructure without ghost towns', pc: 6, naira: 0.6, months: 12, blurb: 'Roads, power and water laid ahead of private builders, paid back by land sales, and nothing built by government that nobody will live in.', done: [['nation.jobs', 5], ['bonus.jobs', 0.02], ['bonus.fiscal', 0.008]], news: ['NEW CITY DISTRICTS FILL AS SERVICES ARRIVE FIRST', 'NEW CITY DON GET PEOPLE'], archive: 'Laid infrastructure for new cities without ghost towns.' }),
      g3({ id: 'u11', name: 'Rebuild after the floods', pc: 4, naira: 0.6, months: 8, emerge: (s) => s.flags['night.dam'] === 'large' || (s.nation.security < 30 && !done(s, 'w4')), emergeText: 'The floods took homes, bridges and roads, and nobody has rebuilt them.', blurb: 'Homes, bridges and roads rebuilt to a standard that survives the next flood.', done: [['approval', 3], ['bloc.street', 4], ['zone.NC.approval', 3], ['zone.SS.approval', 3]], news: ['FLOOD-HIT TOWNS REBUILT', 'WHERE FLOOD SPOIL DON BUILD BACK'], archive: 'Rebuilt after the floods.' }),
    ],
  },
];

// ------------------------------------------------------------ health (the old track, renamed and refilled)
export const HEALTH: M[] = [
  { id: 'm2', name: 'Essential medicines, reliably bought and delivered', pc: 4, naira: 0.4, months: 8, blurb: 'One pooled purchase of the medicines that matter, delivered to every clinic, tracked to the shelf.', done: [['bloc.street', 4], ['approval', 2], ['nation.integrity', 1]], news: ['CLINICS REPORT FULL SHELVES FOR FIRST TIME', 'DRUG DON DEY FOR CLINIC'], archive: 'Reliably bought and delivered essential medicines.' },
  { id: 'm3', name: 'Health workers who turn up, and incentives to go rural', pc: 6, naira: 0.4, months: 8, blurb: 'Attendance checked, and a rural allowance big enough that a doctor will take it.', start: [['pressure.wageGrievance', 3]], done: [['bloc.street', 4], ['zone.NE.approval', 3], ['zone.NW.approval', 3], ['bonus.fiscal', -0.008]], news: ['RURAL CLINICS STAFFED AS ALLOWANCE DOUBLES', 'DOCTOR DON REACH VILLAGE'], archive: 'Got health workers to turn up and go rural.' },
  { id: 'm5', name: 'A maternal and emergency-care network', pc: 4, naira: 0.6, months: 10, blurb: 'Ambulances, blood banks and a referral hospital within two hours of every woman giving birth.', done: [['bloc.street', 5], ['approval', 3], ['bonus.fiscal', -0.008]], news: ['MATERNAL DEATHS FALL A THIRD IN TWO YEARS', 'WOMAN NO GO DIE FOR BIRTH AGAIN'], archive: 'Built a maternal and emergency-care network.' },
  g2({ id: 'm6', name: 'Capitation and a proper referral system', pc: 6, naira: 0.3, months: 8, blurb: 'Clinics paid per patient registered, and patients referred up only when they need to be.', done: [['nation.capacity', 3], ['bloc.street', 3]], news: ['PRIMARY CARE PAID PER PATIENT', 'CLINIC GO DEY PAID FOR EVERY PATIENT'], archive: 'Introduced capitation and a referral system.' }),
  g2({ id: 'm7', name: 'Electronic patient and claims records', pc: 4, naira: 0.4, months: 10, blurb: 'One record per patient and claims paid electronically, so that fraud has somewhere to be found.', done: [['nation.capacity', 3], ['nation.integrity', 2]], news: ['ELECTRONIC HEALTH RECORDS IN EVERY STATE', 'HOSPITAL CARD DON ENTER COMPUTER'], archive: 'Built electronic patient and claims records.' }),
  g2({ id: 'm8', name: 'Local medicine and vaccine manufacturing', pc: 6, naira: 0.7, months: 14, blurb: 'Factories for the medicines and vaccines that are now imported, with the state as first buyer.', done: [['nation.jobs', 4], ['bonus.jobs', 0.02], ['bloc.establishment', 3]], news: ['FIRST NIGERIAN-MADE VACCINES LEAVE THE FACTORY', 'WE DON DEY MAKE OUR OWN VACCINE'], archive: 'Built local medicine and vaccine manufacturing.' }),
  g2({ id: 'm9', name: 'Teaching hospitals run on performance contracts', pc: 6, naira: 0.2, months: 8, blurb: 'Teaching hospitals given autonomy, and contracts that are renewed only if waiting times fall.', start: [['pressure.wageGrievance', 3]], done: [['nation.capacity', 3], ['bloc.street', 3]], news: ['TEACHING HOSPITALS SIGN PERFORMANCE CONTRACTS', 'TEACHING HOSPITAL GO PERFORM'], archive: 'Put teaching hospitals on performance contracts.' }),
  g2({ id: 'm10', name: 'Protection against catastrophic medical costs', pc: 4, naira: 0.5, months: 8, blurb: 'Nobody sells their land for an operation: the state pays above a ceiling.', done: [['bloc.street', 5], ['approval', 2], ['bonus.fiscal', -0.01]], news: ['NO FAMILY TO PAY MORE THAN CEILING FOR SURGERY', 'NOBODY GO SELL LAND FOR HOSPITAL BILL AGAIN'], archive: 'Protected families against catastrophic medical costs.' }),
  g2({ id: 'm11', name: 'Insurance for everyone, through the insurers', pc: 8, naira: 0.4, months: 10, excludes: ['m12'], blurb: 'Compulsory insurance, subsidised for the poor, run by competing insurers.', start: [['bloc.street', -2]], done: [['bloc.establishment', 5], ['nation.capacity', 2], ['bloc.street', 3], ['bonus.fiscal', -0.008]], news: ['HEALTH INSURANCE MADE COMPULSORY FOR ALL', 'EVERYBODY GO GET HEALTH INSURANCE'], archive: 'Made health insurance universal through the insurers.' }),
  g2({ id: 'm12', name: 'Tax-funded care, free at the clinic', pc: 6, naira: 1.0, months: 12, excludes: ['m11'], blurb: 'Primary and emergency care free at the point of use, paid from taxes.', done: [['bloc.street', 8], ['approval', 3], ['bonus.fiscal', -0.025]], news: ['PRIMARY CARE NOW FREE AT EVERY CLINIC', 'CLINIC DON FREE'], archive: 'Made primary care free, funded from taxes.' }),
  g3({ id: 'm13', name: 'Pay the insurers\' arrears', pc: 4, naira: 0.6, months: 4, emerge: (s) => (done(s, 'e4') || done(s, 'm11')) && s.nation.fiscalSpace < 0.3, emergeText: 'The government has not paid its share of the insurance premiums, and hospitals are turning insured patients away.', blurb: 'A schedule to pay what is owed to the scheme, and a rule that premiums are paid first.', done: [['bloc.street', 4], ['bloc.establishment', 3]], news: ['GOVERNMENT CLEARS HEALTH INSURANCE ARREARS', 'HOSPITAL GO ACCEPT INSURANCE AGAIN'], archive: 'Paid the health insurance arrears.' }),
];
