// Writes docs/playtest/BETS-AUDIT.md from the live bet definitions (plan 12.A1).
// Run: npx tsx tools/bets-audit.ts
// Every bet: cost and financing, months, what opens it, its conditions by kind,
// what it delivers, what it leaves if it fails, and what system it changes.

import fs from 'fs';
import { ASSETS } from '../content/assets';
import { ASSET_SYSTEMS } from '../content/asset-systems';
import { RISK_KIND_NAME, VENTURES } from '../content/ventures';

const fx = (list: readonly (readonly [string, number])[] = []) => list.map(([p, v]) => `${p} ${v > 0 ? '+' : ''}${v}`).join(', ') || '—';
const debt = (list: readonly (readonly [string, number])[] = []) => list.filter(([p]) => p.startsWith('debt.')).map(([p, v]) => `${p.slice(5)} ₦${v}tn`).join(', ');

const rows = VENTURES.map((v) => {
  const kinds = (['essential', 'cost', 'acceptance'] as const).map((k) => {
    const rs = v.risks.filter((r) => r.kind === k);
    return rs.length ? `${RISK_KIND_NAME[k]}: ${rs.map((r) => r.label).join('; ')}` : '';
  }).filter(Boolean).join('<br>');
  const financing = [`treasury ₦${v.naira}tn${v.partner ? ` (40% from ${v.partner} if friendly)` : ''}`, debt(v.start as unknown as [string, number][]) ? `borrowed at launch: ${debt(v.start as unknown as [string, number][])}` : '', debt(v.win as unknown as [string, number][]) ? `on success: ${debt(v.win as unknown as [string, number][])}` : '', debt(v.lose as unknown as [string, number][]) ? `on failure: ${debt(v.lose as unknown as [string, number][])}` : ''].filter(Boolean).join('; ');
  const system = ASSETS[v.id] ? `Asset in ${ASSETS[v.id].sites.join('/')}: ${ASSET_SYSTEMS[v.id]?.does ?? '—'}` : v.changes ?? '—';
  return `| ${v.id} | ${v.months} | ${financing} | ${v.opened ?? (v.when ? 'situational' : 'open')} | ${kinds}<br>Luck: ${Math.round((1 - v.top) * 100)}% | ${fx(v.win as unknown as [string, number][])} | ${fx(v.lose as unknown as [string, number][])} | ${system} |`;
});

const out = `# Big bets audit (plan 12.A1)

Generated by \`tools/bets-audit.ts\` from the live definitions; re-run after any change. Units are the game's: ₦tn at the game's scale, months.

Every bet opens in one of four ways (engine/bets.ts): in full; a missed opening, once, when a condition can still be put right; half its design (an asset can be finished later); or failure. Missing cost-and-speed factors slow the work by 12% each and add a monthly overrun of 12% of its monthly budget each, and count half against the odds. Essential and political conditions count in full. What remains at the top is luck.

## Findings fixed in this pass

- Diaspora bond: the text said "$2.4bn" while the game raises ₦1.2tn and owes it in eurobonds; the text and headline now state ₦1.2tn, owed to its holders. The blurb no longer claims remittances exceed oil earnings, which the dollar flow contradicts.
- Nuclear: the partner's ₦1tn loan, taken at launch, was not mentioned; the blurb states it, and the failure headline gives ₦2.5tn rather than "$2bn".
- Rail: the blurb's "$9bn loan" did not match the ₦1.5tn eurobond and ₦0.5tn treasury cost; both now stated.
- Buyback: "a third of the foreign debt" was wrong for ₦2.5tn of ₦5.7tn in eurobonds; now "nearly half the foreign bonds".
- Amnesty: delivered calm in the South South while its approvals, headlines and story were the North West and North Central bandit belt; it now calms the North West and North Central.
- Smelter: said "you now have the electricity" with no power condition; it now needs power at 55.
- Coastal highway and the games: failure added debt with no mention of financing; the coastal blurb states the treasury cost and domestic borrowing for overruns, and a failed games now adds ₦0.6tn of domestic bonds (named in the text) instead of an abstract debt-service jump.
- Refineries: the single refinery bet promised the three plants in the register; there are now three bets and three holdings (9f8bcd4).

## Every bet

| Bet | Months | Cost and financing | Opened by | Conditions | Delivers | If it fails | What it changes |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
fs.writeFileSync('docs/playtest/BETS-AUDIT.md', out);
console.log(`Wrote docs/playtest/BETS-AUDIT.md: ${rows.length} bets.`);
