// Verb audit (plan 07.A7, A11). Every choice whose label promises investigate, prosecute,
// appoint, negotiate, implement, monitor, a committee, talks or a delay is listed with what its
// outcomes actually do: only numbers, or a mechanism (a follow-up, a delayed effect, a flag,
// an operation, a record, a favour, a domain effect). Choices that promise a process and deliver
// only numbers are flagged: either the mechanism is added, or the label says it is limited.
// Usage: npx tsx tools/verb-audit.ts  (writes docs/playtest/experience/VERB-AUDIT.md)

import { writeFileSync } from 'node:fs';
import { EVENT_LIST } from '../content';

const VERBS: [string, RegExp][] = [
  ['investigate', /\b(investigat|probe|inquir|look into|audit)/i],
  ['prosecute', /\b(prosecut|charge|arrest|try them|to court)/i],
  ['appoint', /\b(appoint|name |nominate)/i],
  ['negotiate', /\b(negotiat|talks|bargain|meet them|sit down)/i],
  ['implement', /\b(implement|carry out|enforce)/i],
  ['monitor', /\b(monitor|watch|track)/i],
  ['committee', /\b(committee|panel|commission)/i],
  ['delay', /\b(delay|wait|defer|postpone|later|time)/i],
];

/** Reviewed by hand: the label is not a process, or the result concludes the process it names. */
const REVIEWED: Record<string, string> = {
  'minister.sponsor/hold': 'a public statement, not an investigation',
  'cabinet.leak/sack': 'a dismissal; the replacement is the mechanism elsewhere',
  'minor.chair/boards': 'patronage given at once, not an appointment process',
  'react.chiefs/use': 'posts given at once',
  'react.payroll/recover': 'explicitly no prosecution',
  'fin.lohor.senate/refuse': 'a refusal, not a delay',
  'absurd.goat/audit': 'the audit concludes in the result: nine days, eleven accounts',
  'absurd.goat/committee': 'satire of the committee; the result says it achieved nothing',
  'absurd.goat/payroll': 'the audit concludes in the result and pays the arrears',
  'absurd.mace/probe': 'the arrest, charge and bail conclude in the result',
  'farce.website/arrest': 'the arrest and release conclude in the result',
};
type Row = { event: string; choice: string; label: string; verb: string; mechanism: string[] };
const rows: Row[] = [];
for (const e of EVENT_LIST) for (const c of e.choices ?? []) {
  const hit = VERBS.find(([, re]) => re.test(c.label));
  if (!hit) continue;
  const mech = new Set<string>();
  for (const o of c.outcomes ?? []) {
    if (o.later?.length) mech.add('delayed effect');
    if (o.follow) mech.add('follow-up');
    if (o.flags && Object.keys(o.flags).length) mech.add('flag');
    if (o.ops?.length) mech.add(`op:${[...new Set(o.ops.map((x) => x[0]))].join('/')}`);
    if (o.domain) mech.add('domain record');
    if (o.favour) mech.add('favour');
    if (o.memory) mech.add('memory');
    if (o.exposure) mech.add('exposure');
  }
  rows.push({ event: e.id, choice: c.id, label: c.label, verb: hit[0], mechanism: [...mech] });
}
const bare = rows.filter((r) => !r.mechanism.length && !REVIEWED[`${r.event}/${r.choice}`]);
const reviewed = rows.filter((r) => !r.mechanism.length && REVIEWED[`${r.event}/${r.choice}`]);
const out = [
  '# Verb audit',
  '',
  'Plan 07.A7 and A11. Generated by `tools/verb-audit.ts`. A choice that promises a process should deliver one: a follow-up, a delayed effect, a record or an operation. Those that deliver only numbers are listed first.',
  '',
  `${rows.length} choices promise a process; ${bare.length} deliver only numbers.`,
  '',
  '## Only numbers',
  '',
  '| Event | Choice | Verb | Label |', '|---|---|---|---|',
  ...bare.map((r) => `| ${r.event} | ${r.choice} | ${r.verb} | ${r.label.replace(/\|/g, '/')} |`),
  '',
  '## Reviewed: no process to deliver, or concluded in the result',
  '',
  '| Event | Choice | Why |', '|---|---|---|',
  ...reviewed.map((r) => `| ${r.event} | ${r.choice} | ${REVIEWED[`${r.event}/${r.choice}`]} |`),
  '',
  '## With a mechanism',
  '',
  '| Event | Choice | Verb | Mechanism |', '|---|---|---|---|',
  ...rows.filter((r) => r.mechanism.length).map((r) => `| ${r.event} | ${r.choice} | ${r.verb} | ${r.mechanism.join(', ')} |`),
  '',
];
writeFileSync('docs/playtest/experience/VERB-AUDIT.md', out.join('\n'));
console.log(`${rows.length} process choices, ${bare.length} with only numbers.`);
for (const r of bare) console.log(`${r.event}/${r.choice} [${r.verb}] ${r.label}`);
